### ISSUE TITLE
Sticky overlays first item in DemoListActivity

### ISSUE THREAD

**Issue by dbof10** [facebook/litho#101]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
Scroll down and scroll up. The star of the first cannot be seen. When the second sticky header hits the top, then scroll down. The first star is visible again
![bug](https://cloud.githubusercontent.com/assets/10725747/25189577/c19c4c08-2553-11e7-9cf8-94fa59b1c89c.gif)

**Comment by passy** [comment]
@muraziz Fixed this a while ago. :)
