### ISSUE TITLE
LithoView update delay

### ISSUE THREAD

**Issue by hou3172568** [facebook/litho#1011]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
Litho 0.47

## Issues and Steps to Reproduce
When using LithoView as an Item in Android RecyclerView, when holder reuse and fast sliding causes update delays, causing the last view style to appear before updating to the new style; then  i use setRootSync API, there is not smooth

## Expected Behavior
the item update without delay

## Link to Code
//this case is reuse
if (tree != null && null != dataListenerWrapper) {
            //for async, update delays
            request()?.let {
                //let root component updateState
                dataListenerWrapper?.onReceive(it)
            }
            //for sync,not smooth
             tree?.setRootSync(MyComponent.create().build())
        }
}

**Comment by zielinskimz** [comment]
Hey, it's hard to tell what may be wrong based on the small code sample that you shared. It would be helpful if you could create a small project that reproduces the issue so that we can take a look.

**Comment by hou3172568** [comment]
In other words, the best practices for using LithoView in RecyclerView on Android
