### ISSUE TITLE
issue about viewpager component

### ISSUE THREAD

**Issue by zhengzhong1** [facebook/litho#1028]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
 0.47.0

## Issues and Steps to Reproduce
I need to dynamically adjust the height of the viewpager to achieve the effect shown in the following figure:
![image](https://p9-xtjj-sign.byteimg.com/tos-cn-i-73owjymdk6/199e5c1aa2e54400b49900a17c86a7dd~tplv-73owjymdk6-jj-mark-v1:0:0:0:0:5o6Y6YeR5oqA5pyv56S-5Yy6IEAg5LiA56yR6L2u5Zue:q75.awebp?rk3s=f64ab15b&x-expires=1729310726&x-signature=nW8D%2By25Jq7LreY7BN5uaLKqG1U%3D)
 
In Viewpager2, I can dynamically calculate and refresh the height of viewpager2 by listening to ViewPager2.OnPageChangeCallback, calculating the difference between the current page and the target page, and sliding the differencer;

In litho, I did not find the ViewPager2.OnPageChangeCallback interface, only the lower-level RecyclerView.OnScrollListener interface, so I am wondering if there is an implementation similar to the native ScrollEventAdapter in litho; 

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/java/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by zielinskimz** [comment]
Hey, I don't think it is possible with the existing ViewPager component unfortunately. You'd have to try to build your own component based on the ViewPager2 and expose the APIs you need.
