### ISSUE TITLE
StickyHeader not visible after scrolling back

### ISSUE THREAD

**Issue by pavlospt** [facebook/litho#106]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
`Issue:`StickyHeader is not visible after scrolling back.
`Steps to reproduce:`Create a RecyclerBinder and add components that are sticky.

## Expected Behavior
Expect the sticky header to be visible 

## Link to Code
Code Available here: [Recycler Spec](https://github.com/pavlospt/litho-playground/blob/master/app/src/main/java/com/pavlospt/lithoplayground/RecyclerTestSpec.java)

![Gif of the issue](https://cloud.githubusercontent.com/assets/1070871/25226072/3e7f2c9a-25cc-11e7-8ab6-85cfdb53f929.gif)

**Comment by passy** [comment]
@pavlospt Ooph, this was basically internet years ago. So sorry for the long delay. A lot has changed since then, including at least one direct fix for issues like this. Do you still see this bug?

**Comment by pavlospt** [comment]
@passy not sure If I still have the project :) Will check it and let you know !

**Comment by passy** [comment]
@pavlospt Awesome! And no rush, took me long enough here to respond. :)

**Comment by pavlospt** [comment]
@passy yeap it seems to be resolved :) Closing!

**Comment by passy** [comment]
@pavlospt Brilliant. Thanks for confirming! :)

**Comment by peterbanban** [comment]
@passy  Hello, I am now experiencing this problem, I am using the latest dependency package, I do not know how to solve it. This problem will only occur when the data is displayed more than one screen. Sometimes it can render a part. Sometimes the whole Sticky Header cannot be displayed.

**Comment by peterbanban** [comment]
![file](https://user-images.githubusercontent.com/26356010/40051114-28852f92-586c-11e8-83ab-78e5e9e80136.gif)
