### ISSUE TITLE
NoClassDefFoundError: com/facebook/jni/Countable when load liblib_fb_fbjni.so in Andorid 4.1

### ISSUE THREAD

**Issue by kosiarska** [facebook/litho#108]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate
i think it might be connected to https://github.com/facebook/yoga/issues/354 but i'm not sure

## Issues and Steps to Reproduce
1. Create new android project.
2. Add dependencies to gradle:
```
    compile 'com.facebook.litho:litho-core:0.2.0'
    compile 'com.facebook.litho:litho-widget:0.2.0'
    provided 'com.facebook.litho:litho-annotations:0.2.0'

    annotationProcessor 'com.facebook.litho:litho-processor:0.2.0'

    // SoLoader
    compile 'com.facebook.soloader:soloader:0.2.0'
```
3. Create simple text component in MainActivity:

```
@Override
public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    final ComponentContext context = new ComponentContext(this);

    final Component component = Text.create(context)
        .text("Hello World")
        .textSizeDip(50)
        .build();

    setContentView(LithoView.create(context, component));
}
```
4. Create custom Application class:
```
public class MyApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        SoLoader.init(this, false);
    }
}
```
5. Run app
## Expected Behavior
App should display hello world

## Link to Code
Stacktrace: https://pastebin.com/yjSNTe6T

**Comment by passy** [comment]
@kosiarska Yes, that's definitely the same issue as facebook/yoga#354. It's probably best to follow the progress over there as we can't do anything about it on the Litho side.

Thanks for the report! I'll leave it to @emilsjolander if he wants to keep both issues open.

**Comment by songjian931798** [comment]
I met this issue!!!

**Comment by kebbbnnn** [comment]
encountered this issue too on my android 4.2.2 device

**Comment by emilsjolander** [comment]
@kosiarska I've re-opened  facebook/yoga#354. Investigating now.

**Comment by emilsjolander** [comment]
https://github.com/facebook/yoga/commit/76f6a54327837bd1d791528409b9b0704e37bb76 should fix it. I'll create a new release on friday

**Comment by passy** [comment]
Haven't seen this since. Closing.

**Comment by wt1098078873** [comment]
@emilsjolander Excuse me. I got same problem in  `0.17.0` and crash on android `4.1.1` device every time. the [facebook/yoga@76f6a54](https://github.com/facebook/yoga/commit/76f6a54327837bd1d791528409b9b0704e37bb76) fix has't merged to `litho`?  

[`fbjni` in `litho`](https://github.com/facebook/litho/tree/master/lib/fbjni/src/main/java/com/facebook/jni) 
[`fbjni` in `yoga`](https://github.com/facebook/yoga/tree/master/lib/fb/src/main/java/com/facebook/jni)
