### ISSUE TITLE
Add support to convert existing XML layout to run on Litho

### ISSUE THREAD

**Issue by abhimuktheeswarar** [facebook/litho#109]
It would be awesome if Litho supports converting existing XML layouts we painstakingly created. We can design our layouts in the XML & preview it in Android Studio layout editor & use it with Litho.

**Comment by colriot** [comment]
That's an extremely long-term project and we sadly don't have a timespan to do that now. But if anyone wants to help with that, we will be more than happy.

**Comment by abhimuktheeswarar** [comment]
Jetpack Compose is here now!
