### ISSUE TITLE
Kotlin LayoutSpec files not found by the Processor

### ISSUE THREAD

**Issue by agrosner** [facebook/litho#114]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
I have a simple `LayoutSpec` that returns a single `Text` item. Defining it in Kotlin:
```kotlin
@LayoutSpec
class CurrentWeatherTopSpec {

    companion object {
        @JvmStatic
        @OnCreateLayout
        fun onCreateLayout(c: ComponentContext): ComponentLayout {
            return Column.create(c)
                    .child(Row.create(c)
                            .child(
                                    Text.create(c)
                                            .text("Current Weather")
                                            .build()
                            ).build())
                    .build()
        }
    }
}
```
Nothing gets generated. No `CurrentWeatherTopLayout` file created. If I create the same code in Java, it gets generated:

```java

@LayoutSpec
class CurrentWeatherTopSpec {

    @OnCreateLayout
    static ComponentLayout onCreateLayout(ComponentContext context) {
        return Column.create(c)
                    .child(Row.create(c)
                            .child(
                                    Text.create(c)
                                            .text("Current Weather")
                                            .build()
                            ).build())
                    .build();
    }
}
```

## Expected Behavior
I'd expect the corresponding generated component class.

Is this a bug or something I am doing wrong here?
I guess my real question here is what does Litho use to determine if the class is a proper `@LayoutSpec`. Also FYI im using `kapt` and using it for java files works fine, but when in Kotlin the processor does not work.

**Comment by grandstaish** [comment]
Are you using kapt3 or legacy kapt? I'm not certain, but I don't think legacy kapt will work with litho.

**Comment by agrosner** [comment]
looks like legacy KAPT. Is there a reason why legacy won't work? Its strange that java files work in kapt but not Kotlin files.

**Comment by grandstaish** [comment]
Legacy kapt used to convert kotlin code into stub class files, which in turn were run through the annotation processing tool. One of the (many) limitations of this idea is that class files don't have any information about method parameter names, which this library depends on. Lots of information in this article: https://medium.com/@workingkills/pushing-the-limits-of-kotlin-annotation-processing-8611027b6711

**Comment by agrosner** [comment]
ok. now that would make a lot more sense. would it be possible to add this in the getting started docs or somewhere else so it's clear? Thank you!

**Comment by passy** [comment]
I have yet to try using Litho with Kotlin. If you want to start some docs on how to do it, we'd certainly love to include it.

**Comment by ubuntudroid** [comment]
@grandstaish According to #119 it seems you got Litho to work with Kotlin. For some reason I'm running into the same problem like @agrosner meaning nothing gets generated. Would you mind setting up an example project so that we can compare our configurations?

**Comment by ubuntudroid** [comment]
Okay, got it working as well. I created a minimalistic project on Github pointing out Kotlin specific adaptions: https://github.com/ubuntudroid/litho-kotlin.

**Comment by pavlospt** [comment]
Irrelevant! Project already contains a Kotlin sample now :)! Can be closed!
