### ISSUE TITLE
Clarify necessary setup in `using-components`

### ISSUE THREAD

**Issue by passy** [facebook/litho#118]
As @jimfb pointed out, [the docs](https://github.com/facebook/litho/commit/fc8b6a9f7f02dfab8c82c21755e24334f33f0a51#commitcomment-21864271) are currently unclear about the required parts when instantiating Components.

We should clarify this.

**Comment by pavlospt** [comment]
@passy I think that he is referring to `two things`, because the updated version of the docs has the `ComponentTree` removed and keeps only the `ComponentView`.

If you rephrase it like `...you'll need a [ComponentView]...`, I guess it will be just fine!
