### ISSUE TITLE
Proposal to change component DI approach

### ISSUE THREAD

**Issue by grandstaish** [facebook/litho#119]
The annotation processor currently has hidden support for dependency injection through [DependencyInjectionHelper](https://github.com/facebook/litho/blob/master/litho-processor/src/main/java/com/facebook/litho/specmodels/model/DependencyInjectionHelper.java). 

Because of this implementation detail, the generated component classes instantiate the specs object in the generated code, e.g.:

```java
private ListItemSpec mSpec = new ListItemSpec();
```

This is quite unexpected. I expect that ListItemSpec never gets instantiated and the generated components will just call the static methods on the spec class directly. 

I discovered this because I like to add private constructors to my utility classes, e.g.:

```java
@LayoutSpec
final class ListItemSpec {

  ...

  private ListItemSpec() {
    throw new AssertionError("No instances.");
  }
}
```

This limitation also prevents Spec classes from being kotlin `object`s, e.g.:

Currently you must write:

```kotlin
@LayoutSpec
class ListItemSpec {

  companion object {
    @JvmStatic
    @OnCreateLayout
    fun onCreateLayout(
        c: ComponentContext,
        ...): ComponentLayout {
      ...
    }
  }
}
```

vs. what you could write (slightly more succinct):

```kotlin
@LayoutSpec
object ListItemSpec {

  @JvmStatic
  @OnCreateLayout
  fun onCreateLayout(
      c: ComponentContext,
      ...): ComponentLayout {
    ...
  }
}
```

I'd like to suggest an alternative approach for DI:

Keep the static methods in the specs and delete `DependencyInjectionHelper` (and all related code). If your spec needs dependencies, for whatever reason, you could pass an "Injector" through the Context as a system service. This is a relatively common pattern; you can see [an example in the u2020 app](https://github.com/JakeWharton/u2020/blob/master/src/main/java/com/jakewharton/u2020/data/Injector.java).

Example usage would look like this:

```java
@OnCreateLayout
static ComponentLayout onCreateLayout(
    ComponentContext c,
    ...) {
  Injector injector = Injector.obtain(c);
  Dep1 dep1 = injector.getDep1(); 
  Dep2 dep2 = injector.getDep2();
  // etc
  ...
}
```

Feel free to close if you have alternative plans for this or don't agree with the proposal. Also let me know if you want help with the implementation 👍

**Comment by IanChilds** [comment]
Sorry for the long delay. I've made half of the changes that you proposed here: https://github.com/facebook/litho/commit/b9a6fa71e2b85e408a81197cc407c95b260f61e3

Not all DI systems will support static injection so I don't think what you propose will work, though I like the approach.
