### ISSUE TITLE
Support Elevation property on Components

### ISSUE THREAD

**Issue by pavlospt** [facebook/litho#125]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
Add elevation to a Component without the need of wrapping it on a CardSpec which supports elevation.

## Expected Behavior
Able to add elevation to a Component.

## Link to Code
https://github.com/pavlospt/litho-playground/blob/master/app/src/main/java/com/pavlospt/lithoplayground/ButtonContainerSpec.java
Contains an example of the wrapping to a Card component, situation!

**Comment by bangonkali** [comment]
Hi Guys! Is there any news on this? Or is this idea not technically viable?

**Comment by mihaelao** [comment]
Under the hood, providing a `shadowElevation` prop will call the Android `setElevation` method on the View, so they are basically the same thing. https://github.com/facebook/litho/blob/3ad8bfba12a43e108602bcd8c63fd2404e6203cb/litho-core/src/main/java/com/facebook/litho/MountState.java#L1945
