### ISSUE TITLE
Add individual pools for container directions to save JNI calls

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#133]
To save on JNI calls when acquiring a yoga node from a pool we can pool nodes based on their flex direction. This task requires making some changes to the Yoga api for resetting node values so that we can reset all values except the flex direction. https://github.com/facebook/yoga

## Code pointers
https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/ComponentsPools.java#L75

https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/Column.java

https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/Row.java

https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/ColumnReverse.java

https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/RowReverse.java

**Comment by pavlospt** [comment]
@emilsjolander somthat would probably need to reset to YGNodeDefaults except for the direction?

**Comment by emilsjolander** [comment]
Yes. Hold off on this though, i'm currently working on it and we will see if it is worth it :)

**Comment by pavlospt** [comment]
@emilsjolander ok nice! Should anyone that is working on an issue add a comment on it, in order to avoid conflicting work? :)

**Comment by colriot** [comment]
As we are now removing all the pooling from Litho, this won't be done.
Closing
