### ISSUE TITLE
Make ComponentContext hidden

### ISSUE THREAD

**Issue by paveldudka** [facebook/litho#134]
Right now we need to create `ComponentContext` manually when using Litho. It seems like ComponentContext has little value outside of framework, so does it make sense to make it an implementation detail and make clients pass `android.Content.Context` instead? It can be wrapped into `ComponentContext` internally.
```
final ComponentContext context = new ComponentContext(this);

final Component component = Text.create(context)
    .text("Hello World")
    .textSizeDip(50)
    .build();
```

**Comment by passy** [comment]
I think this is mostly needed to allow for state updates. 

/cc @mihaelao

**Comment by mihaelao** [comment]
Hi @paveldudka, I agree that making that an implementation detail would be nice, but we can't do it with the current implementation of state updates. The ComponentContext holds on to information that is used for state updates, such as the unique keys of components, and it needs to be propagated throughout the ComponentTree hierarchy from parent to children components to ensure that state updates work correctly. I considered overloading the ##create## method to offer both options, but it would be much harder to enforce that the correct ComponentContext is used. 

You can see how the component context is passed down for state updates in the [docs](http://fblitho.com/docs/state). Check out the generated code to see how the information it holds is used.
