### ISSUE TITLE
Always wrap drawables that support displaylist precomputing with `DisplayListDrawable` instead of wrapping it only when we precomputed it.

### ISSUE THREAD

**Issue by muraziz** [facebook/litho#136]
Currently we wrap `TextDrawable` which supports display list precomputing with `DisplayListDrawable` only when we have precomputed display list and other times we use `TextDrawable` directly. This might lead to obscure bugs when some property set to original `TextDrawable` is not reflected on `DisplayListDrawable`.

### Code pointers
- https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/DisplayListDrawable.java
- https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/MountItem.java#L129

Point of contact: @pasqualeanatriello @muraziz

**Comment by colriot** [comment]
DisplayLists were removed from Litho. 
Closing as stale.
