### ISSUE TITLE
Return null when creating display list instances for new Android versions for which we don't have implementation yet

### ISSUE THREAD

**Issue by muraziz** [facebook/litho#137]
Currently for new versions of Android for which we don't have implementation we use previous version implementations when creating display list instances. That is not optimal because the API or behavior might change in new versions, therefore we should return null for new versions until we have proper implementation.

### Code pointers
- https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/displaylist/DisplayList.java#L37

Point of contact: @pasqualeanatriello @muraziz

**Comment by colriot** [comment]
DisplayLists were removed from Litho. 
Closing as stale.
