### ISSUE TITLE
Can you tell me why FeedItemComponentSpec use Recycler ?

### ISSUE THREAD

**Issue by zondaOf2012** [facebook/litho#139]
Hello,I can't understand what image need RecyclerBinder in the sample.
***[FeedItemComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/lithography/FeedItemComponentSpec.java) lines 38 ~ 45***
Who can help me to solve it?

**Comment by muraziz** [comment]
Hi @zondaOf2012, if you noticed in the sample app, for some images there you can scroll horizontally. If there is more than 1 image then instead of creating `SingleImageComponent` the horizontal RecyclerView is created by the binder that's passed as prop.

**Comment by zondaOf2012** [comment]
@muraziz Thank you so much
