### ISSUE TITLE
Add support for SnapHelpers on RecyclerSpec

### ISSUE THREAD

**Issue by marwanf1** [facebook/litho#143]
Can you add support for SnapHelper on the Recycler component? Looking at the implementation it could be added as an optional prop on the RecyclerSpec. This also helps if developers want the Recycler to have ViewPager scrolling behavior which can be achieved by adding a PagerSnapHelper.

I couldn't find a way to implement this in the current Litho release.

**Comment by barontxu** [comment]
Man you have to hack since they haven't add support and don't want developers get recyclerView easily. See this project below, hope it'll solve your problem.
https://github.com/barontxu/litho_snaphelper

**Comment by barontxu** [comment]
Sorry I do a "add ." without editing gitignore.

**Comment by marwanf1** [comment]
@barontxu thanks man that's a good solution. It's just weird that something like ViewPager is not part of Litho although it's a widely used component.

Thanks for the help.

**Comment by hussainahmad** [comment]
@
thanks dude, really good solution

**Comment by muraziz** [comment]
We now have official support for SnapHelper: https://www.facebook.com/groups/litho.android/permalink/111049929590158/
