### ISSUE TITLE
Can you give me a URL to study how to use ? I'm Chinese and I can't access  the URL "http://fblitho.com/docs/getting-started"

### ISSUE THREAD

**Issue by xingxingxiaoyu** [facebook/litho#144]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

## Expected Behavior
***Describe what you expected would happen.***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by passy** [comment]
@xingxingxiaoyu I'm sorry you're having trouble accessing the website. The documentation is also part of the repo here. You can check out https://github.com/facebook/litho/tree/master/docs for information on how to build the documentation yourself on your machine.

The sources for the getting started page is available here: https://github.com/facebook/litho/tree/master/docs/_docs/getting-started

**Comment by xingxingxiaoyu** [comment]
I get,and thank you.Lucky!
