### ISSUE TITLE
Image.create(c).drawableRes seems to block UI thread.

### ISSUE THREAD

**Issue by zondaOf2012** [facebook/litho#145]
I use litho to create layout，like this:
![image](https://cloud.githubusercontent.com/assets/3021796/25477138/127fd1f0-2b6f-11e7-8588-6396d9d7be36.png)
I found Image.drawableRes seems to block UI thread. [This](https://github.com/zondaOf2012/LithoSample/blob/master/my_study_litho/src/main/java/zonda/exercise/litho/postlist/ImagesComponentSpec.java) is my code.

**Comment by muraziz** [comment]
Hi @zondaOf2012, I've seen the code. Why do you think it is blocking UI thread? Can you give more details of your finding?

**Comment by zondaOf2012** [comment]
Hi @muraziz 
The scenario is as follows:
&emsp;&emsp;On starting the activity, I find activity is delay launching. When I commented [it's](https://github.com/zondaOf2012/LithoSample/blob/master/my_study_litho/src/main/java/zonda/exercise/litho/postlist/PostListItemComponentSpec.java) ***48 ~ 51 lines*** out , starting activity to accelerate significantly. So I doubted it. Besides, I use Android's Layout and ImageView, that's not the case.

**Comment by muraziz** [comment]
@zondaOf2012 can you post systrace of android version and litho version so that we can see what's happening there?

**Comment by zondaOf2012** [comment]
Hi, @muraziz 
I'm sorry I was so careless, android version has the questions too. This is due to the picture is so big.
