### ISSUE TITLE
How can I customize a expandView and grab all the touch event until unfold

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#146]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
read tutorials and docs, and can't find anything about replacing component dynamically.

## Expected Behavior
found something like expandCardView or some methods that can replace view or component dynamically.

**Comment by passy** [comment]
Sorry @barontxu, but this is not enough context to provide you with meaningful help. If you still have this issue, can you please reopen this with example code and/or a clearer definition of what you're trying to achieve?

**Comment by barontxu** [comment]
@passy of course, sorry for missing some details of the problem.
