### ISSUE TITLE
Codes in http://fblitho.com/docs/best-practices not work

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#147]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
follow http://fblitho.com/docs/best-practices

## Expected Behavior
works fine.

## Link to Code
http://fblitho.com/docs/best-practices

**Comment by barontxu** [comment]
It may only takes like 5minutes for you to fix it, but it's been 22hours.
Don't treat your open source project like trash.

**Comment by emilsjolander** [comment]
Hi @barontxu we don't appreciate the tone of your comment. We are not here to serve the community but rather work with it. Also your issue does not state how the code is broken. Either file a new issue with more detailed information or work with us to fix it by submitting a pull request.

**Comment by barontxu** [comment]
@emilsjolander I apologize if i use a wrong expression.And I know you're  not here to serve the community, but I think at least you should make codes in tutorial right.

**Comment by barontxu** [comment]
@emilsjolander But I resist your tutorial and docs are not in state a open-source project should be .
