### ISSUE TITLE
Lots of meaningless href in  http://fblitho.com

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#148]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
 http://fblitho.com/docs/inc-mount and click href

## Expected Behavior
Redirect to some page meaningful.

**Comment by muraziz** [comment]
The title and description are neither constructive nor useful. We can handle the issue after getting more detailed description of the issue.

**Comment by barontxu** [comment]
@muraziz sorry for the short description.I'll make it more clear.
