### ISSUE TITLE
Lots of meaningless href in http://fblitho.com

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#149]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
In http://fblitho.com there're some href direct user into unexpected page.
For example, in http://fblitho.com/docs/inc-mount, when you click  "incremental mount", it shows the homepage.And there's some more, hope you take sometime to take a examination through the website.

## Expected Behavior
Show a page explain what is  incremental mount.

**Comment by passy** [comment]
The incremental mount link is a good find. You say "lots of", do you have other examples? I can assure you that we have spent a lot of time writing those docs, and we appreciate feedback on how to improve it.

**Comment by IanChilds** [comment]
A lot of these are fixed in pending pull requests from @jimfb. Unfortunately, he's having some trouble with signing the CLA so we're still having to wait for that to get sorted out.

**Comment by IanChilds** [comment]
e.g. https://github.com/facebook/litho/pull/123

**Comment by barontxu** [comment]
I feel like facing more than 3 this kind of href while i reading the tutorial.I will keep reporting bugs if i find more.

**Comment by barontxu** [comment]
In http://fblitho.com/docs/inc-mount-architecture, the href from "Layout off the main thread" missing.

**Comment by passy** [comment]
@barontxu "Jank" is a fairly commonly used term in UI. If you google for it, try to add "60fps" or "UI" and you'll find some great article, e.g. https://addyosmani.com/blog/making-a-site-jank-free/

**Comment by barontxu** [comment]
@passy Thank you for explain. I use a dictionary instead , so i got nothing, I'll try google first next time.
