### ISSUE TITLE
Codes in http://fblitho.com/docs/best-practices not work

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#150]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
follow the only piece of code inhttp://fblitho.com/docs/best-practices.TYPE it in android studio(you'll find there's no such method in image) or some place and build a project.

## Expected Behavior
Success.

## Link to Code
@LayoutSpec
class MyComponentSpec {

  @OnCreateLayout
  static ComponentLayout onCreateLayout(
      ComponentContext c,
      @Prop(resType = STRING) String title,
      @Prop(optional = true) Drawable image) {

  return Row.create(c)
      .alignItems(CENTER)
      .paddingRes(R.dimen.some_dimen)
      .child(
          Image.create(c)
              .src(image)
              .withLayout()
              .width(40)
              .height(40)
              .marginRes(RIGHT, R.dimen.my_margin))
      .child(TextUtils.isEmpty(title) ? null :
          Text.create(c)
              .text(title)
              .textColorAttr(R.attr.textColorTertiary)
              .withLayout()
              .marginDip(5)
              .flexGrow(1f))
      .build();
  }
}

**Comment by passy** [comment]
@barontxu Could you please provide the full error message you see when trying to compile the example code?

**Comment by pavlospt** [comment]
@barontxu Have you added the needed `annotationProcessor` dependency ?

**Comment by IanChilds** [comment]
We just need to change `.src` to `.drawable`, I believe? Is there anything else wrong?

**Comment by barontxu** [comment]
I think Ian is right, the api has changed.

**Comment by IanChilds** [comment]
Fix for this is incoming.
