### ISSUE TITLE
ClassCastException during annotation processing, triggered by package-level annotations

### ISSUE THREAD

**Issue by brian98point6** [facebook/litho#151]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
At build time annotation processing, the Litho AbstractComponentsProcessor runs into a ClassCastException. Here is a partial stack trace:
```
java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$PackageSymbol cannot be cast to javax.lang.model.element.TypeElement
    at com.facebook.litho.specmodels.processor.AbstractComponentsProcessor.process(AbstractComponentsProcessor.java:48)
```
Here is the relevant line of code:
https://github.com/facebook/litho/blob/cbbd4e26129e45ab6e43bb70473a2f8a65d600c3/litho-processor/src/main/java/com/facebook/litho/specmodels/processor/AbstractComponentsProcessor.java#L48

This is triggered by the package-level annotation `@Gson.TypeAdapters` we are using from the Immutables library:
https://immutables.github.io/json.html#generating-type-adapters

It looks like AbstractComponentsProcessor makes an assumption that the annotation is for a class or interface, but the case we're using the package-level annotation, it's a fragile assumption.

Repro steps:
1. Bring in the immutables gson library, i.e. `provided 'org.immutables:gson:2.4.6'`
2. Create a Litho spec. The `@LayoutSpec` annotation is sufficient.
3. Add the `@Gson.TypeAdapters` annotation in a new package-info.java file, e.g.:
```java
@Gson.TypeAdapters
package com.your.package.name;

import org.immutables.gson.Gson;
```
4. Attempt to build with the litho-processor, i.e. with `annotationProcessor 'com.facebook.litho:litho-processor:0.2.0'`

## Expected Behavior
I expect `AbstractComponentsProcessor` to not process the annotation if the `element` is not an instance of `TypeElement`, allowing apps which use package-level annotations to succeed.

## Link to Code
(I can work on a minimal app if the above repro steps are insufficient.)

**Comment by passy** [comment]
Oh that's an interesting one. Thanks for reporting!

/cc @IanChilds

**Comment by pavlospt** [comment]
One thought on this is that it could create a List of Elements from RoundEnvironment by combining the results of: 

```java
roundEnv.getElementsAnnotatedWith(LayoutSpec.class)
roundEnv.getElementsAnnotatedWith(MountSpec.class)
```

instead of getting the root elements, since it seems that you are only taking care of those 2 annotations :)

**Comment by pavlospt** [comment]
```java
Set<Element> layoutSpecElements =
        (Set<Element>) roundEnv.getElementsAnnotatedWith(LayoutSpec.class);
Set<Element> mountSpecElements =
        (Set<Element>) roundEnv.getElementsAnnotatedWith(MountSpec.class);

Set<Element> allSpecElements = new HashSet<>();
allSpecElements.addAll(layoutSpecElements);
allSpecElements.addAll(mountSpecElements);

for (Element element : allSpecElements) {
...
}
```

Seems to be working fine with the current implementation. I also run the sample with a `package-info.java` file and an annotated package entry. Let me know if you need a PR for this.
