### ISSUE TITLE
How to support Drag/Drop of items?

### ISSUE THREAD

**Issue by byronanderson** [facebook/litho#152]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

I know this doesn't fit into the guidelines for an *issue* but I didn't see a message board for generic questions.  Feel free to close given this breach of etiquette.

I'm having difficulty integrating this into a list where we want to support drag/drop interaction ->

As an example:  A long press of one item in the list should 'pick it up' visually and then I can scroll around the list to find a destination.

I see touch events and click/longclick events exposed, but I don't know how to stop the list view from scrolling.

Furthermore, I could not see how to scroll when a 'picked up' item reaches the top or bottom of a list.

Any help would be appreciated!  

--Byron

P.S. I love the idea behind this library, thanks FB OSS contributors!

**Comment by lucasr** [comment]
cc @pasqualeanatriello

**Comment by newfivefour** [comment]
I'd like something similar.

Specifically, I want to fire an event on dragging downwards on a component.

I can currently react when there's a short press and a long press. But nothing else.

Is it possible to expose the inner Android event? That way I could analyse the Android event for downward dragging and then fire a Litho event.

Am I missing something?

**Comment by newfivefour** [comment]
Here's the code to put in `onTouch` above to allow dragging. There's no drop area support in the code sample but it should be easy to implement.
```
        if (motionEvent.getAction() == MotionEvent.ACTION_DOWN) {
            ClipData data = ClipData.newPlainText("", "");
            View.DragShadowBuilder shadowBuilder = new View.DragShadowBuilder(
                    view);
            view.startDrag(data, shadowBuilder, view, 0);
            return true;
        } else {
            return false;
        }
```

**Comment by pasqualeanatriello** [comment]
The solution proposed by @newfivefour using DragShadowBuilder should work here :)
