### ISSUE TITLE
Optimized component lifecycle builders for Kotlin

### ISSUE THREAD

**Issue by ubuntudroid** [facebook/litho#153]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

I've played around a bit with Litho in conjunction with Kotlin: https://github.com/ubuntudroid/litho-kotlin

In a follow-up discussion with @lucasr on twitter we discovered, that a kotlin-litho-processor (used as a dependency instead of the already existing litho-processor) could help making the component lifecycle builders generated from specs more [Kotlin-friendly](http://stackoverflow.com/a/36150989/304266).

According to @lucasr litho's annotation processor is flexible enough for this use case, however keeping the generators in sync could be a problem. Adding to that there currently seem to be no stable Kotlin code generator out there. The only [promising one](https://github.com/jonnyzzz/kotlin.generator) I found is still kind of pre-alpha and the project seems to be hibernating.

**Comment by pavlospt** [comment]
https://medium.com/square-corner-blog/generating-kotlin-code-with-kotlinpoet-119dc20f74d4 Seems like now there is a tool :)

**Comment by ubuntudroid** [comment]
JIT :)

Pavlos-Petros Tournaris <notifications@github.com> schrieb am Di., 16. Mai
2017, 18:54:
