### ISSUE TITLE
`imeOptions` is missing from `EditTextSpec`

### ISSUE THREAD

**Issue by code-mc** [facebook/litho#155]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
The litho API currently does not support setting the input type on an EditText widget, this is a rather important feature. Android supports following input types https://developer.android.com/reference/android/text/InputType.html

Also, `imeOptions` is unsupported. This is used to set the action connected to the "enter" button on the keyboard. It's very important when designing a screen with multilple EditText fields. See https://developer.android.com/reference/android/view/inputmethod/EditorInfo.html

## Expected Behavior
N/A

## Link to Code
N/A

**Comment by pavlospt** [comment]
`InputType` seems to be supported judging by the latest `EditTextSpec` on `master` https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/EditTextSpec.java

**Comment by muraziz** [comment]
@pavlospt correct, it has been added very recently. Now we support `inputType` in `EditTextSpec`

**Comment by shrisukhani** [comment]
It seems imeOptions is also supported in `EditTextSpec` [now](https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/EditTextSpec.java#L296) Should we close this issue? :)

Please correct me if I'm wrong! :)

**Comment by passy** [comment]
Thanks, @shrisukhani!
