### ISSUE TITLE
How to request a redraw on prop/state update?

### ISSUE THREAD

**Issue by newfivefour** [facebook/litho#156]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce

Give a component a prop which is created from a singleton object.

I.e. `MyComponent.create(c).athing(MyData.instance()).build()`

Which is then used to display some text, 

```
    @OnCreateLayout
    static ComponentLayout onCreateLayout(
            ComponentContext c,
            @Prop MyData athing) {
        return Column.create(c)
                .child(create(c)
                        .text(athing.something)
               ...
```

And then in an onClick method update the singleton i.e:

`MyData.instance().something = "NEW THING!";`

## Expected Behavior

The component should update the text with `NEW THING`.

How can I update a prop  - or whatever - which is passed to a component and have the component update? Or simple request a redraw of the component?

[Edit] Reading about it some more, the whole component must be recreated. This is fine. But in hierarchical components - say parent component and then a edit text component within it - how can I tell the parent from within the child to recreate itself? An event?

**Comment by newfivefour** [comment]
I now understand I must use an event.

I have done this. The child component calls an event which is handle in the parent component.

But, now my global state object (given to the child components as props) has changed, how do I request a component update?

**Comment by newfivefour** [comment]
I've read this on react: https://stackoverflow.com/questions/30626030/can-you-force-a-react-component-to-rerender-without-calling-setstate/35004739#35004739 

Specifically

> By default, when your component's state or props change, your component will re-render. However, if these change implicitly (eg: data deep within an object changes without changing the object itself) or if your render() method depends on some other data, you can tell React that it needs to re-run render() by calling forceUpdate().

So in this case I made a component take a string as a prop. Then in the event handler, I change the string object. So:

```
@LayoutSpec
public class MyComponentHolderSpec {

    private static String thing = "SOMETHING OLD";

    @OnCreateLayout
    static ComponentLayout onCreateLayout(
            ComponentContext c) {
        return Column.create(c)
                .child(MyComponent.create(c)
                        .athing(thing)
                        .refreshAllHandler(MyComponentHolder.onRefreshAll(c))
                        .build())
                .build();
    }

    @OnEvent(RefreshAllEvent.class)
    static void onRefreshAll(
            ComponentContext c) {
        Log.d("MyComponent", "Refresh event called ");
        thing = "SOMETHING NEW";
    }
}
```

It renders "SOMETHING OLD" first. And then I can see `onRefreshAll` is invoked. And I'm changing the string prop that's passed to `MyComponent`.

But `MyComponent` is not re-rendered. Whereas in the above description it says `By default, when your component's state or props change, your component will re-render.`.

What am I missing?

**Comment by newfivefour** [comment]
Oh, in the event handler, you do this:

```
        c.updateState(new ComponentLifecycle.StateUpdate() {
            @Override
            public void updateState(ComponentLifecycle.StateContainer stateContainer, Component component) {
            }
        });
```

Can we put this in the documentation somewhere? It's taken me about a day to figure it out.

**Comment by passy** [comment]
Hi @newfivefour,

thanks for pointing out some issues with the documentation. That first example is generally *not* how Litho is supposed to be used at all. One of the main tenets of Litho is the use of immutable data structures. Explicit mutation is something that's highly discouraged for all the well-documented reasons against mutable state. Instead, you create a new Component and let the framework figure out how to apply the difference in the most performant way for you.

If you need to keep state contained to your component, you should look at [State](http://fblitho.com/docs/state#initializing-a-state-value).

I think your initial question is very valid. We don't cover the standard case of how to react to events and updating components well at the moment. I'll open a new issue for that.

Perhaps @mihaelao can shine some light on your approach to the state update, too.

**Comment by mihaelao** [comment]
Hi @newfivefour , thanks for bringing this up. I'll work on adding a concrete example on how to update the components in the tutorial. 

In the meantime, regarding your question around these instructions: "If the props values must be updated, the parent has to create a new Component and pass down new values for the props". Whenever you want to change the props for one of your components in your hierarchy, you need to create a new component using the new value of the prop and pass it as the new root for your `LithoView` using the [setComponent](http://fblitho.com/javadoc/com/facebook/litho/LithoView.html#setComponent-com.facebook.litho.Component-) method. The data flow model in Litho is top-down, meaning that whenever something has to change in a component, it's the parent that is responsible for passing down that data to the children, and the only way to re-render the hierarchy is by setting a new root for the tree.

If a component needs to keep track of an internal value that the parent doesn't need to know about (for example the selected/unselected state of a toggle button), then you can use [state updates](http://fblitho.com/docs/state) to manage this value locally to the component. Each state update would trigger a new re-layout of the component tree.  

Hope that helps, let me know if this is still unclear.

**Comment by mihaelao** [comment]
Closing as @passy opened #164 for writing a tutorial on this.

**Comment by newfivefour** [comment]
@passy  @mihaelao  I'm using what I think is the flux, or at least elm, system. Model -> View -> Update

I have a global immutable model (not component specific state). The whole app is rendered from this model. 

Then components throw events when a button is clicked, text is entered etc. Those events call an update method that creates a new model from the old model. 

At that point I want to tell the root component to update itself and its children and we now have new model.

How would this be possible? Make the `update` event handler have a reference to the activity, and thereby the `LithoView` and then again call `Updater.create(c).build()`

**Comment by samueljseay** [comment]
@newfivefour Did you ever figure this stuff out in a nice way? the state stuff is clear enough but doing a flux-like model update is not clear to me.
