### ISSUE TITLE
litho-widget has a runtime dependency on fresco

### ISSUE THREAD

**Issue by adelnizamutdinov** [facebook/litho#158]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
litho-widget has a runtime dependency on fresco, although it seems like it's litho-fresco's responsibility

## Expected Behavior
litho-widget does not depend on fresco

## Link to Code
https://github.com/facebook/litho/blob/master/litho-widget/build.gradle#L51

**Comment by IanChilds** [comment]
This is a good point - a legacy issue. Will fix this up.

**Comment by passy** [comment]
Fixed with 496f4e4eb3aaad5356925dd5f8eb9ca0d06c619c.
