### ISSUE TITLE
Add basic documentation for animating components

### ISSUE THREAD

**Issue by newfivefour** [facebook/litho#160]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

There are animation classes in https://github.com/facebook/litho/tree/master/litho-core/src/main/java/com/facebook/litho/animation.

However, there's no documentation on how to use them. And my very brief research into react animations isn't helping.

Can we add some very basic documentation on how to use these classes?

**Comment by newfivefour** [comment]
Or just post some sample code here?

Then I'll make a blog post explaining it and giving the caveat that it's not documented and things may change?

**Comment by passy** [comment]
Animation is still very much in flux and unstable right now, as I understand it. Once we're happy with the API, we will definitely spend the effort on providing examples and docs.

Perhaps @marco-cova can provide some info here.

**Comment by astreet** [comment]
Yeah, these APIs aren't ready for production yet, we're still working on them. Once they're more solidified and tested we'll write up some documentation :)

**Comment by passy** [comment]
Thanks! I'll close this for now.
