### ISSUE TITLE
Can't figure out what is convertDrawable in http://fblitho.com/docs/mount-specs

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#162]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
read code below line "Let’s have a look at ColorComponent with the described @OnPrepare method.
" in http://fblitho.com/docs/mount-specs.

In code piece:
  @OnMount
  static void onMount(
      ComponentContext context,
      ColorDrawable colorDrawable,
      @FromPrepare int color) {
    convertDrawable.setColor(color);
  }
there's a convertDrawable which only shows once in this passage,  is it a out put from previous scene which you didin't mention? or just spelling error?

**Comment by IanChilds** [comment]
It's a spelling error. I will send a fix.
