### ISSUE TITLE
What does canMountIncrementally and PTRRefreshEvent means?

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#163]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
In source code of RecyclerSpec I came over this piece:
_@MountSpec(canMountIncrementally = true, isPureRender = true, events = {PTRRefreshEvent.class})_
I search the docs for the annotations but it shows its a value of canMountIncrementally() and tells me "Whether this ComponentLifecycle mounts views that contain component-based content that can be incrementally mounted e.g. if the mounted view has a LithoView with incremental mount enabled.
" or "Whether this mount spec supports incremental mount."But still I find it  hard to understand.
So If you got some time could you plz show me what does canMountIncrementally and PTRRefreshEvent mean? Thank you.

**Comment by barontxu** [comment]
Does it means using image or text or some small unit instead of using a whole view class to present recycler?

**Comment by passy** [comment]
@barontxu The concept of incremental mount is explained here: http://fblitho.com/docs/inc-mount-architecture

PTR stands for Pull To Refresh. We should probably have a docstring explaining that. I'll add that today.

**Comment by barontxu** [comment]
@passy Thank you!

**Comment by barontxu** [comment]
@passy By the way, a href in http://fblitho.com/docs/inc-mount-architecture is missing, one of the flaws I should report in https://github.com/facebook/litho/issues/149. I'll add it to that issue.

**Comment by sushshring** [comment]
For a Recycler object, what how exactly do we trigger the event handler to hide the refresh animation?
