### ISSUE TITLE
Maybe a bug in http://fblitho.com/docs/state#calling-state-updates

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#166]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
In the piece of code in http://fblitho.com/docs/state#calling-state-updates,
 @OnUpdateState
  void updateCheckbox(StateValue<Boolean> isChecked) {
    isChecked.set(!isChecked.get());
  }
is void, but I thought other method in spec is static, so the function can not work with others.
Be more clear, I wrote a sample project use the code, it fails when build, and tells me the method should be static.
So maybe it's a mistake.

**Comment by passy** [comment]
Thanks!
