### ISSUE TITLE
At least one error in http://fblitho.com/docs/events-overview

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#169]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
In every piece of code in http://fblitho.com/docs/events-overview, there's 

 static ComponentLayout onCreateLayout(
      Context c,

and 

 @OnCreateLayout
  static ComponentLayout onCreateLayout(
      LayoutContext c,

but  LayoutContext not even exist in API, maybe it should be ComponentContext.
And if possible, could you plz provide a sample project of this function?I have trouble binding events, and I think there's more bugs in this page but I can't find them all.A sample project can help both you and the reader a lot. Thank you!

## Link to Code
http://fblitho.com/docs/events-overview#callbacks

**Comment by barontxu** [comment]
By "I have trouble binding events", I mean, for example, how can I dispatch a CLICK event by dispatchClickEvent? I have no idea how to get access to view.Or why there's a 
@FromPrepare int color
from the second piece of code, I know what FromPrepare means, but where is it define or how should I implement a FromPrepare?

**Comment by mihaelao** [comment]
Hi @barontxu , thanks for pointing out these issues, we need to fix this in the docs. In the meantime you can find an example of how to create and pass down click handlers in [DemoListItemComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/DemoListItemComponentSpec.java) in the [sample](https://github.com/facebook/litho/tree/master/sample/src/main/java/com/facebook/samples) app.

**Comment by barontxu** [comment]
hello @mihaelao ,thanks for answering the question.But that's not the answer I'm looking for, of course I know how to simply bind onClick.What I'm asking is more complicated.
And it's my fault not explaining the problem correctly.
I mean i want to bind click event out of spec(int runtime or in parent of the spec), and bind click event to recycler.

By " how can I dispatch a CLICK event by dispatchClickEvent?", I mean in http://fblitho.com/docs/events-overview
there's this piece of code

@LayoutSpec(events = { ColorChangedEvent.class })
class ColorComponentSpec {
  ...
  @OnCreateLayout
  static ComponentLayout onCreateLayout(
      Context c,
      @Prop EventHandler colorChangedHandler,
      @FromPrepare int color) {
    ...
    ColorComponent.dispatchColorChangedEvent(
        colorChangedHandler,
        color);
    ...
  }
}

you can see there's a 
 ColorComponent.dispatchColorChangedEvent(
        colorChangedHandler,
        color);
so I wonder if I need to dispatchClickEvent if I want to bind onClick out of the spec. If I do, I need to get view, which is nearly impossible.

All I want to do is to add clickevent to a recycler.
what's more, read https://github.com/facebook/litho/issues/173.
I've been trapped in this problem for several days, I'll appreciate very holy much if you can help.
