### ISSUE TITLE
recycler's bug that can't add onClick for it as tutorial do for text component

### ISSUE THREAD

**Issue by barontxu** [facebook/litho#173]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
I tried to add an onClick() for recycler as first piece of code in http://fblitho.com/docs/events-touch-handling do.At first I add onClick for a text, it worked.Then I replace the text by a recycler, but it seems the binding failed.

## Expected Behavior
Output log in onClick().

## Link to Code
https://github.com/barontxu/lithoflow_cant_add_onClick_error/blob/master/app/src/main/java/com/example/tanisxu/lithotest/components/TrainExpandCardFlowSpec.java
line 58--64.

**Comment by passy** [comment]
Just for clarification, do you want the click handler to be called when you tap the RecyclerView or do you want to have individual items in the recycler to respond to them?

**Comment by barontxu** [comment]
@passy thank you first!!
I think the handler to be called when I tap the RecyclerView is fine.And if possible I want every individual items in the recycler to respond when click at them.

**Comment by passy** [comment]
I don't think clicks on the recycler are supported as it's expected to forward events to its children. The `RecyclerBinder` is more than just a wrapper around `RecyclerView` (hence the different name) and doesn't expose the underlying mounted view with all its regular functionality.

**Comment by barontxu** [comment]
@passy Get it. So is there any way I can make the component in recycler to answer my click and change some variable or state in recycler?

**Comment by barontxu** [comment]
I doesn't mean implement onClick in the component's spec, but add onClick when components are added to recycler.

**Comment by barontxu** [comment]
Should I take the silence as a "you can only set one's click handler in its spec"?
