### ISSUE TITLE
JNI WARNING: JNI method called with exception pending

### ISSUE THREAD

**Issue by dynsxyc** [facebook/litho#177]
- [1 ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***
通过运行gradlew :sample:installDebug 安装sample测试demo，应用已安装成功，但是无法运行，点击demo Icon 出错
05-08 10:46:43.813 20299-20299/com.facebook.samples.litho D/dalvikvm: Added shared lib /data/app-lib/com.facebook.samples.litho-1/libfb.so 0x427faff0
05-08 10:46:43.813 20299-20299/com.facebook.samples.litho W/dalvikvm: JNI WARNING: JNI method called with exception pending
05-08 10:46:43.813 20299-20299/com.facebook.samples.litho W/dalvikvm:              in Ljava/lang/Runtime;.nativeLoad:(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/lang/String; (GetFieldID)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho W/dalvikvm: Pending exception is:
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm: java.lang.NoClassDefFoundError: com/facebook/jni/Countable
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.Runtime.nativeLoad(Native Method)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.Runtime.load(Runtime.java:338)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.System.load(System.java:521)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:279)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:69)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:63)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:367)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:332)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.yoga.YogaConfig.<clinit>(YogaConfig.java:19)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentsPools.acquireYogaNode(ComponentsPools.java:171)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentsPools.acquireInternalNode(ComponentsPools.java:196)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:250)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Column.create(Column.java:25)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Column.create(Column.java:29)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.onCreateLayout(ComponentLifecycle.java:320)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:225)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:261)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Layout.create(Layout.java:40)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Component$Builder.withLayout(Component.java:113)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.samples.litho.DemoListComponentSpec.onCreateLayout(DemoListComponentSpec.java:41)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.samples.litho.DemoListComponent.onCreateLayout(DemoListComponent.java:29)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:225)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LayoutState.createTree(LayoutState.java:1165)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1334)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LayoutState.calculate(LayoutState.java:915)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1226)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentTree.measure(ComponentTree.java:537)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LithoView.onMeasure(LithoView.java:205)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2256)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1922)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1106)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1313)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1006)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4712)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer.doFrame(Choreographer.java:532)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.os.Handler.handleCallback(Handler.java:725)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:92)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.os.Looper.loop(Looper.java:137)
05-08 10:46:43.823 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5154)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:511)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:569)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm: Caused by:
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm: java.lang.ClassNotFoundException: Didn't find class "com.facebook.jni.Countable" on path: /data/app/com.facebook.samples.litho-1.apk
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.Runtime.nativeLoad(Native Method)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.Runtime.load(Runtime.java:338)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.System.load(System.java:521)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader$1.load(SoLoader.java:279)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:69)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:63)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.DirectorySoSource.loadLibrary(DirectorySoSource.java:40)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:427)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:367)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:332)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.yoga.YogaConfig.<clinit>(YogaConfig.java:19)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentsPools.acquireYogaNode(ComponentsPools.java:171)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentsPools.acquireInternalNode(ComponentsPools.java:196)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:250)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Column.create(Column.java:25)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Column.create(Column.java:29)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.onCreateLayout(ComponentLifecycle.java:320)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:225)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentContext.newLayoutBuilder(ComponentContext.java:261)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Layout.create(Layout.java:40)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.Component$Builder.withLayout(Component.java:113)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.samples.litho.DemoListComponentSpec.onCreateLayout(DemoListComponentSpec.java:41)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.samples.litho.DemoListComponent.onCreateLayout(DemoListComponent.java:29)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentLifecycle.createLayout(ComponentLifecycle.java:225)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LayoutState.createTree(LayoutState.java:1165)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LayoutState.createAndMeasureTreeForComponent(LayoutState.java:1334)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LayoutState.calculate(LayoutState.java:915)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentTree.calculateLayoutState(ComponentTree.java:1226)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.ComponentTree.measure(ComponentTree.java:537)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.facebook.litho.LithoView.onMeasure(LithoView.java:205)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.support.v7.widget.ActionBarOverlayLayout.onMeasure(ActionBarOverlayLayout.java:393)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1404)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.LinearLayout.measureVertical(LinearLayout.java:695)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.LinearLayout.onMeasure(LinearLayout.java:588)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:4948)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.widget.FrameLayout.onMeasure(FrameLayout.java:310)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2256)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.View.measure(View.java:15544)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:1922)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1106)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1313)
05-08 10:46:43.833 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1006)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4712)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer.doCallbacks(Choreographer.java:562)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer.doFrame(Choreographer.java:532)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.os.Handler.handleCallback(Handler.java:725)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.os.Handler.dispatchMessage(Handler.java:92)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.os.Looper.loop(Looper.java:137)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at android.app.ActivityThread.main(ActivityThread.java:5154)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.reflect.Method.invokeNative(Native Method)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at java.lang.reflect.Method.invoke(Method.java:511)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:802)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:569)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm:     at dalvik.system.NativeStart.main(Native Method)
05-08 10:46:43.843 20299-20299/com.facebook.samples.litho I/dalvikvm: "main" prio=5 tid=1 NATIVE
## Expected Behavior
***Describe what you expected would happen.***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by passy** [comment]
Apologies, but this is not enough for us to reproduce the error. Please reopen a bug report with more information about potential changes you've made, the version of the repo and platform you're on. Thank you!
