### ISSUE TITLE
RecyclerBinderUpdateCallback not work as expected.

### ISSUE THREAD

**Issue by talenguyen** [facebook/litho#181]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
I'd like to bind my Recycler by using `DiffUtil` and `RecyclerBinderUpdateCallback` this way: 

Define a custome component called `PlaygroundComponentSpec` and it will display a list:

```java
[PlaygroundComponentSpec.java]
@LayoutSpec
public class PlaygroundComponentSpec {

  @OnCreateLayout
  static ComponentLayout onCreateLayout(
      ComponentContext c) {

    final RecyclerBinder recyclerBinder = new RecyclerBinder(
        c,
        4.0f,
        new LinearLayoutInfo(c, OrientationHelper.VERTICAL, false));

    addDataToBinder(recyclerBinder, c);

    return Column.create(c)
        .backgroundColor(Color.WHITE)
        .child(
            Recycler.create(c)
                .binder(recyclerBinder)
                .build())
        .build();
  }
  ...
}
```

Then populate the binder with list items:

```java
[PlaygroundComponentSpec.java]
private static void addDataToBinder(RecyclerBinder recyclerBinder, final ComponentContext c) {

  final List<String> items = Arrays.asList(
      "Item 1",
      "Item 2",
      "Item 3");

  final DiffUtil.DiffResult diffResult = DiffUtil.calculateDiff(new DiffUtil.Callback() {
    @Override public int getOldListSize() {
      return 0;
    }

    @Override public int getNewListSize() {
      return items.size();
    }

    @Override public boolean areItemsTheSame(int oldItemPosition, int newItemPosition) {
      return false;
    }

    @Override public boolean areContentsTheSame(int oldItemPosition, int newItemPosition) {
      return false;
    }
  });

  final RecyclerBinderUpdateCallback<String> updateCallback = RecyclerBinderUpdateCallback.acquire(
      0,
      items,
      new RecyclerBinderUpdateCallback.ComponentRenderer<String>() {
        @Override public ComponentInfo render(String item, int idx) {
          return ComponentInfo.create()
              .component(
                  Text.create(c)
                      .textSizeSp(20)
                      .text(item)
                      .build())
              .build();
        }
      },
      recyclerBinder);

  diffResult.dispatchUpdatesTo(updateCallback);
}
```

## Expected Behavior
Recycler should display a list of 3 Texts view.

## Link to Code
https://gist.github.com/talenguyen/19f57d709727257189491447fc87c61a

**Comment by lucasr** [comment]
cc @pasqualeanatriello

**Comment by pasqualeanatriello** [comment]
Really sorry for the late reply but I've been out of the office.
The problem here is probably that you are allocating the RecyclerBinder inside onCreateLayout.
I would suggest keeping it in your Fragment and pass it down as prop. Also you want to invoke addDataToBinder from your fragment. onCreateLayout will run every time the system needs to compute a new layout.

**Comment by talenguyen** [comment]
Thank you for your reveal of "onCreateLayout will run every time the system needs to compute a new layout". But the code is only for demo purpose. After I take a deeper look at source code of the `RecyclerBinderUpdateCallback.java` I figured out that there is a method `applyChangeset()` and it must be called right after `diffResult.dispatchUpdatesTo(updateCallback)` like below:

```java
  diffResult.dispatchUpdatesTo(updateCallback);
  updateCallback.applyChangeset();
```

It's a little bit strange but it worked.
