### ISSUE TITLE
error: Event fields must be declared as public non-final.

### ISSUE THREAD

**Issue by R4md4c** [facebook/litho#182]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
I'm trying to write a custom Event in my application, that includes `@IntDef` annotation, and contains `public final static int` fields.
I'm getting an error from the annotations processor that says 
`Error:(19, 9) error: Event fields must be declared as public non-final.`

## Expected Behavior
I would expect that the annoation processor skips static fields, and the build succeeds with no problem.

## Link to Code
Here is a sample code.
```
@Event
public class VoteEvent {
    public final static int VOTE_DIRECTION_UP = 1;
    public final static int VOTE_DIRECTION_DOWN = 2;

    @IntDef({VOTE_DIRECTION_UP, VOTE_DIRECTION_DOWN})
    @interface VoteDirection {}


    public @VoteDirection int voteDirection;
}

```
If you confirmed this as an issue, I'd be glad to submit a PR.

**Comment by IanChilds** [comment]
Hi @R4md4c, yes you are right, I think your proposal makes sense. If you could submit a PR that would be really great! I think that we should allow either `public non-static non-final` or `public static final`, do you agree?

**Comment by R4md4c** [comment]
IMHO, I think if we allowed `public non-static non-final` then the code above won't work, because `IntDef` annotation expects a constant static field. So I'd say I would go for allowing just `public static final`, and disallow `non-static final` variables.

**Comment by R4md4c** [comment]
I think I misunderstood your statement, sorry about that, Yeah I agree with allowing just `public non-static non-final` and `public static final`.
