### ISSUE TITLE
SoLoader dependency version problem in Getting Started page

### ISSUE THREAD

**Issue by karuppiah7890** [facebook/litho#183]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
Simply follow the [getting started guide](http://fblitho.com/docs/getting-started) and add the dependencies. And build with gradle.

## Expected Behavior
Gradle should build with all dependencies without errors. But it says it's not able to resolve soloader dependency

```gradle
compile 'com.facebook.soloader:soloader:0.2.1'
```

Then I used "0.1.0+" version as mentioned in soloader repo README, like this : 

```gradle
compile 'com.facebook.soloader:soloader:0.1.0+'
```
and it worked. I tried "0.2.0" version too, and it worked! I guess "0.2.1" version is not yet uploaded to the jCenter repository ?

## Link to Code

No code. Only build.gradle file and I had some issues with test app and : 

```gradle
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.3"
    defaultConfig {
        applicationId "me.karuppiah7890.lithodemo"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'

    // ...
    // Litho
    compile 'com.facebook.litho:litho-core:0.2.1'
    compile 'com.facebook.litho:litho-widget:0.2.1'
    provided 'com.facebook.litho:litho-annotations:0.2.1'

    annotationProcessor 'com.facebook.litho:litho-processor:0.2.1'

    // SoLoader
    compile 'com.facebook.soloader:soloader:0.1.0+'

    // Optional
    // For debugging
    debugCompile 'com.facebook.litho:litho-stetho:0.2.1'

    // For integration with Fresco
    compile 'com.facebook.litho:litho-fresco:0.2.1'

    // For testing
    testCompile 'com.facebook.litho:litho-testing:0.2.1'
}

android {
    configurations.all {
        resolutionStrategy.force 'com.google.code.findbugs:jsr305:3.0.1'
    }
}
```

**Comment by pavlospt** [comment]
Yeap, as you can see here: http://jcenter.bintray.com/com/facebook/soloader/soloader/ only version 0.2.0 is uploaded, also there is no snapshot of 0.2.1 available on Sonatype Snapshots: https://oss.sonatype.org/content/repositories/snapshots/com/facebook/ .

**Comment by passy** [comment]
Woops, sorry that was my fault. The soloader version should be `0.2.0`. I accidentally replaced that during our Litho version update. It's completely independent from Litho and our release cycle. Doc fix is coming.
