### ISSUE TITLE
SoLoader lib version in "Getting Started" guide is wrong 

### ISSUE THREAD

**Issue by paveldudka** [facebook/litho#186]
"Getting started" section of Litho docs mentions `soloader` lib version 2.0.1. However it is not released yet - the latest version published on Maven is 2.0.0: https://mvnrepository.com/artifact/com.facebook.soloader/soloader
![screen shot 2017-05-16 at 9 41 39 am](https://cloud.githubusercontent.com/assets/3103759/26117608/efa15c74-3a1b-11e7-9293-9580c5536df0.png)

**Comment by pavlospt** [comment]
Yes, this is wrong and known issue. Will be fixed soon I think.

**Comment by pavlospt** [comment]
Yes, this is wrong and known issue. Will be fixed soon I think.

**Comment by passy** [comment]
Sorry, I fixed half of it before and didn't see that there were two references in this guide. Other half will be fixed in half an hour or so. :)
