### ISSUE TITLE
unable to use Typeface class to customize font through createFromAsset()

### ISSUE THREAD

**Issue by hussainahmad** [facebook/litho#189]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

## Expected Behavior
***Describe what you expected would happen.***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by lucasr** [comment]
Hi @hussainahmad, have you tried this?
```
Text.create(c)
    .text("Some text")
    .textColor(Color.RED)
    .typeface(Typeface.createFromAsset(c.getAssets(), "yourfont.ttf"))
    .build();
```

**Comment by hussainahmad** [comment]
Hi @lucasr thanks for early response, its really works, 
its my mistake , solved my problem 
again thanks 💯
