### ISSUE TITLE
can not resolve symbol 'LithoWebKitInspector'

### ISSUE THREAD

**Issue by hussainahmad** [facebook/litho#191]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
***Replaces this with steps to repro your issue.***

## Expected Behavior
***Describe what you expected would happen.***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by hussainahmad** [comment]
when i import `com.facebook.litho.stetho.LithoWebKitInspector;` giving error 
Gradle file `// Litho
    compile 'com.facebook.litho:litho-core:0.2.1'
    compile 'com.facebook.litho:litho-widget:0.2.1'
    compile 'com.facebook.litho:litho-annotations:0.2.1'
    annotationProcessor 'com.facebook.litho:litho-processor:0.2.1'
    // SoLoader
    compile 'com.facebook.soloader:soloader:0.2.0'
    // Optional
    // For debugging
    debugCompile 'com.facebook.litho:litho-stetho:0.2.1'
    // For integration with Fresco
    compile 'com.facebook.litho:litho-fresco:0.2.1'
    // For testing
    testCompile 'com.facebook.litho:litho-testing:0.2.1'`

**Comment by passy** [comment]
@hussainahmad How do you compile it? Is it possible you're compiling a release flavor and not a debug one?

**Comment by passy** [comment]
For future bug reports, it would really help us a lot if you could stick to the template we've created.

**Comment by hussainahmad** [comment]
i am compiling this code[https://github.com/facebook/litho/tree/master/sample](sample code)
that's why i didn't check this, just copy past code of your sample project

**Comment by passy** [comment]
@hussainahmad That's why I ask about the way you compiled it. If you build it in release mode, then the import won't be available. :)

**Comment by hussainahmad** [comment]
Really sorry for late response, @passy i am getting this error in debug mode not in release mode

**Comment by passy** [comment]
@hussainahmad Does that mean you're not getting the issue in release mode? Which version of the gradle plugin are you using? The semantics have changed with version 3.

**Comment by hussainahmad** [comment]
@passy yep, i am getting this error in debug mode,  gradle version is 3.3, android plugin version is 2.3.2 and build tool version is 25.0.3

**Comment by passy** [comment]
@hussainahmad If you change the dependency declaration from `debugCompile` to a regular `compile`, does that still cause issues?

**Comment by hussainahmad** [comment]
@passy still cause same issue in both declaration condition (debugCompile & compile)

**Comment by passy** [comment]
@hussainahmad Sorry, I'm not sure in that case. Would it be possible to create a repository so I can repro this myself?

**Comment by hussainahmad** [comment]
Sure, let me create

**Comment by hussainahmad** [comment]
Sure, let me create

**Comment by hussainahmad** [comment]
@passy [https://github.com/hussainahmad/LithoSample](sample code)

**Comment by passy** [comment]
@hussainahmad Changing the import from `com.facebook.litho.stetho.LithoWebKitInspector` to just `com.facebook.litho.LithoWebKitInspector` will fix your issue. I'm not entirely sure why the JARs ended up with that package, though.

Thanks for the report, I'll look into this!

**Comment by passy** [comment]
Oh, the answer is simple: The move to its own `.stetho` package is a fairly recent one and happened after the last release: https://github.com/facebook/litho/commit/cd55b73156b1c957487969a5fd1beeabcb6522a8

With the next release, the new import will work.
