### ISSUE TITLE
Spec Class Visibility not found

### ISSUE THREAD

**Issue by hussainahmad** [facebook/litho#195]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
***I don't found any method in Litho like 'ProgressBar.setVisibility(View.VISIBLE);' 
here 'ProgressBar' is generated class of  ProgressBarSpec. ***

## Expected Behavior
***Like in android View we  use setVisibility() for setting visibility according use case ***

**Comment by IanChilds** [comment]
In Litho, you don't dynamically set visibility. You just choose to include the `ProgressBar` or not when you layout your Component.
