### ISSUE TITLE
Nested Recycler

### ISSUE THREAD

**Issue by Martin-Hogge** [facebook/litho#197]
I try to use nested recycler because I have a layout that can be used alone or into a list but this layout can have more than > 10 rows with many views so I think it's better to set it up into a Recycler to take advantage of view's recycling, etc.

But when I try to nest Recycler, here's the error message I got:

> java.lang.IllegalStateException: Height mode has to be EXACTLY OR AT MOST for a vertical scrolling RecyclerView

Here is the code I'm using:

```
public class LithoActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        final ComponentContext context = new ComponentContext(this);

        final RecyclerBinder recyclerBinder = new RecyclerBinder(
                context,
                new LinearLayoutInfo(this, OrientationHelper.VERTICAL, false)
        );

        final Component component = Recycler.create(context)
                .binder(recyclerBinder)
                .nestedScrollingEnabled(true)
                .build();

        setContentView(LithoView.create(this, component));
        addContent(recyclerBinder, context);
    }

    private  void addContent(RecyclerBinder recyclerBinder, ComponentContext c) {
        Faker.with(this);

        for (int i = 0; i < 4 ; i++) {
            final RecyclerBinder subBinder = new RecyclerBinder(
                    c,
                    new LinearLayoutInfo(this, OrientationHelper.VERTICAL, false)
            );

            final Component subComponent = Recycler.create(c)
                    .binder(subBinder)
                    .build();

            for (int j = 0; j < 20; j++) {
                subBinder.insertItemAt(
                        j,
                        ComponentInfo.create()
                                .component(FormField.create(c)
                                        .text(Faker.Lorem.sentence())
                                        .dataType(DataType.STRING)
                                        .color(i % 2 == 0 ? Color.RED : Color.GREEN)
                                        .build())
                                .build());
                recyclerBinder.insertItemAt(i, subComponent);
            }
        }
    }
```

NB: this code is only to test nested recycler.

Thank you for further help !

**Comment by pasqualeanatriello** [comment]
hey Martin there are a couple of issues here. The first is that you are using vertical recyclers within a vertical recycler. This is not supported at the moment. You can simply add all the children to the same Recycler.
If what you wanted is to have horizontal recyclers within a vertical recycler instead, that's totally fine. The only thing that you have to take care of is either give a specific size to your horizontal recycler (create a LayoutSpec and assign a height value to your horizontal recycler), or pass the canMeasure prop as true.

**Comment by Martin-Hogge** [comment]
Will nested vertical Recycler will be possible in a future release or it isn't planned at all?

The reason why I wanted to have nested vertical Recycler is because I want to create dynamic forms, each forms could have different type of views (EditText, CheckBoxes, DatePicker, etc) but a form is not strictly defined, it is created dynamically depending on some data models. So forms could have 1 to many views, that's why I wanted to have one form wrapped inside a Recycler to handle forms with lot of views (>15 views for example). But a thing is that those forms could possibly be added to a list if the user has to fill multiple forms at once. That was the original reason why I wanted nested vertical Recycler. But I should consider not wrapping a form inside a Recycler and see what happens with huge forms. 

Thank you for the answer.

**Comment by pasqualeanatriello** [comment]
@Martin-Hogge how did that work for you? in general multiple Recyclers/Binders would not help with performances here as we already support mixing very different content in one Recycler in an efficient way. Please feel free to reopen the task if this  is still an issue for you

**Comment by Martin-Hogge** [comment]
I finally avoid the need of using nested Recyclers (which is, as you said, better regarding performances), thank's.

**Comment by didixyy** [comment]
> @ Martin-Hogge这对你有用吗？一般而言，多个回收商/粘合剂对这里的表现没有帮助，因为我们已经支持以一种有效的方式在一个Recycler中混合非常不同的内容。如果这仍然是一个问题，请随时重新打开任务

when i fist line use VERTICAL recycler and secord use  StaggeredGrid, StaggeredGrid all item heigh are difference ,I didn't seem to have a good idea after trying.
