### ISSUE TITLE
Add support for StaggeredGridLayoutManager

### ISSUE THREAD

**Issue by 9h0st** [facebook/litho#201]
It's easy to implement a LayoutInfo for StaggeredGridLayoutManager, but it's hard to change item's layoutparams to setFullspan.
It will be appreciated to add support for StaggeredGridLayoutManager.

**Comment by lucasr** [comment]
@pasqualeanatriello Any thoughts here?

**Comment by pasqualeanatriello** [comment]
The idea here would probably be to pass custom attributes through the ComponentInfo. I believe we do something similar to support span count for the GridLayoutInfo

**Comment by 9h0st** [comment]
@pasqualeanatriello What do you mean? GridLayoutInfo does have spanSizeLookUp to change span, but it doesn't support StaggeredGridLayoutManager.

**Comment by pasqualeanatriello** [comment]
@9h0st  sorry for the super late reply on this. I'm not sure what the problem here is. Is there anything that makes it hard to implement a StaggeredGridLayoutInfo?

**Comment by mihaelao** [comment]
StaggeredGridLayoutInfo was added in 1d7dadaa42e645a6f7c26a7ee3759d8ecfbaf91a, closing this
