### ISSUE TITLE
Better Documentation and Samples

### ISSUE THREAD

**Issue by Zeyad-37** [facebook/litho#202]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
I am trying to use Litho in my project but the documentation and samples don't really explain any advanced cases. Like how to handle the refresh handler and other

## Expected Behavior
Please make a more demonstrative sample with a full functionality. Like a recycler view with  infinite scrolling, toggles progress bars when loading and item selection.

**Comment by thatsVishal** [comment]
No documentation on how to use Images

**Comment by hussainahmad** [comment]
@thatsVishal you should read documentation thoroughly before saying this, please read how to use  `litho-fresco` for image integration

**Comment by hussainahmad** [comment]
@thatsVishal sorry dude if you mind this, BTW I am not arguing with you :)

**Comment by thatsVishal** [comment]
That's alright

**Comment by passy** [comment]
This is definitely good feedback. I agree that there should be more documentation on that topic. We've got fairly limited resources here for writing those docs so knowing what people need most can help us prioritize.

**Comment by Zeyad-37** [comment]
Come on guys play nice. All we want is better documentation/examples so we can use this amazing product

**Comment by mihaelao** [comment]
Closing this as we are working on adding docs and codelabs for the most common use cases
