### ISSUE TITLE
recyclerBinder.append()

### ISSUE THREAD

**Issue by Zeyad-37** [facebook/litho#203]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
Add an append function to add items to the list

## Expected Behavior
recyclerBinder.append(/*item(s) to added*/)

**Comment by passy** [comment]
@Zeyad-37 What would that add that the existing functions don't provide? E.g. `insertItemAt`, `updateItemAt` etc.?

**Comment by Zeyad-37** [comment]
That i dont need to manage the index

**Comment by passy** [comment]
I've now noticed this being quite inconvenient at times too. If someone wants to prepare a PR for this, I'm happy to review it. :)

**Comment by mihaelao** [comment]
closed in #236
