### ISSUE TITLE
Using Typeface with Text component is problematic

### ISSUE THREAD

**Issue by bgfb** [facebook/litho#204]
Typeface.create() accesses a static cache and is not thread-safe.  This can lead to race-conditions and problems if you call Typeface.create() during Text component layout creation or style resolution, which can happen on a background thread.

**Comment by pasqualeanatriello** [comment]
@IanChilds should have fixed this here https://github.com/facebook/litho/commit/ca96aba0fd81b4ca24203243bcc2894713307079.
Please reopen if this still reproduces for you.
