### ISSUE TITLE
RxJava/2 extension

### ISSUE THREAD

**Issue by Zeyad-37** [facebook/litho#205]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Feature Request
A RxJava/2 extension for Recycler events, something like RxBinding

## Expected Behavior
RxRecycler.scrollStateChanges(myRecycler).map(integer -> {/* handle scroll events here*/})
or
RxRecycler.endlessScrollListener(myRecycler).map(onLoad -> {/* handle onLoad events here*/})

**Comment by passy** [comment]
We don't use RxJava internally, but I think this would be great to have as a separate library. We'd definitely be happy to link to it. :)

**Comment by pasqualeanatriello** [comment]
I'd love to see something like that being worked on too. Unfortunately this won't be on our roadmap anytime soon. Let us know if you decide to work on this as I'd love to have a look at the code.
