### ISSUE TITLE
FrescoImage miss the uri() method

### ISSUE THREAD

**Issue by hanhailong** [facebook/litho#213]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
    
    // Litho
    compile 'com.facebook.litho:litho-core:0.3.1'
    compile 'com.facebook.litho:litho-widget:0.3.1'
    provided 'com.facebook.litho:litho-annotations:0.3.1'

    annotationProcessor 'com.facebook.litho:litho-processor:0.3.1'

    // SoLoader
    compile 'com.facebook.soloader:soloader:0.2.0'

    // For debugging
    debugCompile 'com.facebook.litho:litho-stetho:0.3.1'

    compile 'com.facebook.litho:litho-fresco:0.3.1'***

## Issues and Steps to Reproduce
***
![image](https://user-images.githubusercontent.com/4241807/28066439-7e9598da-666f-11e7-95fc-f2f03d4cd6e2.png)
***

## Expected Behavior
***FrescoImage should have uri() method***

**Comment by passy** [comment]
Where did you see that method call? I'm wondering if our docs are incorrect.

You can see the correct use in the example here:
https://github.com/facebook/litho/blob/94cb400c90fd4e09430c42584693b29725e2dd8c/sample/src/main/java/com/facebook/samples/litho/lithography/SingleImageComponentSpec.java#L32

You set the URI on the controller, not the component.
