### ISSUE TITLE
clipToPadding not working on Recycler

### ISSUE THREAD

**Issue by BartNijland91** [facebook/litho#219]
Steps to reproduce:

- Create Recycler
- Add some Cards as items
- Add padding to the recycler
- Set "clipToPadding = false" to Recycler
- Still clips padding?

**Comment by passy** [comment]
Maybe @muraziz knows something about this?

**Comment by pasqualeanatriello** [comment]
We are aware of this. We are working on a fix. Will keep you posted!

**Comment by amoikevin** [comment]
any updates on this issue?

**Comment by amoikevin** [comment]
+1
