### ISSUE TITLE
Crash cazu lack of so file in apk

### ISSUE THREAD

**Issue by barnett-yuxiang** [facebook/litho#221]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
***Add the version of the litho packages you use. You can paste the dependency
section of the gradle file if you have one.***
no, I follow buck, i like it.

## Issues and Steps to Reproduce
***Replace this with steps to repro your issue.***
$ buck fetch sample
$ buck install -r sample

use AS analyze apk, there is no libyoga.so .etc. I list gradle build as follow

![image](https://user-images.githubusercontent.com/12042337/29205525-154a9246-7eb0-11e7-8aaf-b816db2b43ff.png)

![image](https://user-images.githubusercontent.com/12042337/29205572-499c3450-7eb0-11e7-8398-0bcb1701b6fb.png)

Anything Wrong?

## Expected Behavior
***Describe what you expected would happen.***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by passy** [comment]
Not good! Thanks for the report. I can repro this locally. I'm looking into it.
