### ISSUE TITLE
Litho removes all my other native libraries with BUCK

### ISSUE THREAD

**Issue by jollycopper** [facebook/litho#222]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
litho 0.5

## Issues and Steps to Reproduce
1. Create an simple Android app with buck using some prebuilt_native_library
2. Make sure the above reference native libraries only support armeabi-v7a
3. Add litho-core and litho-widget as a deps
4. In the genrated APK, only libfb.so and libyoga.so is present and they are put in arm64 folder. Somehow it overrides all my previous native libraries.

## Expected Behavior
In the generated APK, both existing so files and the new libfb.so and libyoga.so should be present.

## Some other things to mention:
1. I use exopackage in my app
2. NDK should be correctly configured for my buck as $ANDROID_NDK shows /Users/xyz/Library/Android/sdk/ndk-bundle
3. In gradle everything works

**Comment by jollycopper** [comment]
This might be similar to https://github.com/facebook/litho/issues/96.

After I include Litho in BUCK, it forces my project to be arm64. Weird.

**Comment by ywensc** [comment]
I think I solved the problem by specifying my android_binary's cpu_filters to be armv7... Feel free to close the issue.

**Comment by passy** [comment]
Do you have a sample project or some code that could help reproduce this? I haven't seen this kind of behavior before.

**Comment by passy** [comment]
Friendly ping. :)

**Comment by jollycopper** [comment]
I was able to fix the issue by setting cpu_filters to my BUCK filter. I think this might be a BUCK issue, not Litho's. :) Feel free to close it.
