### ISSUE TITLE
Litho's buck documentation is totally broken

### ISSUE THREAD

**Issue by jollycopper** [facebook/litho#223]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

1. In the [Getting Started](https://fblitho.com/docs/getting-started) doc's BUCK section, the first android_prebuilt_aar references the wrong file litho.aar. It should be litho-core.aar.
2. In line 58, com.facebook.litho.processor.ComponentsProcessor is a wrong name and does not exist.
3. litho-processor:aar:0.5.0 does not exist. It should have been litho-processor:jar:0.5.0.

In general, I feel Litho compiling with BUCK for external developers is poorly tested and has many issues. I just filed [another bug](https://github.com/facebook/litho/issues/222) about native libraries.

@passy Please fix the docs! :)

**Comment by jollycopper** [comment]
Another question is how exactly we should include litho-annotations in BUCK. provided_deps is not an option for android_library target.

**Comment by passy** [comment]
I'm sorry if you had a bad experience with the documentation. :(

> In general, I feel Litho compiling with BUCK for external developers is poorly tested and has many issues. I just filed another bug about native libraries.

It is certainly true that it receives less rigor than the gradle-based system, with the main reason being that Gradle is the de-facto standard in the community. We are a small team with limited resources and can't constantly test all configuration ourselves. Instead, we rely on reports like these to get better.

If there are obvious problems that you find, please consider opening PRs. It's often faster to just fix a typo than to write a sentence referencing it and for us it's just a button-press away from fixing. :)

Thanks for your report!

**Comment by passy** [comment]
> Another question is how exactly we should include litho-annotations in BUCK. provided_deps is not an option for android_library target.

We do use `provided_deps` in the open source build of litho through `android_library` and according to the buck source it should be available: https://github.com/facebook/buck/blob/adc0f78a68db45334098ac083171c7c2ebc32a8c/src/com/facebook/buck/android/AndroidLibraryDescription.java#L123

I think it may just be missing documentation. Closing this for now but let me know if you still have any issues with this.
