### ISSUE TITLE
Support for targetSdkVersion=26?

### ISSUE THREAD

**Issue by davidgoli** [facebook/litho#226]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.google.code.findbugs'
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:support-annotations:25.3.1'

    // RxAndroid
    compile 'io.reactivex.rxjava2:rxandroid:2.0.1'
    compile 'io.reactivex.rxjava2:rxjava:2.1.2'

    // Litho
    compile 'com.facebook.litho:litho-core:0.5.0'
    compile 'com.facebook.litho:litho-widget:0.5.0'
    compile 'com.facebook.soloader:soloader:0.2.0'
    provided 'com.facebook.litho:litho-annotations:0.5.0'

    annotationProcessor 'com.facebook.litho:litho-processor:0.5.0'

    debugCompile 'com.facebook.litho:litho-stetho:0.5.0'
    testCompile 'com.facebook.litho:litho-testing:0.5.0'

    androidTestCompile 'com.facebook.litho:litho-espresso:0.5.0'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support.test.espresso:espresso-intents:2.2.2'

    testCompile 'junit:junit:4.12'
    testCompile "org.robolectric:robolectric:3.4.2"

## Issues and Steps to Reproduce
Use the above dependencies
Using com.android.support:appcompat-v7:25.3.1 gives a lint error: `This support library should not use a different version (25) than the compileSdkVersion (26)`
Using com.android.support:appcompat-v7:26.0.0-alpha1 gives a compile error: Error:Conflict with dependency 'com.android.support:support-vector-drawable' in project ':app'. Resolved versions for app (26.0.0-alpha1) and test app (25.3.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

## Expected Behavior
Would be great if we were able to use Litho against API Level 26. We're working for a large client and they will probably decline the use of Litho for the app since a big requirement for them is compatibility with the latest version of the Android API (even though 26 is still alpha).

**Comment by passy** [comment]
Sorry, I don't quite follow. How does the Litho dependency come into play here? Why can't you just override the dependencies you need to make this work with SDK 26?

**Comment by davidgoli** [comment]
@passy It's not clear/documented how to do that. These build problems only come after adding Litho dependencies, most directly involving RecyclerView's version.

**Comment by davidgoli** [comment]
Nevermind, figured it out. It's necessary to add the following to the app module's `build.gradle`:

```
configurations.all {
    resolutionStrategy {
        force 'com.android.support:appcompat-v7:26.+'
        force 'com.android.support:support-compat:26.+'
        force 'com.android.support:support-core-ui:26.+'
        force 'com.android.support:support-annotations:26.+'
        force 'com.android.support:recyclerview-v7:26.+'
    }
}
```

Would be great to add this to the documentation!

**Comment by passy** [comment]
Thanks for sharing, @davidgoli!
