### ISSUE TITLE
Rename RenderInfo related methods/classes

### ISSUE THREAD

**Issue by hussainahmad** [facebook/litho#229]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
***V:0.6.0***

## Issues and Steps to Reproduce
I noticed you replaced  `ComponentInfo` with `RenderInfo`  when I run the code  getting error **Error:(143, 61) error: cannot find symbol method create()
Error:(145, 67) error: cannot find symbol method build()** 

## Expected Behavior
`RenderInfo.create() not found`

![componentinfo](https://user-images.githubusercontent.com/5903522/29553684-ac763a48-8735-11e7-981e-882ace530f5f.png)

![renderinfo](https://user-images.githubusercontent.com/5903522/29553698-bfebdb96-8735-11e7-830e-ecc5ed62ffe9.png)

**Comment by hussainahmad** [comment]
found Issue , it's not `RenderInfo` here it's `ComponentRenderInfo`  ,  thanks to `Java Docs`

**Comment by hussainahmad** [comment]
![renderinfo](https://user-images.githubusercontent.com/5903522/29555147-23e7173c-873b-11e7-8992-78e044990e33.png)
Feel free to close this Issue

**Comment by pasqualeanatriello** [comment]
Happy Java Docs helped 👍
