### ISSUE TITLE
Litho 0.6.1 missing dependencies in pom.xml

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#231]
The entire section of dependencies is missing in litho 0.6.1, but present in 0.6.0. Is this intentional?

```
  <dependencies>
    <dependency>
      <groupId>com.facebook.yoga</groupId>
      <artifactId>yoga</artifactId>
      <version>1.6.0</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>support-core-ui</artifactId>
      <version>25.3.1</version>
      <scope>compile</scope>
    </dependency>
    <dependency>
      <groupId>com.android.support</groupId>
      <artifactId>recyclerview-v7</artifactId>
      <version>25.3.1</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

0.6.0 pom: https://bintray.com/facebook/maven/download_file?file_path=com%2Ffacebook%2Flitho%2Flitho-core%2F0.6.0%2Flitho-core-0.6.0.pom

0.6.1 pom: https://bintray.com/facebook/maven/download_file?file_path=com%2Ffacebook%2Flitho%2Flitho-core%2F0.6.1%2Flitho-core-0.6.1.pom

**Comment by passy** [comment]
Apologies again. I've reuploaded with the right deps. I wanted to add a verification step for this but ultimately this should be fixed as soon as `android-maven-gradle-plugin` receives an update ... I'll put it on my list for next week if this remains an issue.

**Comment by passy** [comment]
The plugin is fixed now. Waiting for the new release and then this shouldn't happen again. :)

https://github.com/dcendents/android-maven-gradle-plugin/issues/61#issuecomment-325265071
