### ISSUE TITLE
Missing Javadocs for widget package

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#232]
https://fblitho.com/javadoc/com/facebook/litho/widget/Recycler

These show up as google search results, and the classes are clearly there in source and documented but can’t find them in the generated javadoc.

**Comment by passy** [comment]
I'm a bit confused about this. The `.widget` package seems to be online, including the generated specs: https://fblitho.com/javadoc/com/facebook/litho/widget/package-summary.html

I've also tried to search for things like "fblitho widget" and all the links seem to work. The one you provided should have never been a valid link - I think.

Is there anything particular that's missing?

**Comment by hussainahmad** [comment]
@passy please see this [Recycler](https://fblitho.com/docs/recycler-component) , I hope you will find the Issue

**Comment by passy** [comment]
Oh! I think that's a bad link that was there from the start. I thought it was the javadoc generation that was buggy again. I'll fix the broken link straight away. Thanks @hussainahmad!

**Comment by vinc3m1** [comment]
Weird seems fixed now. The widgets package didn't have things like Text, Image, Recycler etc at all.

**Comment by vinc3m1** [comment]
The link I had was 404 at the time of posting, seems fixed now though?

**Comment by passy** [comment]
Yes, I was wrong after all. GitHub seems to allow leaving off the `.html` suffix for hosted files, so your link *should have worked* and there were indeed missing docs. I've updated the internal script we use for generating these so hopefully this shouldn't happen again.

**Comment by passy** [comment]
I've also set up a 404 check for the page to send me an email. I hope that'll make sure I find out about this before someone posts an issue here. :)

**Comment by vinc3m1** [comment]
Awesome thanks for the quick follow up!
