### ISSUE TITLE
Swipe to refresh

### ISSUE THREAD

**Issue by dbof10** [facebook/litho#243]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
`0.6.1`

## Issues and Steps to Reproduce
Since `RecyclerViewWrapper` inherits from `SwipeRefreshLayout`, swipe down should show refresh indicator but nothing happens. Because it's not well-documented, is there  any method to activate to refresh?

**Comment by marco-cova** [comment]
You should pass a PTRRefreshEvent EventHandler as prop (called 'refreshHandler') of your Recycler component.
The pull to refresh should than be enabled and you will be called back on that event when a pull to refresh action is performed.

**Comment by dbof10** [comment]
```
companion object {
  
        @JvmStatic
        @OnCreateLayout
        fun onCreateLayout(c: ComponentContext,
                           @Prop binder: RecyclerBinder,
                           @Prop scrollListener: RecyclerView.OnScrollListener): ComponentLayout {
            return Recycler.create(c)
                    .binder(binder)
                    .onScrollListener(scrollListener)
                    .pTRRefreshEventHandler(HomeListComponent.onRefresh(c))
                    .withLayout()    
                    .build()
        }

        @JvmStatic
        @OnEvent(PTRRefreshEvent::class)
        fun onRefresh(c: ComponentContext) {
            
        }
    }

```
My code does not work

**Comment by marco-cova** [comment]
As I said, the @prop is called "refreshHandler"
`
Recycler.create(c)
    .binder(...)
    .refreshHandler(MyComponent.onRefresh(c))
    ...
`

**Comment by dbof10** [comment]
it works. Thanks. However , exposing `pTRRefreshEventHandler` make confused.

**Comment by dbof10** [comment]
With `Button` it's able do to something like 
```@OnEvent(ClickEvent.class)
  static void onClick(ComponentContext c, @FromEvent View view,
      @Prop OnButtonClickListener listener) {
    listener.onButtonClick();
  }
```
With `Recycler` unfortunately, it is not
```
        @OnEvent(PTRRefreshEvent::class)
        static void onRefresh(ComponentContext c, @Prop OnRefreshListener refreshListener) {
            refreshListener.onRefresh()
        }
```

**Comment by dbof10** [comment]
Reference https://fblitho.com/docs/services
