### ISSUE TITLE
Tutorial makes use of dependencies that aren't mentioned in 'getting started'

### ISSUE THREAD

**Issue by danhawkes** [facebook/litho#252]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

Going through the tutorial here: <https://fblitho.com/docs/tutorial#3-creating-a-list-of-items>

In it, you're required to use the `@GroupSectionSpec` annotation, but the lib that contains it isn't mentioned in the [getting started](https://fblitho.com/docs/getting-started) instructions.  

I think the instructions need to be updated to include:
```gradle
    compile 'com.facebook.litho:litho-sections-core:0.7.0'
    provided 'com.facebook.litho:litho-sections-annotations:0.7.0'
```

**Comment by passy** [comment]
Thanks for raising this. We have a few internal changes for this that haven't been synced yet but will over the next couple of days.
