### ISSUE TITLE
SectionContext.newEventHandler incorrectly overrides ComponentContext.newEventHandler

### ISSUE THREAD

**Issue by mullender** [facebook/litho#253]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

Captured from logcat output
```
method Lcom/facebook/litho/sections/SectionContext;.newEventHandler incorrectly overrides package-private method with same name in Lcom/facebook/litho/ComponentContext;
```

**Comment by passy** [comment]
Do you have steps to reproduce this?

**Comment by mullender** [comment]
I saw this in the logs while investigating an unrelated issue. From reading a bit, overriding package private methods is not allowed, and has buggy behavior on older Android devices.
https://stackoverflow.com/a/23094051

Also feel free to close this issue for lack of reproducibility.

**Comment by passy** [comment]
Merged https://github.com/facebook/litho/commit/b9c379dc960adae4bdf12d499299b602b3efc21e
