### ISSUE TITLE
CircleCI: Configure parallelism

### ISSUE THREAD

**Issue by passy** [facebook/litho#254]
Our plan allows for parallel builds but we're not leveraging it at the moment. We should be able to run at least the gradle and buck builds in parallel and cut the wait times down.

There's the yoga build which we shell out to from Gradle, so we may have to run that in advance to prevent stalling.

Documentation here: https://circleci.com/docs/2.0/parallelism-faster-jobs/

**Comment by pavlospt** [comment]
Can be closed now :D !!

**Comment by passy** [comment]
Yasss.
