### ISSUE TITLE
@PropDefault can't compile with BUCK Exopackage resources

### ISSUE THREAD

**Issue by VerTiGoEtrex** [facebook/litho#272]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
```
    compile 'com.facebook.litho:litho-core:0.7.1'
    compile 'com.facebook.litho:litho-widget:0.7.1'
    provided 'com.facebook.litho:litho-annotations:0.7.1'
    provided 'com.facebook.litho:litho-processor:0.7.1'
    annotationProcessor 'com.facebook.litho:litho-processor:0.7.1'
    compile 'com.facebook.soloader:soloader:0.2.0'
    debugCompile 'com.facebook.litho:litho-stetho:0.7.1'
```

## Issues and Steps to Reproduce
Try to use a `@PropDefault` with `resId` attribute while compiling using buck exopackage

Result will be something like
```
error: element value must be a constant expression
    @PropDefault(resType = ResType.COLOR, resId = R.color.some_custom_color) static int someColor;
                                                         ^
```

Caused by exopackage requirement that R.* values not be `final`

## Expected Behavior
I assume `PropDefault` generates some builder code with some const R.* values, hence this error. If building with exopackage or non-final R.* values, I would still expect `@PropDefault` with `resId=x` to function.

Thanks!

**Comment by passy** [comment]
That's a known bug that we can't work around at the moment. My understanding is that this isn't a limitation of the annotation processor, but of Java itself, which requires values passed into annotations to be constant.

**Comment by pavlospt** [comment]
Is this a BUCK limitation? It seems to build just fine for me :)

**Comment by passy** [comment]
Yes, I believe this is something related to exo package where IDs are changed on the fly. I might be mixing things up, though.
