### ISSUE TITLE
TextAppearance_AppCompat_Title not rendered properly in TextSpec

### ISSUE THREAD

**Issue by dsyang** [facebook/litho#276]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
    lithoVersion = '0.8.0'

## Issues and Steps to Reproduce
  https://imgur.com/a/A8zEZ
- The first "All TO-DOs" is a TextView with `mTextView.setTextAppearance(R.style.TextAppearance_AppCompat_Title)`
- The section "All TO-DOs" is a TextSpec with 
`Text.create(c, 0, R.style.TextAppearance_AppCompat_Title)`

## Expected Behavior
The Expected Behavior is that both strings look exactly the same
The observed behavior is that one looks less bold than the other.

## Link to Code
https://github.com/dsyang/android-architecture/tree/todo-litho

**Comment by passy** [comment]
Could this be because of #204?

**Comment by passy** [comment]
Yes, it is. Since this should now be thread-safe, I'm reenabling this.

**Comment by passy** [comment]
D6358856
