### ISSUE TITLE
Are TreeProps in Sections just not yet implemented?

### ISSUE THREAD

**Issue by drd** [facebook/litho#277]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
`0.8.0` (and `master` too)

## Issues and Steps to Reproduce
Attempt to pass a `TreeProp` from a parent component into a `Section`. It will be `null`.

## Expected Behavior
I would like to be able to use `TreeProp`s with `Section`s :)

## Link to Code
https://github.com/facebook/litho/blob/master/litho-sections-core/src/main/java/com/facebook/litho/sections/SectionLifecycle.java#L205

This just seems like it's not yet written, but I'd like to clarify, and also would be happy to contribute, but not sure I understand enough about Litho implementation details at the moment to plow into this without guidance.

Thanks for an awesome library!

**Comment by drd** [comment]
On further reading, I believe the linkage is broken when creating a `SectionContext` from a `ComponentContext`. The `TreeProps` of the `ComponentContext` is not copied to the new `SectionContext`.

**Comment by pavlospt** [comment]
@drd Since `SectionContext` extends `ComponentContext` `TreeProps` live on the super class. You can chech that one here. https://github.com/facebook/litho/blob/563b251179e3d34d1559be6f4070f4a226a0cf79/litho-sections-core/src/main/java/com/facebook/litho/sections/SectionContext.java#L114

Do you have a link for the broken linkage you are mentioning?

**Comment by passy** [comment]
cc @pasqualeanatriello

**Comment by drd** [comment]
Here is an example: https://github.com/drd/litho/tree/drd/tree-props

I put it in the `samples-codelab` module, if you run that you will get an NPE. It appears to be crashing during `LithoView#onMeasure`, so perhaps the linkage is broken there. (I even tried a little hack to allow the `SectionContext` to explicitly retrieve and set its `TreeProps` from the `ComponentContext` but that did nothing… will keep digging)

**Comment by dsyang** [comment]
I don't believe we've gotten around to implementing tree props in sections. Would love it if you wanted to contribute! I'm AFK right now so I can't help with many pointers now but one crucial step is to make sure treeprops related code is generated when running the annotation processor. Take a look at TreePropsGenerator.java and see if it's used in any of the SpecModel#generate() methods.

**Comment by pasqualeanatriello** [comment]
TreeProps should work within a Section hierarchy. What is not supported at the moment is to share TreeProps between Components and Sections. This is something we'd love to support but never had the time for. Contributions there are super welcome of course :)

**Comment by pavlospt** [comment]
@pasqualeanatriello What do you mean by share?

**Comment by pasqualeanatriello** [comment]
suppose you create some TreeProps in a Section. Now you render a Component from that Section. The Component will not inherit any TreeProp from the Section.
Similarly if you create a Section inside a Component's OnCreateLayout.

**Comment by pavlospt** [comment]
I think that would need another annotation variable then, on whether you want the Component or Section to inherit those `TreeProps` or not! Otherwise forcing a share of `TreeProps` might feel unexpected. What do you think?

**Comment by mihaelao** [comment]
TreeProps can now cross the hierarchy between Sections to Components, closing this.
