### ISSUE TITLE
ViewPager of LithoViews only renders first screen

### ISSUE THREAD

**Issue by jbarr21** [facebook/litho#280]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
```
    annotationProcessor 'com.facebook.litho:litho-processor:0.8.0'
    compile 'com.facebook.litho:litho-core:0.8.0'
    compile 'com.facebook.litho:litho-widget:0.8.0'
    provided 'com.facebook.litho:litho-annotations:0.8.0'
    annotationProcessor 'com.facebook.litho:litho-sections-processor:0.8.0'
    compile 'com.facebook.litho:litho-sections-core:0.8.0'
    compile 'com.facebook.litho:litho-sections-widget:0.8.0'
    provided 'com.facebook.litho:litho-sections-annotations:0.8.0'
    compile 'com.facebook.soloader:soloader:0.2.0'
```

## Issues and Steps to Reproduce
- Install [forked Conductor sample app with Litho](https://github.com/jbarr21/Conductor/tree/litho-pager) using `./gradlew :demo:installDebug`
- Launch the app and tap "View Pager"
- Observe Page 0 renders correctly
- Scroll to Page 1, observe no LithoView has been shown
- Scroll to Page 2, also not displayed
- Scroll back to Page 0, observe the LithoView is not displayed

## Expected Behavior
Scrolling between pages 0, 1, and 2 should all display the contents of their LithoViews

## Link to Code
https://github.com/jbarr21/Conductor/tree/litho-pager

**Comment by passy** [comment]
I don't know much about that framework or ViewPagers, but have you checked if `inflateView` is called by setting a breakpoint there?

**Comment by pasqualeanatriello** [comment]
cc @IanChilds that knows more about Litho+ViewPager

**Comment by IanChilds** [comment]
Unfortunately, right now Litho fails to work when a LithoView is used as a direct child of a ViewPager. You have a few options: 
1. Add

```
        ComponentsConfiguration.incrementalMountUsesLocalVisibleBounds = true;
        ComponentsConfiguration.lithoViewIncrementalMountUsesLocalVisibleBounds = true;
```
to `DemoApplication.onCreate()`. 

2. Wrap the LithoView in a FrameLayout. 
3. You can create the ComponentTree that LithoView.create() creates manually, and set incrementalMount to be false. 

I suggest that (1) is the easiest. It's the approach we're moving towards anyway (we are just experimenting with it right now).

**Comment by ihenk** [comment]
> Unfortunately, right now Litho fails to work when a LithoView is used as a direct child of a ViewPager. You have a few options:
> 
> 1. Add
> 
> ```
>         ComponentsConfiguration.incrementalMountUsesLocalVisibleBounds = true;
>         ComponentsConfiguration.lithoViewIncrementalMountUsesLocalVisibleBounds = true;
> ```
> 
> to `DemoApplication.onCreate()`.
> 
> 2. Wrap the LithoView in a FrameLayout.
> 3. You can create the ComponentTree that LithoView.create() creates manually, and set incrementalMount to be false.
> 
> I suggest that (1) is the easiest. It's the approach we're moving towards anyway (we are just experimenting with it right now).

Any updates on this issue? I'm facing the same question. The version of litho we use is '0.39.0'. We create the componentTree with 'incrementalMount(false)', and wrap the LithoView in a FrameLayout. However it doesn't work.
