### ISSUE TITLE
TreeProps don't support types with generics

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#285]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.11.0

## Issues and Steps to Reproduce
Set a @TreeProp with a generic, like `Observable<Integer>`.

## Expected Behavior
Compiles.

## Link to Code
https://github.com/vinc3m1/litho/commit/4b164a6dd08dbfcdf9340a8a3200ab56be85a218

**Comment by pavlospt** [comment]
Hey @vinc3m1, this seems to be working in `0.15.0`! Can you test it again :) ?

**Comment by passy** [comment]
And if not, let me know. I'm working on TreeProps right now and could take a look at how to support that. :)

**Comment by vinc3m1** [comment]
Going to close for now since we're no longer using generics in treeprops, but can re-open if someone else finds an issue.
