### ISSUE TITLE
build failure on win: BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly

### ISSUE THREAD

**Issue by DemoDu** [facebook/litho#291]
build failure on win: BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly  

No way out

**Comment by passy** [comment]
@DemoDu Please follow the template that we provide and fill in as many details you can provide so that we can actually help you. Feel free to open another issue with the missing information.

**Comment by DemoDu** [comment]
Thanks for the reply, I git clone this project
Follow the prompts
$ buck fetch sample
$ buck install -r sample
Inside my environment has been installed buck and downloaded in the mac environment installed Android-NDK and Android-SDK and has been set up ~ / .bash_profile inside the environment variables
But the last implementation of the $ buck fetch sample command will prompt me the following error
build failure on win: BUILD FAILED: No native platforms detected. Probably Android NDK is not configured properly
I am very puzzled
Maybe there is a mistake in my operation
My mac has been installed a series of tools such as Xcode Python ant and so on
Thank you

**Comment by passy** [comment]
Thanks for additional details, @DemoDu. This is not a Litho issue but a problem with your Buck setup. Perhaps following the Gradle setup is a bit easier.

Otherwise, please follow the guidelines in the [Buck docs](https://buckbuild.com/setup/getting_started.html) which define a bunch of environment variables which are probably not set up correctly.

**Comment by erhu** [comment]
Add 
```
ANDROID_HOME=/Users/xxx/Library/Android/sdk
ANDROID_NDK=/Users/xxx/Library/Android/sdk/ndk-bundle
```
to your .buckconfig file.
