### ISSUE TITLE
TextSpec doesn't respect "android:textColor" style

### ISSUE THREAD

**Issue by dsyang** [facebook/litho#292]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
v0.11.0

## Issues and Steps to Reproduce
I have a text spec that's created with a style: 
```
Text.create(c, 0, R.style.TextAppearance_AppCompat_Title)
    .text("Something")
    .build();
```
but the text is incorrectly colored. According to the TextAppearance.AppCompat.Title style, `android:textColor="?attr/textColorPrimary"`

If I explicitly set the color to be `textColorPrimary` then it works fine. 

To Reproduce:
 - build https://github.com/dsyang/android-architecture/tree/dev-todo-mvp-litho/
 - observe that the text is a light grey and different from the "All TO-DOs" text (which is set to `@style/TextAppearance.AppCompat.Title`)
 -  uncomment  https://github.com/dsyang/android-architecture/blob/dev-todo-mvp-litho/todoapp/app/src/main/java/com/example/android/architecture/blueprints/todoapp/tasks/TaskItemSpec.java#L48
 - observe that the text is the same dark color.

## Expected Behavior
```
Text.create(c, 0, R.style.TextAppearance_AppCompat_Title)
    .text("Something")
    .build();
```
Should have the same textColor as a TextView set to `android:textAppearance="@style/TextAppearance.AppCompat.Title"`

## Link to Code

https://github.com/dsyang/android-architecture/tree/dev-todo-mvp-litho/

**Comment by mihaelao** [comment]
Investigated this and it's now working on the latest version
