### ISSUE TITLE
Strange UI behavior with Column

### ISSUE THREAD

**Issue by dbof10** [facebook/litho#296]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.11

## Issues and Steps to Reproduce
I'm using a `HorizontalRecycler` with each item

```
 Column.create(c)
                .backgroundColor(ContextCompat.getColor(c, R.color.white_100))
                .child(
                        Row.create(c)
                                .child(
                                        Text.create(c, 0, R.style.Text_Body)
                                                .text(resources.getQuantityString(R.plurals.like, viewModel.votesCount, viewModel.votesCount))
                                                .marginRes(YogaEdge.START, R.dimen.space_small)
                                )
                                .child(
                                        Text.create(c, 0, R.style.Text_Body)
                                                .text("•")
                                                .marginRes(YogaEdge.START, R.dimen.space_small)
                                                .marginRes(YogaEdge.END, R.dimen.space_small)

                                )
                                .child(
                                        Text.create(c, 0, R.style.Text_Body)
                                                .text(resources.getQuantityString(R.plurals.comment, viewModel.commentsCount, viewModel.commentsCount))
                                )
                                .flex(1F)
                                .marginRes(YogaEdge.TOP, R.dimen.content_padding_vertical)
                                .marginRes(YogaEdge.BOTTOM, R.dimen.content_padding_vertical)
                                .justifyContent(YogaJustify.FLEX_START)
                                .build()
                )
                .build()
```
![colum](https://user-images.githubusercontent.com/10725747/34441735-3d6f91aa-ecf0-11e7-8424-194f188b4b1e.gif)
As noticed, the first item is correct. the rest are laid out improperly

If `Column` is removed, it looks like

![columno](https://user-images.githubusercontent.com/10725747/34441767-7161a232-ecf0-11e7-99f7-25146da0f3eb.gif)

As expected behavior, whether `Column` is used or not, the UI should be correct.

**Comment by marco-cova** [comment]
Hi @dbof10, the information provided are not sufficient to debug your issue. There's no `HorizontalRecycler` component. There's a `Recycler` and an `HorizontalScroll`.. and also we have a `RecyclerCollectionComponent` in the sections.widget package... which one is it?

Your example also shows images, and it looks like they are the ones affected by this bug"bug", but your code doesn't have images.
Would it be possible to provide a bit more context and more code that we could just plug and use in our playground app to replicate this weird behavior?
Thanks!!

**Comment by dbof10** [comment]
I'm sorry for my bad description. `HorizontalRecycler` I meant is `RecyclerCollectionComponent` with ` ListRecyclerConfiguration(LinearLayout.HORIZONTAL,..,..)`. I'm trying to reproduce this bug. I will edit the example code and let you know soon

**Comment by dbof10** [comment]
I close it for now since I can't reproduce. I will continue observing this potential bug.
