### ISSUE TITLE
Not using @Deprecated annotation

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#298]
The deprecated `background(Reference)` function in `Component` is throwing an ErrorProne error of [DepAnn](http://errorprone.info/bugpattern/DepAnn) for not using a full `@Deprecated` annotation on the method.
https://github.com/facebook/litho/blob/42fbaa0ab4329cb78655ecf785217ee1bc5fde83/litho-core/src/main/java/com/facebook/litho/Component.java#L960-L961

Ideally, would be nice to have a check for these in the future.

**Comment by IanChilds** [comment]
Good point. I'll fix this.
