### ISSUE TITLE
Remove usage of @RestrictTo

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#299]
`@RestrictTo` is actually not meant to be general purpose or used external to the support library, see: https://github.com/google/error-prone/issues/812#issuecomment-349119297

We should probably remove it from Litho so error prone won't complain for others building from source (like me 😄).
https://github.com/facebook/litho/blob/27b238c880254042ee97b473f58495c3ce42961d/litho-core/src/main/java/com/facebook/litho/LayoutState.java#L154-L155

**Comment by IanChilds** [comment]
@passy - looks like you added these?

**Comment by passy** [comment]
Ah, thanks for the info. I thought this would get IntelliJ support at some point and we could get something close to a `@hide` we can use.

I'll remove the few usages we have.
