### ISSUE TITLE
ErrorProne findings

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#303]
Since you wanted me to report any error prone checks I ran into, just letting you know what you're triggering. These are all suppressed so they're not blocking anything:

 - [MissingCasesInEnumSwitch](http://errorprone.info/bugpattern/MissingCasesInEnumSwitch)
    - BuilderGenerator.java
    - PropValidation.java
    - Border.java
 - [GuardedBy](https://github.com/google/error-prone/blob/master/docs/bugpattern/GuardedBy.md)
    - ComponentTreeHolder.java
    - RecyclerBinder.java
    - SectionTree.java

Again, not a huge deal since we're not blocking on them, but could be useful to enable.

**Comment by passy** [comment]
Thanks for the list, Vince! I'll try to get them fixed.

**Comment by vinc3m1** [comment]
Another one found here:
https://github.com/facebook/litho/blob/b5764a095151fe5a248857855a991262144adcae/litho-sections-widget/src/main/java/com/facebook/litho/sections/widget/RecyclerCollectionComponentSpec.java#L116

> Declaring a type parameter that is only used in the return type is a misuse of generics: operations on the type parameter are unchecked, it hides unsafe casts at invocations of the method, and it interacts badly with method overload resolution.
> https://github.com/google/error-prone/blob/master/docs/bugpattern/TypeParameterUnusedInFormals.md

**Comment by passy** [comment]
The warning is absolutely correct, but this one seems harder to fix then most of the others.

**Comment by passy** [comment]
I'll close this one for now as we are no longer blocked on this.
