### ISSUE TITLE
What IDE do the main contributers use

### ISSUE THREAD

**Issue by VerTiGoEtrex** [facebook/litho#311]
Hi, just curious what IDE (if any) the main contributors use to develop Litho? 

I see there's a build.gradle now, but the entire project is centered around BUCK as the main build system, and Android Studio/Intellij support seems a tad light, so I guessed you used something besides Android Studio?

**Comment by passy** [comment]
Hey @VerTiGoEtrex! These kinds of questions are usually better discussed in chat. :)

The core team members all use IntelliJ or Android Studio. We consider Gradle the main build system for the open source version, but use Buck to build Litho as part of our Monorepo.
