### ISSUE TITLE
Compile-time error when passing generated class instance into generated spec

### ISSUE THREAD

**Issue by ar-g** [facebook/litho#313]
## Issues and Steps to Reproduce
During compilation, I'm getting an error:

`
AdPageListSpec.kt: (38, 40): Type mismatch: inferred type is GlideRequests but NonExistentClass was expected
`

## Link to Code
```kotlin
 public Builder glide(@NotNull NonExistentClass glide) {
      this.mAdPage.glide = glide;
      mRequired.set(3);
      return this;
    }
```
First I thought that the problem is in the dependencies order, but it is not. It seems that code generation tasks run in parallel which is causing this issue. Does anybody knows how to tune it?
```groovy
    implementation 'com.github.bumptech.glide:glide:4.6.1'
    kapt 'com.github.bumptech.glide:compiler:4.6.1'

    // Litho
    implementation 'com.facebook.litho:litho-core:'+ lithoVersion
    implementation 'com.facebook.litho:litho-widget:'+ lithoVersion
    compileOnly 'com.facebook.litho:litho-annotations:'+ lithoVersion
    kapt 'com.facebook.litho:litho-processor:'+ lithoVersion
    implementation 'com.facebook.litho:litho-sections-core:'+ lithoVersion
    implementation 'com.facebook.litho:litho-sections-widget:'+ lithoVersion
    compileOnly 'com.facebook.litho:litho-sections-annotations:'+ lithoVersion
    kapt 'com.facebook.litho:litho-sections-processor:' + lithoVersion
```

**Comment by passy** [comment]
This is a known issue with kapt, the Kotlin annotation processor. Sadly, there isn't anything we can do from our side. It often helps to properly clean your project and rerun it which in my experience works almost every time. If it doesn't, you'll have to bite the bullet and write this one in Java.
