### ISSUE TITLE
Error when generating prop for LatLng

### ISSUE THREAD

**Issue by ar-g** [facebook/litho#315]
Basically, the error is:

```
Error:(30, 2) error: Error processing the param 'model'. Are your imports set up correctly? The causing error was: java.lang.IllegalArgumentException: couldn't make a guess for com.google.android.gms.internal.zzbck
    com.google.android.gms.maps.model.LatLng model) {
                                             ^
```
Does it mean that it is not possible to use such classes as props?

**Comment by passy** [comment]
@ar-g Could you provide more context? Generally, there are no exclusions for what can be used for Props. The only class of props that can cause problems are those that are generated themselves.

**Comment by ar-g** [comment]
@passy It seems like this issue was related to specific build. This issue is not reproducible anymore.
