### ISSUE TITLE
text styles are not working properly inside a column

### ISSUE THREAD

**Issue by yigit** [facebook/litho#324]
version: `0.12.0`

If I create the following layout:
```
Column.create(componentContext)
  .child(
    Text.create(componentContext, 0, R.style.TextAppearance_AppCompat_Large).text("Hello!")
  )
   .build()
```
It looks like [this][1]

But if i remove the column and create a Text directly, it looks like [this][2] (expected result)
```
Text.create(componentContext, 0, R.style.TextAppearance_AppCompat_Large).text("Hello!")
    .build()
```

Not sure what I'm doing wrong here but seems like text styles are not working properly when there is a Column parent. There are no other UI elements here, the result is just put into a `LithoView` and set as the content view of the `Activity`.

[1]: https://www.evernote.com/shard/s19/sh/7439710a-826f-4bdb-9270-f2a3228c7a9c/68da22a66bfae9cc
[2]: https://www.evernote.com/shard/s19/sh/b162c223-7a07-461d-b5cd-c8f89fe9a6a8/0556b293c9e34012

**Comment by pavlospt** [comment]
Have you tried using the other constructor where you can pass `defaultStyleAttrs` and `defaultStyleRes`? 
https://github.com/facebook/litho/blob/7706f4e1d6f35af374371e8b343151e59a333b19/litho-core/src/main/java/com/facebook/litho/Column.java#L67

**Comment by yigit** [comment]
Not sure what you mean but I've also tried
`Text.create(c, R.attr.textAppearanceListItem, 0).text("Hello!")`
same problem, it works outside column and breaks inside a Column.

**Comment by pavlospt** [comment]
I mean Column’s constructor :)

**Comment by yigit** [comment]
nope, doesn't work.

**Comment by topwu** [comment]
Seems like when Text is created as a child of a Column, the method `TextDrawable#onStateChange()` isn't triggered, which leads to incorrect text color rendering.
https://github.com/facebook/litho/blob/7706f4e1d6f35af374371e8b343151e59a333b19/litho-widget/src/main/java/com/facebook/litho/widget/TextDrawable.java#L97

**Comment by passy** [comment]
@IanChilds Could this have to do with the new Column-as-Component implementation?

**Comment by IanChilds** [comment]
It's plausible. Did this used to work?

**Comment by kar** [comment]
Any updates on this?

**Comment by mihaelao** [comment]
Verified and cannot repro this, applying styles on a Text inside or outside a Row/Column is working. Please reopen will repro steps if still having issues
