### ISSUE TITLE
About update state int recycler

### ISSUE THREAD

**Issue by jerboy** [facebook/litho#332]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.12.0

## Issues and Steps to Reproduce
`the code below is an item of GroupSection`,when scroll away from this item, **updateCollectStatus** will not called.
```java
    @OnCreateInitialState
    static void onCreateInitialState(final ComponentContext c, final StateValue<Boolean> collected ){
      post.set(postBean);
      collected.set(false);

      new android.os.Handler().postDelayed(new Runnable() {
        @Override
        public void run() {
          collected.set(true);
        }
      }, 5000);
  }
```
```java
  @OnUpdateState
  static void updateCollectStatus(StateValue<Boolean> collected, @Param boolean collect){
    collected.set(collect);
  }
```
## Expected Behavior
I expected `updateCollectStatus` will be called after 5 seconds, but not.

**Comment by marco-cova** [comment]
Hi @jerboy, you're misusing the State APIs. You should not change `StateValues` params within `onCreateInitialState` over time. As the method name suggests, you should only initialize `StateValues` in there.
If you want to change state values at any point in time, after initialization, you should call the proper state update method. In your case that would be `YourComponent.updateCollectStatus(c, true);`.
For more information about state, please refer to our documentation: [https://fblitho.com/docs/state](https://fblitho.com/docs/state).

**Comment by astreet** [comment]
Additionally, we don't provide guarantees on when exactly `onCreateInitialState` (and `onCreateLayout`) is called: it would be better to trigger the runnable from a visibility event if possible.

**Comment by jerboy** [comment]
@marco-cova I mean that I need to get data from remote server when `onCreateInitialState` is called, But if this component is in recycler and  I called `YourComponent .updateCollectStatus(ComponentContext c, boolean collected` , but ` updateCollectStatus(StateValue<Boolean> collected, @Param boolean collect)` is not called after the recyclerView has scroll a long distance away , So I guess this Component is released, And I want to know how to fix it?

**Comment by passy** [comment]
@jerboy This is generally not how you want to structure your application. Think of components as pure functions that transform props into a UI. You'll want to keep your server interaction entirely separate from your UI. When you have new data, set new props on your component or on your binder/DiffSection.

I'd recommend checking out the docs about Sections: https://fblitho.com/docs/sections-intro
