### ISSUE TITLE
Why  @OnPrepare called twice ?

### ISSUE THREAD

**Issue by jerboy** [facebook/litho#334]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
***0.13.1***

## Issues and Steps to Reproduce
***Method annotated by @OnPrepare called twice, not really true by `https://fblitho.com/docs/mount-specs`  ***

## Expected Behavior
***Only once!***

## Link to Code
```java
@MountSpec
public class MyMountSpec {
  @OnCreateInitialState
  static void OnCreateInitialState(ComponentContext c, StateValue<Integer> videoBean){
    Log.e("MyLOG", "OnCreateInitialState");
    videoBean.set(null);
  }

  @OnPrepare
  static void onPrepare(ComponentContext c, @Prop int videoId){
    Log.e("MyLOG", "onPrepare " + videoId);
  }

  @OnCreateMountContent
  static TextView getVideoView(ComponentContext c){
    Log.e("MyLOG", "getVideoView");
    return new TextView(c);
  }

  @OnMount
  static void onMount(ComponentContext c, TextView videoView, @State Integer videoBean){
    Log.e("MyLOG", "onMount");
  }

  @OnUnmount
  static void onUnMount(ComponentContext c, TextView videoView){
    Log.e("MyLOG", "onUnMount");
  }

  @OnMeasure
  static void onMeasure(ComponentContext c, ComponentLayout layout, int widthSpec, int heightSpec, Size out){
    // TODO: 2018/3/28
    MeasureUtils.measureWithAspectRatio(widthSpec, heightSpec, 1, out);
  }
}
```

**Comment by IanChilds** [comment]
This depends upon how you are using your MountSpec. What is the calling code?

**Comment by pasqualeanatriello** [comment]
There is a possibility of a layout happening more than once (say on two
different threads). You shouldn't assume that prepare gets called only
once. Only one of the two invocations should be part of a valid layout
computation though.

**Comment by jerboy** [comment]
@IanChilds @pasqualeanatriello `https://github.com/jerboy/LithoTest` here is my code, just basic usage

**Comment by IanChilds** [comment]
Hi @jerboy - please see @pasqualeanatriello's comment - there's no guarantee that it will only be called once.

**Comment by jerboy** [comment]
@IanChilds but it said called once only by the document.
