### ISSUE TITLE
why sBuilderPool  not release???

### ISSUE THREAD

**Issue by guiyichen** [facebook/litho#335]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
***  implementation 'com.facebook.litho:litho-core:0.13.0'
    implementation 'com.facebook.litho:litho-widget:0.13.0'***

## Issues and Steps to Reproduce
***every component have sBuilderpool
private static final Pools.SynchronizedPool<Builder> sBuilderPool =
      new Pools.SynchronizedPool<>(2);
why it not release???
***

## Expected Behavior
***when component create more it exist more .***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using***

**Comment by passy** [comment]
The release happens in the component's `release()` method:

https://github.com/facebook/litho/blob/469a41133c19d332e097d9cf073463fb90991b77/litho-it/src/test/resources/processor/SimpleLayout.java#L87

**Comment by guiyichen** [comment]
but  initialize  was 2 ; and it's not release empty; when the component more and more ,it's stay at the memory ???

**Comment by passy** [comment]
Sorry, I don't follow.

**Comment by guiyichen** [comment]
Unscientific

**Comment by guiyichen** [comment]
well ,I mean the sBuilderPool  was 2 , when release(this); why not clean the Object[]  ? and how clean the  Object[] ?
