### ISSUE TITLE
Transfer @Nullable annotation from @Prop to generated Component

### ISSUE THREAD

**Issue by passy** [facebook/litho#343]
When marking a `@Prop` as `@Nullable`, the generated component should have the field and the parameter in the builder method also generated with `@Nullable`. This helps static analysis.

Point of contact: @passy

**Comment by pavlospt** [comment]
I can take it if it is still free :)

**Comment by pavlospt** [comment]
Update 1) From a quick look, I see that the annotation is transferred to the `Builder` 's method but not on the class field. 

@passy I can update it to transfer it to the class field as well, if that is ok :)

**Comment by passy** [comment]
@pavlospt Oh great! I didn't know we already did this for builders. Yeah, would be great if we could transfer them to the fields. :)

**Comment by pavlospt** [comment]
@passy great checking it now!

**Comment by passy** [comment]
Awesome! Ping me if there's anything that's unclear. :)

**Comment by passy** [comment]
Landed! Thanks for the super quick fix, @pavlospt!

![](https://media2.giphy.com/media/wjK3YnjoQf0go/giphy.gif)
