### ISSUE TITLE
Feature: Coloring spans of Text (or some way to layout 2 text components inline)

### ISSUE THREAD

**Issue by mehcode** [facebook/litho#351]
I'd like to be able to change the textColor for a specific span of a Text. I don't see a way to layout 2 text components inline which would handle my use case as well.

We can currently highlight a single span of text. It would suit _my_ needs to just duplicate that functionality and allow changing the foreground color of a single span of text. I'm sure others might need more functionality though. Something similar to `SpannableString` perhaps.

**Comment by passy** [comment]
Hey @mehcode, wouldn't the existing Spannable API allow you to do just that? You can just pass a regular Spannable to a `TextSpec` and apply all the normal styles to it that way: https://github.com/facebook/litho/blob/master/litho-it/src/test/java/com/facebook/litho/widget/TextSpecTest.java#L63

**Comment by mehcode** [comment]
You're totally correct. I'm not sure why I just assumed that since `TextSpec` accepted a `CharSequence` it clearly must not work with `SpannableString`. Still getting used to native Android development apparently. Thanks for the quick pointer.

**Comment by pavlospt** [comment]
@mehcode `SpannableString` implements `CharSequence` so it is accepted wherever a `CharSequence` is needed :)
