### ISSUE TITLE
shadowElevation not working

### ISSUE THREAD

**Issue by xSharkM** [facebook/litho#353]
When i use shadowElevationPx to set a row shadow like android elevation methods,but not show ,i don't know why.

The following is example code.

	@LayoutSpec
	public class TestSpec {
	  @OnCreateLayout
	 static Component onCreateLayout(ComponentContext c) {
	 return Row.create(c)
	        .heightPx(600)
	        .alignItems(YogaAlign.CENTER)
	        .justifyContent(YogaJustify.CENTER)
	        .child(Row.create(c)
	            .alignItems(YogaAlign.CENTER)
	            .justifyContent(YogaJustify.CENTER)
	            .shadowElevationPx(29)
	            .heightPx(300)
	            .widthPx(300)
	            .backgroundColor(Color.GREEN)
	            .child(SolidColor.create(c)
	                .heightPx(150)
	                .widthPx(150)
	                .color(Color.RED))
	            .build())
	        .build();
	 }
	}

then  lithoView.setComponent(Test.create(c).build());

![](https://ws2.sinaimg.cn/large/006tNc79gy1fqy6fbw5hlj30gs0csq2w.jpg)

how to set green  area  shadow?

**Comment by pavlospt** [comment]
Hey @xSharkM, I am not sure that you can apply `shadowElevation*()` on a `Component` that does not support `elevation` at all!

**Comment by zibellon** [comment]
How i can use elevation(shadows)? In my app i need ti create TextBlock with shadow

**Comment by Wesely** [comment]
you can create a Column/Row with shadow res like 

                Column.create(c)
                    .heightDip(4f)
                    .widthPercent(100f)
                    .backgroundRes(R.drawable.toolbar_layout_shadow)
                    .build()
