### ISSUE TITLE
Feature request: scrollOffset in onViewPortChange method

### ISSUE THREAD

**Issue by mishrabhilash** [facebook/litho#354]
scrollOffset will help in creating a viewPager like structure where we can use this value for various UI updates.

**Comment by mihaelao** [comment]
@mishrabhilash onViewportChanged is called with information extracted from the RecyclerView.LayoutManager that's being used. What would be the equivalent API of getting this scrollOffset from it?

**Comment by mihaelao** [comment]
Please reopen if this is still relevant
