### ISSUE TITLE
varArg properties breaks when using most types.

### ISSUE THREAD

**Issue by kjbilliot** [facebook/litho#373]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version

`Config.Dependencies.litho` is `"0.14.0"`

```
    implementation("com.facebook.litho", "litho-core", Config.Dependencies.litho)
    implementation("com.facebook.litho", "litho-widget", Config.Dependencies.litho)
    compileOnly("com.facebook.litho", "litho-annotations", Config.Dependencies.litho)
    kapt("com.facebook.litho", "litho-annotations", Config.Dependencies.litho)
    kapt("com.facebook.litho", "litho-processor", Config.Dependencies.litho)
```

## Issues and Steps to Reproduce

1. Create either LayoutSpec or MountSpec.
2. Add `@Prop(varArg = "name") names : List<String>` as a property. 
3. Code should compile fine here.
4. Change types to something else outside of basic types (IE: Color, TextView, etc)
5. Code will no longer compile, giving the following two errors in the build panel, from the generated component .java file.
`error: illegal start of type    public Builder color(@NotNull) ? extends Color color) {`
`error: ';' expected    public Builder color(@NotNull) ? extends Color color) {`

## Expected Behavior
Code should compile fine, and I should be able to use the component in the way demonstrated in [the documentation](https://fblitho.com/docs/props#variable-arguments) for whatever type I'd need to be a varArg.

## Link to Code
Example code in Kotlin.

```
@LayoutSpec
object TestComponentSpec {
    @OnCreateLayout
    fun onCreateLayout(
        c : ComponentContext,
        @Prop(varArg = "color") colors : List<Color>
    ) : Component {
        return Row.create(c).build()
    }
}
```
Errors from Gradle:

```
e: /home/<snip>/android/app/build/generated/source/kapt/devDebug/com/mingo/chat/ui/TestComponent.java:130: error: illegal start of type
    public Builder color(@NotNull ? extends Color color) {
                                  ^
e: /home/<snip>/android/app/build/generated/source/kapt/devDebug/com/mingo/chat/ui/TestComponent.java:130: error: ')' expected
    public Builder color(@NotNull ? extends Color color) {
                                   ^
e: /home/<snip>/android/app/build/generated/source/kapt/devDebug/com/mingo/chat/ui/TestComponent.java:130: error: ';' expected
    public Builder color(@NotNull ? extends Color color) {
                                           ^
e: /home/<snip>/android/app/build/generated/source/kapt/devDebug/com/mingo/chat/ui/TestComponent.java:130: error: <identifier> expected
    public Builder color(@NotNull ? extends Color color) {
                                                       ^
```

**Comment by pavlospt** [comment]
This should work fine in Java, but I can take a look and fix it for Kotlin code! cc: @passy

**Comment by kjbilliot** [comment]
Thanks a bunch!

**Comment by pavlospt** [comment]
As a quick fix you can annotate `Color` with `@JvmSuppressWildcards` e.g.: `List<@JvmSuppressWildcards Color>`. I will dive a bit deeper to see the root cause! If you are in a hurry use that one :)

**Comment by kjbilliot** [comment]
Thanks! I'll use that until a fix comes in.
