### ISSUE TITLE
Build failure for OnUpdateState with ComponentContext isn't useful

### ISSUE THREAD

**Issue by jsendros** [facebook/litho#390]
- [yes https://github.com/facebook/litho/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+state ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.15.0

## Issues and Steps to Reproduce
Make a ComponentSpec with an `@OnUpdateState` method and put `ComponentContext` as the first argument. The build failure does not describe the reason the build fails. It doesn't even point to the Component causing the issue.

![screen shot 2018-06-23 at 10 04 26 am](https://user-images.githubusercontent.com/707665/41810466-ddd21a9e-76cc-11e8-92b4-9161ccb2ae16.png)

The `@OnUpdateState` method which broke the build was in `VehicleSelectionComponentSpec`, which isn't even mentioned in the build failure.

## Expected Behavior
Build failure clearly indicates the problematic method.

## Link to Code
```
@OnUpdateState
    static void onUpdateVehicleList(
        ComponentContext c,
        StateValue<Set<Long>> vehicles,
        @Param Set<Long> updatedVehicles) {
        vehicles.set(updatedVehicles);
    }
```

**Comment by jsendros** [comment]
Seems like the same obscure build issue happens when you use a `@FromEvent` argument in an `@OnEvent` method which doesn't supply that argument.

**Comment by pavlospt** [comment]
@jsendros Is there any sample project that we could use to reproduce this?

**Comment by jsendros** [comment]
Unfortunately I don't. :'(

**Comment by pavlospt** [comment]
Ok will try to reproduce tonight and see if I can prepare a fix!

**Comment by passy** [comment]
@jsendros Could you post the compiler output for this? I really dislike this new tree-based Gradle view which swallows all the information the AP adds before. I'm on my phone right now, but Pavlos showed me once that there's a button next to the tree thingy to switch back to the console.

**Comment by pavlospt** [comment]
![screen_shot_2018-05-03_at_16 42 17](https://user-images.githubusercontent.com/1070871/41813677-420fc670-7743-11e8-96cf-49488c7123fe.png)

**Comment by pavlospt** [comment]
@jsendros not sure if this could change though :/ indeed it is bad that this view does not output Exception messages.

**Comment by mihaelao** [comment]
Checked and error message appears correct when building now, closing
