### ISSUE TITLE
MountSpec incremental docs and annotation JavaDoc ambiguous/confusing

### ISSUE THREAD

**Issue by jnlopar** [facebook/litho#400]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

The [@OnMount](https://github.com/facebook/litho/blame/428c8f513d68b8bd18f96132e62cf94d74b1adb4/docs/_docs/mount-specs.md#L21) lifecycle documentation states that incremental mounting is enabled by default.

However, `canMountIncrementally` is `false` by default in [MountSpec](https://github.com/facebook/litho/blob/428c8f513d68b8bd18f96132e62cf94d74b1adb4/litho-annotations/src/main/java/com/facebook/litho/annotations/MountSpec.java#L88-L91) itself. The `canMountIncrementally` does state that this only applies to mount specs with views that are or contain a `LithoView`, which is why I think it doesn't necessarily invalidate what the doc says, so I didn't send a PR to change the doc since I'm not sure it's actually incorrect.

I think I'm just missing something obvious, but maybe slightly adjusted wording would clarify this?

**Comment by IanChilds** [comment]
Yeah, probably we should rename `canMountIncrementally` to `hasInternalLithoViews`, or something like that, since that is really what it is saying.
