### ISSUE TITLE
Update state cause refresh global component

### ISSUE THREAD

**Issue by Tobyyyyyyyyyy** [facebook/litho#408]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version

    implementation 'com.facebook.litho:litho-core:0.17.0'
    implementation 'com.facebook.litho:litho-widget:0.17.0'
    compileOnly 'com.facebook.litho:litho-annotations:0.17.0'

    kapt 'com.facebook.litho:litho-processor:0.17.0'

    // SoLoader
    implementation 'com.facebook.soloader:soloader:0.3.0'

    // For integration with Fresco
    implementation 'com.facebook.litho:litho-fresco:0.17.0'

    // For testing
    testImplementation 'com.facebook.litho:litho-testing:0.17.0'

    // Sections
    implementation 'com.facebook.litho:litho-sections-core:0.17.0'
    implementation 'com.facebook.litho:litho-sections-widget:0.17.0'
    compileOnly 'com.facebook.litho:litho-sections-annotations:0.17.0'

    kapt 'com.facebook.litho:litho-sections-processor:0.17.0'
## Issues and Steps to Reproduce
`FrescoImage` in `TestImageComponentSpec` will re-mount when i click `Text` update state in `TestStateComponentSpec`.

This cause refresh global component every time when i just want to refresh itself.

```
Column.create(c)
        .child(TestStateComponent.create(c)
            .marginDip(YogaEdge.TOP, 20f)
            .build())
        .child(TestImageComponent.create(c)
            .marginDip(YogaEdge.TOP, 20f)
            .build())
        .build()
```
```
@LayoutSpec
public class TestStateComponentSpec {

  @OnCreateInitialState
  static void OnCreateInitialState(ComponentContext c, StateValue<Boolean> clicked) {
    clicked.set(false);
  }

  @OnCreateLayout
  static Component OnCreateLayout(ComponentContext c,
      @State boolean clicked) {
    return Row.create(c)
        .child(Text.create(c)
            .textColor(Color.BLACK)
            .textSizeSp(20)
            .text(clicked ? "Clicked" : "Click")
            .clickHandler(TestStateComponent.onItemClick(c))
            .build())
        .build();
  }

  @OnUpdateState
  static void OnUpdateState(StateValue<Boolean> clicked) {
    clicked.set(!clicked.get());
  }

  @OnEvent(ClickEvent.class)
  static void onItemClick(ComponentContext c) {
    TestStateComponent.OnUpdateState(c);
  }
}
```

```
@LayoutSpec
public class TestImageComponentSpec {

  @OnCreateLayout
  static Component OnCreateLayout(ComponentContext c) {
    return Row.create(c)
        .widthDip(32)
        .heightDip(32)
        .child(FrescoImage.create(c)
            .placeholderImageRes(R.drawable.ic_action_ac)
            .controller(Fresco.newDraweeControllerBuilder()
                .build())
            .build())
        .build();
  }
}

```

## Expected Behavior

Update state will only effect itself.

**Comment by mihaelao** [comment]
Currently state updates will always recreate the entire ComponentTree - the framework needs all objects in the hierarchy to be immutable to be able to perform background layout so that's why everything needs to be recreated on a state update. Having granular state updates is not trivial, because a child state update could potentially change the parent in which case a further mutation is needed. @adityasharat is working on reconciliation between ComponentTrees when state updates are triggered, so progress is being made on this. Closing
