### ISSUE TITLE
Image Spec can not show picture in the following situation

### ISSUE THREAD

**Issue by xSharkM** [facebook/litho#415]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version

 // Litho
    implementation 'com.facebook.litho:litho-core:0.18.0'
    implementation 'com.facebook.litho:litho-widget:0.18.0'
    compileOnly 'com.facebook.litho:litho-annotations:0.18.0'

    annotationProcessor 'com.facebook.litho:litho-processor:0.18.0'

    // SoLoader
    implementation 'com.facebook.soloader:soloader:0.5.1'

    // For integration with Fresco
    implementation 'com.facebook.litho:litho-fresco:0.18.0'

    // For testing
    testImplementation 'com.facebook.litho:litho-testing:0.18.0'

    implementation 'com.facebook.litho:litho-sections-core:0.18.0'
    implementation 'com.facebook.litho:litho-sections-widget:0.18.0'
    compileOnly 'com.facebook.litho:litho-sections-annotations:0.18.0'

    annotationProcessor 'com.facebook.litho:litho-sections-processor:0.18.0'

## Issues and Steps to Reproduce

when Image Component roll out to invisible ,then roll back , image component can not display picture.

<img src="https://ws3.sinaimg.cn/large/006tNbRwgy1fu6vba5xiej30ku10ewgh.jpg" width="50%" height="50%" />

___

<img src="https://ws3.sinaimg.cn/large/006tNbRwgy1fu6vh51l2wj30ke10gdgf.jpg" width="50%" height="50%" />

the following is my GroupSectionSpec

	@GroupSectionSpec
	public class ListSectionSpec {
	
	  @OnCreateChildren
	  static Children onCreateChildren(final SectionContext c) {
	    Children.Builder builder = Children.create();

    for (int i = 0; i < 10; i++) {

      if (i == 3) {
        builder.child(SingleComponentSection.create(c).key("3")
            .component(Column.create(c)
                .child(Column.create(c)
                    .heightPx(300)
                    .clipToOutline(true)
                    .child(Column.create(c)
                        .heightPx(1000)
                        .flexShrink(0f)
                        .child(Image.create(c)
                            .scaleType(ScaleType.FIT_XY)
                            .drawableRes(R.drawable.testing)))
                    .marginDip(YogaEdge.BOTTOM, 100))));

      } else {
        builder.child(SingleComponentSection.create(c)
            .key(String.valueOf(i))
            .component(ListItem.create(c)));
      }
    }
    return builder.build(); 
    }}

## Expected Behavior
 image Component display picture.

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by muraziz** [comment]
This particular usecase is not supported by Litho as for incremental mount to work correctly we need to have child bounds to be smaller or equal to the parent bounds (which isn't the case here). It would work `clipToOutline` wasn't specified, but that property wasn't designed to be used just to stretch image bounds outside its parent but was used for shadows (in which case the current behavior makes sense). I would suggest to reconsider the current layout in such a way to make sure no child bounds becoming bigger than parent.

Thanks!
