### ISSUE TITLE
Build failed can't print error log when component's count more than 100

### ISSUE THREAD

**Issue by wt1098078873** [facebook/litho#420]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
```
    // Litho
    implementation 'com.facebook.litho:litho-core:0.17.0'
    implementation 'com.facebook.litho:litho-widget:0.17.0'
    compileOnly 'com.facebook.litho:litho-annotations:0.17.0'
    annotationProcessor 'com.facebook.litho:litho-processor:0.17.0'
    // SoLoader
    implementation 'com.facebook.soloader:soloader:0.3.0'
    // For integration with Fresco
    implementation('com.facebook.litho:litho-fresco:0.17.0') {
        exclude group: 'com.facebook.fresco'
    }
    // For testing
    testImplementation 'com.facebook.litho:litho-testing:0.17.0'
    // Sections
    implementation 'com.facebook.litho:litho-sections-core:0.17.0'
    implementation 'com.facebook.litho:litho-sections-widget:0.17.0'
    compileOnly 'com.facebook.litho:litho-sections-annotations:0.17.0'
    annotationProcessor 'com.facebook.litho:litho-sections-processor:0.17.0'
```
## Issues and Steps to Reproduce

![image](https://user-images.githubusercontent.com/5964735/44379713-d2040d80-a539-11e8-8d64-bbda8ee1344c.png)

![image](https://user-images.githubusercontent.com/5964735/44379642-87829100-a539-11e8-8ab5-db110fd0f07c.png)

## Expected Behavior

Build failed can print error log anytime.

**Comment by pavlospt** [comment]
@wt1098078873 what do you mean by "component's count" ?

**Comment by passy** [comment]
I don't understand the issue either, but I would not be surprised if this is related to unicode issues. We haven't been very careful in our String treatment in various places in the annotation processor.

**Comment by wt1098078873** [comment]
@passy "component's count" meas "The number of component in my project".  Can't print litho's error message when the number exceeds 100.

**Comment by passy** [comment]
But the compiler error looks pretty legitimate to me regarding "param must be annotated with ...". There's definitely no limit for the number of components anywhere.

**Comment by pavlospt** [comment]
@wt1098078873 There is a chance that you capped the javac error output. check this issue and give a try on the proposed solutions https://github.com/google/dagger/issues/306

**Comment by wt1098078873** [comment]
@pavlospt  It work for me. thanks.  👍
