### ISSUE TITLE
How to play video?

### ISSUE THREAD

**Issue by shiv71** [facebook/litho#424]
There are not example for video play using litho. We want a example like facebook timeline with video play.
Can you share any link or suggestion.

Thank.

**Comment by passy** [comment]
As I said in #425, this is not a good place for answering general questions. Check out [MountSpecs](https://fblitho.com/docs/mount-specs) as a way of using regular views inside Litho. If you need more information, I recommend you ask on StackOverflow.

**Comment by namdevlondhe** [comment]
@passy I am also facing the same issue to add video player in litho like exoplayer or any other player to improve scroll performance. I have asked question for the same on StackOverflow [VideoInLitho](https://stackoverflow.com/questions/56449392/how-to-add-exoplayer-in-facebook-litho-for-android). Can you please suggest me the solution or any example?
