### ISSUE TITLE
Litho plus XML

### ISSUE THREAD

**Issue by shiv71** [facebook/litho#425]
Can we use litho component with android xml.

**Comment by passy** [comment]
Could you please provide more context about what you're trying to do? Also, this is an issue tracker and not a good forum for open-ended questions. If you want to get general assistance, I'd recommend you ask on StackOverflow with the litho tag. Thanks!

**Comment by shiv71** [comment]
How to use Facebook litho component with android xml. We already create news feed page in android with recycleview and we want to use facebook litho library for add video in news feed to use litho feature like auto play , auto stop and smooth scrooling and video prepare before post coming on screen etc.
