### ISSUE TITLE
@MountSpec class issue

### ISSUE THREAD

**Issue by shiv71** [facebook/litho#429]
`@MountSpec
public class CounterButtonSpec {

    @OnCreateMountContent
    static Button onCreateMountContent(Context c) {
        return new Button(c);
    }

    @OnPrepare
    static void onPrepare( ComponentContext context){
        dumym();
       // onCreateMountContent(context);
    }

    private static void dumym() {
    }

    @OnMount
    static void onMount(
            ComponentContext c, Button button) {
        button.setText("Counter");
    }

}`

**Comment by shiv71** [comment]
In my above class only onPrepare method is call not any other method call.
onCreateMountContent method not calling

**Comment by mishrabhilash** [comment]
Either provide `width` and `height` props wherever you are using this component or override `onMeasure()` in this class.

Here `onCreateMountContent` is not getting called because your component has 0 width and 0 height.

**Comment by mihaelao** [comment]
@shiv71 did @mishrabhilash 's suggestion help? Can we close this?
