### ISSUE TITLE
EventTrigger usage problem

### ISSUE THREAD

**Issue by xSharkM** [facebook/litho#444]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
annotationProcessor 'com.facebook.litho:litho-processor:0.18.0'

// SoLoader
implementation 'com.facebook.soloader:soloader:0.5.1'

// For integration with Fresco
implementation 'com.facebook.litho:litho-fresco:0.18.0'

// For testing
testImplementation 'com.facebook.litho:litho-testing:0.18.0'

implementation 'com.facebook.litho:litho-sections-core:0.18.0'
implementation 'com.facebook.litho:litho-sections-widget:0.18.0'
compileOnly 'com.facebook.litho:litho-sections-annotations:0.18.0'

annotationProcessor 'com.facebook.litho:litho-sections-processor:0.18.0'

## Issues and Steps to Reproduce
I use litho widget EditText component ,when this component visible, i need auto show keyboard.
	Here is my code.
	
	  @LayoutSpec
	   public class InputBoxComponentSpec {
	
	@OnCreateLayout
	  static Component onCreateLayout(ComponentContext c) {
	    return Column.create(c).child(com.facebook.litho.widget.EditText.create(c)
	        .marginDip(YogaEdge.HORIZONTAL, 15)
	        .textSizeDip(14)
	        .textColor(Color.RED)
	        .hintColor(Color.GRAY)
	        .heightDip(30)
	        .gravity(Gravity.CENTER_VERTICAL)
	        .backgroundColor(Color.TRANSPARENT)
	        .inputType(InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS)
	        .flexGrow(1f)
	        .flexShrink(1f)
	        .isSingleLine(true)
	        .editable(true)
	        .requestFocus(true)
	        .imeOptions(EditorInfo.IME_ACTION_SEARCH )
	        .paddingPx(YogaEdge.ALL,0)
	        .textChangedEventHandler(InputBoxComponent.onTextChangeEventHandler(c))
	        .visibleHandler(InputBoxComponent.onVisibleEventHandler(c))
	        .hint("Testing data"))
	        .build();
	  }
	
	
	  @OnEvent(VisibleEvent.class)
	  static void onVisibleEventHandler(ComponentContext c) {
	    // TODO: 2018/10/12  request show keyboard 
	  }
	}

onVisibleEventHandler method I need request show keyboard, then I read EditTextSpec.java code,I find  should use EventTrigger to dispatch RequestFocusEvent, then EditTextSpec will receive event according to @OnTrigger annotation. But how to assign EventTrigger.EventTrigger field
EventTriggerTarget here must EditText component.I found that the document did not find the  sample of the EventTrigger.

## Expected Behavior

when InputBoxComponent visible ,auto show keyboard.

**Comment by topwu** [comment]
Hi, I think you have to assign a key when creating the EditText, and then use the key to trigger requestFocus().

```java
@OnCreateLayout
static Component onCreateLayout(ComponentContext c) {
    return Column.create(c).child(
        EditText.create(c).key("editTextKey")...
    ).build();

@OnEvent(VisibleEvent.class)
static void onVisibleEventHandler(ComponentContext c) {
    EditText.requestFocus(c, "editTextKey");
}
```

**Comment by xSharkM** [comment]
@topwu Thank you for your answer. Through your answer, I also know the usage of the ontrigger.
