### ISSUE TITLE
Support targetSDK 28 - Remove Dark Greylist Usage

### ISSUE THREAD

**Issue by kurtisnelson** [facebook/litho#460]
When we run veridex over our app, we see 4 API usages that are on the dark greylist and will cause crashes if used while targeting 28. These usages should be switched to use official APIs.

#9158: Linking dark greylist Landroid/view/RenderNodeAnimator;->ALPHA:I use(s):
Lcom/facebook/litho/animation/RenderThreadTransition;->getRenderNodeAnimatorProperty(Lcom/facebook/litho/animation/AnimatedProperty;)I

#9159: Linking dark greylist Landroid/view/RenderNodeAnimator;->ROTATION:I use(s):
Lcom/facebook/litho/animation/RenderThreadTransition;->getRenderNodeAnimatorProperty(Lcom/facebook/litho/animation/AnimatedProperty;)I

#9160: Linking dark greylist Landroid/view/RenderNodeAnimator;->X:I use(s):
Lcom/facebook/litho/animation/RenderThreadTransition;->getRenderNodeAnimatorProperty(Lcom/facebook/litho/animation/AnimatedProperty;)I

#9161: Linking dark greylist Landroid/view/RenderNodeAnimator;->Y:I use(s):
Lcom/facebook/litho/animation/RenderThreadTransition;->getRenderNodeAnimatorProperty(Lcom/facebook/litho/animation/AnimatedProperty;)I

**Comment by astreet** [comment]
Thanks for the report :) We're working with Google to try to get these APIs whitelisted (or for them to provide alternate APIs). AFAIUI, these should only cause runtime crashes if used, and this code will only be run if you specifically use a render thread transition (`Transition.renderThread`)

**Comment by ex3ndr** [comment]
Is there any news about your collaboration with google? We are using same APIs and we are unable to target 28 sdk too.

**Comment by astreet** [comment]
This should be fixed now, re: https://github.com/facebook/litho/commit/7b6dd499c468e8b22e289809f585642d94cfb66e. All hidden API usages have been removed -- let us know if you still have a problem after rebasing past this commit. Thanks!

**Comment by ex3ndr** [comment]
@astreet does this mean that render thread animations are disabled? What's the reason?

**Comment by astreet** [comment]
It means our custom render thread exposing is removed, yes -- reason being this was never really supported by google and prone to weird crashes :(

**Comment by astreet** [comment]
(and also issues with people getting greylist/blacklist errors of course -- it didn't seem worth it to keep)
