### ISSUE TITLE
Support targetSDK 28 - cashing on app launch

### ISSUE THREAD

**Issue by cezium** [facebook/litho#469]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
    // Litho
    implementation 'com.facebook.litho:litho-core:0.22.0'
    implementation 'com.facebook.litho:litho-widget:0.22.0'
    compileOnly 'com.facebook.litho:litho-annotations:0.22.0'

    kapt 'com.facebook.litho:litho-processor:0.22.0'

    // SoLoader
    implementation 'com.facebook.soloader:soloader:0.5.1'

    // For testing
    testImplementation 'com.facebook.litho:litho-testing:0.22.0'

## Issues and Steps to Reproduce
Build and run on api level 28

## Expected Behavior
Not crashing

[stacktrace.txt](https://github.com/facebook/litho/files/2690515/stacktrace.txt)

**Comment by cezium** [comment]
it works fine with 0.21.0

**Comment by passy** [comment]
cc @sergeynv

**Comment by wooyukit** [comment]
I also get crash issue on my google pixel 3 XL device with android 9 version. Other android version is fine. Please check it. Thanks

**Comment by krokyze** [comment]
Having the same issues only on Android 9.0 and Litho version 0.20.0. I don't know how it could be related but after testing out it looks like this is somehow Android Studio 3.3 problem because after checking out commit which was previously completely working now has all these issues.

**Comment by abdyer** [comment]
@cezium Please add part of the error message to the title and/or include a portion of the stack trace in the description to save others some time. I almost opened a duplicate issue for this because `stacktrace.txt` is not searchable.

**Comment by MichaelRocks** [comment]
Litho started calling `RenderNode`'s  `setTranslationX(F)Z` and `setTranslationY(F)Z` methods in [c16a40c3d6](https://github.com/facebook/litho/commit/c16a40c3d6216f03a269079c5c2f356c8a3b2919). And it seems these methods are blacklisted when targeting Android P. At least I can't see them via reflection.

**Comment by KrestM** [comment]
I have the same issue.

**Comment by FincherFincher** [comment]
Any news about that problem?

**Comment by nsk-mironov** [comment]
FYI: The issue was fixed in [v0.25.0](https://github.com/facebook/litho/releases/tag/v0.25.0) release.

**Comment by colriot** [comment]
Fixed in de3097b
