### ISSUE TITLE
How to use material design with Litho?

### ISSUE THREAD

**Issue by nikhilag** [facebook/litho#470]
I am new to Litho and I was wondering if we need to create all views from scratch or is it possible to leverage the existing material components available in Android? Won't it be way too time consuming to build everything from scratch such as the app bar, buttons, etc.?

**Comment by wooyukit** [comment]
You can use mountSpec to create the litho view for those widgets.
For App bar, I suggest you could use conventional xml approach to do so. For the rest part of the page, you may use litho view to do the layout.
