### ISSUE TITLE
RecyclerCollectionComponent fullscreen

### ISSUE THREAD

**Issue by Reedyuk** [facebook/litho#471]
## Issues and Steps to Reproduce
I have a recycler collection component, how do i get the elements in the sections to be full screen cards and allow horizontal scroll of them?

`RecyclerCollectionComponent.create(c)
            .recyclerConfiguration(
                ListRecyclerConfiguration.create()
                    .orientation(LinearLayoutManager.HORIZONTAL)
                    .snapMode(0)
                    .build()
            )
            .section(
                DataDiffSection.create<DiscoverListDataModel>(SectionContext(c))
                    .data(dataModels)
                    .renderEventHandler(DiscoverListComponent.onRender(c))
                    .onCheckIsSameItemEventHandler(DiscoverListComponent.isSameItem(c))
                    .onCheckIsSameContentEventHandler(DiscoverListComponent.isSameContent(c))
                    .build()
            )
            .canMeasureRecycler(true)
            .disablePTR(true)
            .build()`

**Comment by Reedyuk** [comment]
I guess i could just use a view pager and include the spec within this without the recycler but wondered if it was possible to use the recycler.

**Comment by wooyukit** [comment]
You can pass the screen height as a prop to your horizontal recyclercollectioncomponent height for the card view
