### ISSUE TITLE
LithoActivityTestRule does not support AndroidX support libraries

### ISSUE THREAD

**Issue by samueljseay** [facebook/litho#477]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
androidTestImplementation "com.facebook.litho:litho-espresso:0.21.0"

(I'm stuck on 21.0 because of #469 - but this is not related to 0.21.0 version)

## Issues and Steps to Reproduce
1. Use the AndroidX support libraries in instrumentation tests
2. Use the Litho Espresso activity rule
3. Throws exception `java.lang.IllegalStateException: No instrumentation registered! Must run under a registering instrumentation.`

## Expected Behavior
There would be no exceptions or errors

## Link to Code
https://gist.github.com/samueljseay/c59179c1321fcc80c2c1f34793a573f4

I believe the fix would be as simple as providing another rule class that extends the Android x ActivityRule.

**Comment by colriot** [comment]
Fixed in [v0.25.0](https://github.com/facebook/litho/releases/tag/v0.25.0) by de3097b
