### ISSUE TITLE
Support for incremental annotation processing in Gradle

### ISSUE THREAD

**Issue by harliedharma** [facebook/litho#482]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

Gradle supports incremental annotation processing since version 4.7 to speed up compilation process. 
For details see:
https://docs.gradle.org/nightly/userguide/java_plugin.html#sec:incremental_annotation_processing

https://github.com/gradle/gradle/issues/5277

Litho currently doesn't support incremental annotation processing. AFAIK, by default, it will make Gradle disable incremental annotation processing for the entire module. It will be great if Litho enable this feature as Litho heavily depends on annotation processing.

**Comment by pavlospt** [comment]
I can take a look at this and give it a try!

**Comment by pavlospt** [comment]
@harliedharma the PR for incremental annotation processing has been merged! You can close this :)

**Comment by karandeep-swiggy** [comment]
I am on the latest version(0.33.0) and I am still getting this error:
`Incremental annotation processing requested, but support is disabled because the following processors are not incremental: com.facebook.litho.specmodels.processor.testing.ComponentsTestingProcessor (NON_INCREMENTAL)`
