### ISSUE TITLE
Remove references to Powermock in litho-testing

### ISSUE THREAD

**Issue by TimvdLippe** [facebook/litho#490]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

We are using litho for our view tests, but we would like to remove our usages of Powermock. The `litho-testing` package that we use has several reference to 1 class in Powermock: `Whitebox`.

Since this is only 1 class, it is quite easy to have a local replacement with just the functions that `litho-testing` needs. [This gist](https://gist.github.com/TimvdLippe/1635f0f1606dca14d6c91d43ec30fac3) contains the required local copy of Whitebox that we already succesfully used internally. However, we would like to make this change upstream as well.

Would you consider remove these few references to Powermock in `litho-testing` with the local replacement implementation in `com.facebook.litho`?

**Comment by passy** [comment]
Sounds good to me! Could you perhaps put it all in `com.facebook.litho.testing` instead of the root namespace?

**Comment by TimvdLippe** [comment]
I initially wanted to open a PR, but saw that I had to sign a CLA. Moreover, I was not able to build the project as I don't have BUCK installed on my machine. Therefore, I opened an issue first.

Since you are positive regarding the change and it is problematic for me to make the change, would you mind making the change as well?

**Comment by passy** [comment]
I won't have time to do this myself anytime soon, so if you could turn this into a PR, that would be fantastic. And don't worry about the BUCK side of things. I'm happy to take care of that.
