### ISSUE TITLE
Please bundle yoga with different package name for React Native compatiliby

### ISSUE THREAD

**Issue by ex3ndr** [facebook/litho#522]
Starting from last RN release there are some huge internal inconsistency in Yoga layer between java version (from maven) and the one from RN itself. I have tried most of recent version of Litho and nothing works with latest releases of React Native. Previous release of RN works just fine.

While that could be a problem on RN side, but RN team have a record ignoring even more important problems and now there are only hope on Litho ream 🙏

Thanks!

**Comment by colriot** [comment]
We actually don't bundle Yoga with Litho. We depend on a maven/bintray dependency provided as usual.

The thing is that you may get a collision not only on Java API level, but also on a ntive libs level. So, even if they repackage Yoga with jarjra, for example, native Yoga libs will be different as well and will probably collide.

Looks like the one and proper thing here if for them to depend on latest release versions of Yoga.

Can you link RN issue for that here, please? I'll try to highlight it internally.

**Comment by xfumihiro** [comment]
@colriot @ex3ndr 
https://github.com/facebook/react-native/issues/24459

It seems like RN is depend on latest Yoga c++ version (based on the [comment](https://github.com/facebook/react-native/issues/24459#issuecomment-483940027) & RN source code) but Litho is depend on [1.16 Yoga java version](https://github.com/facebook/litho/blob/34b6dfdf8f30f69ba47fbc677cfb8a959f7eb0de/build.gradle#L117)

so there's no way to safely use Litho with RN?
