### ISSUE TITLE
TextSpec doesn't support text selectable

### ISSUE THREAD

**Issue by wooyukit** [facebook/litho#533]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.25.0

## Issues and Steps to Reproduce
Cannot long press the text spec component to highlight the text

## Expected Behavior
Should be selectable for sharing or dictionary

**Comment by muraziz** [comment]
TextSpec uses TextDrawable under the hood and unfortunately that's not easy to add. In vanilla android TextView it relies on Editor object which encapsulates fully editing capability which we don't: http://androidxref.com/9.0.0_r3/xref/frameworks/base/core/java/android/widget/TextView.java#6981.
One possible workaround could be to use EditTextSpec (that mounts android.view.EditText) and adjust styles (like remove bg, disable editing, etc.) to make it look like textview.
Or another workaround could be to add some sort of 'Copy to clipboard' button next to text.

**Comment by wooyukit** [comment]
Thanks for you reply. Because our users wanna to use dictionary to check the word or phrase meaning, I prefer to use EditTextSpec and disable editing. I wonder if it will affect the performance or not.

**Comment by muraziz** [comment]
@wooyukit yeah, it depends. If you have a lot of of them in scrolling surface, it may affect, but you can do some systracing to see how expensive it is.

**Comment by wooyukit** [comment]
@muraziz Finally, I used MountSpec to create a TextViewComponentSpec to wrap native TextView to enable the textIsSelectable property

**Comment by muraziz** [comment]
@wooyukit Nice, yeah, that's almost same as using EditText as MountSpec with all editing capabilities turned off. Glad that it worked for you :)
