### ISSUE TITLE
Usages of YogaConstants.UNDEFINED are replaced with instead of 1.0E21F after compilation.

### ISSUE THREAD

**Issue by ex3ndr** [facebook/litho#536]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.23

## Issues and Steps to Reproduce

In compiled library all usages of YogaConstants.UNDEFINED are replaced with with `1.0E21F` and this breaks runtime since YogaConstants.isUndefined(...) stops working at all. Because of this fblitho is incompatible with latest react-native.

![image](https://user-images.githubusercontent.com/400659/56156239-7bb27600-5fc5-11e9-817f-b67e93384dc7.png)

**Comment by adityasharat** [comment]
Thank you reporting this. We'll look into this.

**Comment by colriot** [comment]
@ex3ndr this will be fixed in the new version. We'll release it next week

**Comment by colriot** [comment]
Fixed in [v0.26.0](https://github.com/facebook/litho/releases/tag/v0.26.0)
