### ISSUE TITLE
Options for setting SectionsDebug.ENABLED = true

### ISSUE THREAD

**Issue by abdyer** [facebook/litho#544]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
I'm trying to build Litho from source after modifying the final `SectionsDebug.ENABLED` flag to troubleshoot a `RecyclerCollectionComponent` diffing issue in our app.
* Should I use Buck or Gradle?
* Do I need to build all dependencies or just `litho-widget` (where `SectionsDebug` is located)?
* What is the recommended way to add the modified dependency to my project?
* Is there another way to do this? I also tried various reflection based approaches but was unsuccessful.

**Comment by passy** [comment]
Hey @abdyer, the best way for doing this will depend on your existing build infrastructure. If it's a buck/bzl-compatible system, I'd depend on the changed module; if it's Gradle, I'd integrate litho-widget as sub-project; if the lowest common denominator is Maven dependency resolution, I'd `gradle install` everything to a local m2 repository and point the build system to that for getting Litho.

**Comment by abdyer** [comment]
Thanks for the info! Closing the issue.
