### ISSUE TITLE
Can I use services in layout specs?

### ISSUE THREAD

**Issue by AhmedMKamal** [facebook/litho#546]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
```
val lithoVersion: String by project // 0.25.0

dependencies {
    ...
    implementation("com.facebook.litho:litho-core:$lithoVersion")
    implementation("com.facebook.litho:litho-widget:$lithoVersion")
    implementation("com.facebook.soloader:soloader:0.6.0")
    implementation("com.facebook.litho:litho-fresco:$lithoVersion")
    implementation("com.facebook.litho:litho-sections-core:$lithoVersion")
    implementation("com.facebook.litho:litho-sections-widget:$lithoVersion")
    compileOnly("com.facebook.litho:litho-annotations:$lithoVersion")
    compileOnly("com.facebook.litho:litho-sections-annotations:$lithoVersion")
    kapt("com.facebook.litho:litho-processor:$lithoVersion")
    kapt("com.facebook.litho:litho-sections-processor:$lithoVersion")
}
```

## Issues and Steps to Reproduce
Services annotations exist only in sections but not in layout specs.

## Expected Behavior
I don't know actually if that is the expected behavior!!

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

Side question, Can I use Litho to build my entire UI or you are focus only on lists and scroll views?

**Comment by marco-cova** [comment]
Hi @AhmedMKamal, Services are a "Section only" concept. Therefore, you can only use them within Sections. LayoutSpecs are only used to declare your UI and not to control/fetch/update your data model. That should be done somewhere externally of your UI definition.
