### ISSUE TITLE
Question : How to set error text for TextInput

### ISSUE THREAD

**Issue by amoikevin** [facebook/litho#550]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.26.1

**Comment by colriot** [comment]
There currently is no support for `setError` in TextInput. You may add a PR for that or rename this issue to make a feature request

**Comment by colriot** [comment]
Feel free to create a PR or a Feature Request if it will be needed. For now, I'm closing this question as answered.
