### ISSUE TITLE
Support for Component Redraw/Update Event

### ISSUE THREAD

**Issue by ComethTheNerd** [facebook/litho#555]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

How might one hook into an event fired every time a component update is (re)rendered/flushed to the screen? 

The hook I was ideally looking for would be scoped to a particular component, rather than a global update event. For example, 'fire this callback whenever this instance of the Foo component is redrawn'

**Comment by topwu** [comment]
Does `(re)rendered/flushed` mean you create a new component or have a state update? If so, have you considered using [Visible Event](https://fblitho.com/docs/visibility-handling)? You can pass your callback as a prop and execute it when visible event is triggered.

**Comment by ComethTheNerd** [comment]
I did think about trying to combine events like that, but the reason I stipulated `flushed` is because if the component was already invisible and got updated but remained invisible then you would miss an event.

However, as an alternative.. if the `@OnCreateLayout` delegate is called each time regardless of the visibility, then maybe I could put the trigger in that function at the top, and that could be the signal? (In lieu of an actual fully fledge `onUpdate` event)

I'm not somewhere I can test that assumption right now, but feedback welcome

**Comment by topwu** [comment]
`@OnCreateLayout` might be called at same time on main/background threads. If you put your callback there, it might be triggered multiple times even there's only a flushed. Does it meet your requirement?

**Comment by ComethTheNerd** [comment]
Thank you for the prompt response. I think as long as the `@OnCreateLayout` delegate is called *every* time _something_ in the component has changed (regardless of the eventual visibility/measurements) then it could suffice.

...With the added caveat that I take care to make subscribers idempotent and unassuming about the thread they are executing on - which is probably desirable on both counts anyway.

I think that is a better idea than trying to dedup/compute a hash for a given update, and do the bookkeeping to avoid calling the event multiple times for a 'single flush'.

I will prototype (ab)using `@OnCreateLayout` and see if it works as expected.
