### ISSUE TITLE
[Question] How to use ItemDecoration in a Grid?

### ISSUE THREAD

**Issue by winterDroid** [facebook/litho#556]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.21.0

## Issues and Steps to Reproduce
Add an `ItemDecoration` that changes the `Rect` e.g. to show equal spacing between grid items.
Right now this just works in scroll direction since the item does not remeasure the non-scrolling direction.
I found `GridLayoutInfo#OVERRIDE_SIZE` which seems to be the "workaround". Do you have a sample or some guidance?

## Expected Behavior
Best would be if it works independently of any scroll direction.

**Comment by ironmanTony** [comment]
same problem.
```
Component component = RecyclerCollectionComponent.create(componentContext)
                .disablePTR(true)
                .eventsController(eventsController)
                .recyclerConfiguration(GridRecyclerConfiguration.create().numColumns(4).build())
```
and use itemDecoration, int getItemOffsets set rect, decoration not correct.

**Comment by muraziz** [comment]
Given that this issue was opened two years ago, closing it now as it might not be relevant any more due to changes in Litho code since then. But if this is still relevant please create a new PR.
