### ISSUE TITLE
FocusChangedEvent Is triggered all the time

### ISSUE THREAD

**Issue by aozaoz112233** [facebook/litho#558]
## Version
0.25.0

## Issues and Steps to Reproduce

I'm trying to write an android TV demo , Add FocusChangedEvent to ListItemSpec to change the item state .The demo is very simple, just changing ClickEvent from barebones(demo) . And found that the item in the RecyclerCollectionComponent state of hasFocus has been constantly changing . I find that the first item in the list keeps losing focus and getting it back. and TV remote control device hard to slide list . I checked the keyevent occurrence of the dispatchKeyEvent but nothing .

    2019-06-24 11:35:41.626 19560-19560/com.demo.lithodemo D/onFocusChanged: true
    2019-06-24 11:35:41.659 19560-19560/com.demo.lithodemo D/onFocusChanged: true
    2019-06-24 11:35:41.662 19560-19560/com.demo.lithodemo D/onFocusChanged: false
    2019-06-24 11:35:41.664 19560-19560/com.demo.lithodemo D/onFocusChanged: true
    2019-06-24 11:35:41.697 19560-19560/com.demo.lithodemo D/onFocusChanged: true
    2019-06-24 11:35:41.700 19560-19560/com.demo.lithodemo D/onFocusChanged: false
    2019-06-24 11:35:41.705 19560-19560/com.demo.lithodemo D/onFocusChanged: true
    2019-06-24 11:35:41.742 19560-19560/com.demo.lithodemo D/onFocusChanged: true
    2019-06-24 11:35:41.744 19560-19560/com.demo.lithodemo D/onFocusChanged: false

## Expected Behavior
FocusChangedEvent do not automatically trigger

## Link to Code

    @OnCreateLayout
    fun onCreateLayout(
            c: ComponentContext,
            @Prop color: Int,
            @Prop title: String,
            @Prop subtitle: String,
            @State isFocus: Boolean
    ): Component = Column.create(c)
            .paddingDip(ALL, 16f)
            .focusable(true)
            .clickHandler(ListItem.onFocusChanged(c))
            .backgroundColor(if (isFocus) Color.GRAY else Color.WHITE)
            .child(
                    Text.create(c)
                            .text(title)
                            .textSizeSp(40f))
            .child(
                    Text.create(c)
                            .text(subtitle)
                            .textSizeSp(20f))
            .build()

    @OnUpdateState
    fun bgColorChange(isFocus: StateValue<Boolean>) {
        isFocus.set(!isFocus.get()!!)
    }

    @OnEvent(FocusChangedEvent::class)
    fun onFocusChanged(c: ComponentContext, @FromEvent hasFocus:Boolean) {
        logd("onFocusChanged","$hasFocus")
        ListItem.bgColorChange(c)
    }

I try to find the cause of the problem in the ComponentFocusChangeListener and I find it strange that the view that triggers onFocusChange is different every time

    public void onFocusChange(View view, boolean b) {
            Log.d("FocusEvent", view.toString() + " hasFocus " + b);
            if (mEventHandler != null) {
              dispatchOnFocusChanged(mEventHandler, view, b);
        }
 }

view that triggers onFocusChange is different every time

    D/FocusEvent: litho.ListItem{937951f VFE..... .. 0,0-1920,170}
                        litho.Text{114206c V.E..... .. 24,24-1896,105}
                        litho.Text{6fae635 V.E..... .. 24,105-1896,146} hasFocus false
    D/FocusEvent: litho.ListItem{cf65aca VFE..... .. 0,170-1920,340}
                        litho.Text{6ca643b V.E..... .. 24,24-1896,105 text="Hello, world!"}
                        litho.Text{f58d758 V.E..... .. 24,105-1896,146 text="Litho tutorial"} hasFocus true
    D/FocusEvent: litho.ListItem{80b0b1 VFE..... .. 0,170-1920,340}
                        litho.Text{6875996 V.E..... .. 24,24-1896,105 text="Hello, world!"}
                        litho.Text{4f10917 V.E..... .. 24,105-1896,146 text="Litho tutorial"} hasFocus false

**Comment by Katalune** [comment]
A typical example of State usage is rendering a checkbox. The component renders different drawables for the checked and unchecked states. This means that updating the State also recreates a Component. https://fblitho.com/docs/state

Another thing I've noticed, clickHandler method expects handler for the `ClickEvent`, not `FocusChangedEvent`. Either change the method to focusChangeHandler or event class to `ClickEvent`.

**Comment by colriot** [comment]
Closing this now @aozaoz112233. If you have more questions, please reopen.
