### ISSUE TITLE
how to add a litho view into an Android native view ? eg  LinearLayout 

### ISSUE THREAD

**Issue by zs1973** [facebook/litho#562]

**Comment by wooyukit** [comment]
`val linearLayout = view.findViewById(R.id.fragment_linearlayout)`
`val c = ComponentContext(context)`
`linearLayout.addView(LithoView.create(c, (Your Component: for example) Column.create(c).build()))`

**Comment by colriot** [comment]
@zs1973 is that ^ what you were looking for?

**Comment by colriot** [comment]
@tuliopereirazup then you need to wrap this View in a `@MountSpec`. See [docs](https://fblitho.com/docs/mount-specs) and [ProgressBar](https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/ProgressSpec.java) example.

**Comment by niranjanneeru** [comment]
> `val linearLayout = view.findViewById(R.id.fragment_linearlayout)`
> `val c = ComponentContext(context)`
> `linearLayout.addView(LithoView.create(c, (Your Component: for example) Column.create(c).build()))`

How about adding a RecyclerCollectionComponent into a native android view?
