### ISSUE TITLE
How to support Drag/Drop of items in RecyclerCollectionComponent?

### ISSUE THREAD

**Issue by wooyukit** [facebook/litho#563]
I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

**Comment by topwu** [comment]
For my understanding, for now I don't think there is an easy way to support drag and drop in RecyclerCollectionComponent unfortunately.

**Comment by wooyukit** [comment]
Finally, I use conventional approach using native recycler and adapter to do so
