### ISSUE TITLE
ListItem unresolved reference

### ISSUE THREAD

**Issue by vinukn335** [facebook/litho#572]
- [] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
***Add the version of the litho packages you use. You can paste the dependency
section of the gradle file if you have one.***

## Issues and Steps to Reproduce
***Replace this with steps to repro your issue.***

## Expected Behavior
***Describe what you expected would happen.***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***
I am new to Litho,
When  I am trying to run some tutorial(ListItem) in Android Studio, I get ListeItem unresolved reference. But this works,
`        val component = Text.create(context)
            .text("Hello World")
           .textSizeDip(50f)
            .build()`

**Comment by marco-cova** [comment]
Hi @vinukn335, what tutorial are you referring to exactly?
Could you give me enough information to be able to repro your issue?

**Comment by colriot** [comment]
Hi @vinukn335 . I encourage you to check out [these Codelabs](https://github.com/facebook/litho/tree/master/codelabs) and if you'll still have questions, just reopen this issue or create a new one.
