### ISSUE TITLE
VerticalScrollSpec should also "only enable incremental mount if parent incremental mount is enabled"

### ISSUE THREAD

**Issue by yuntao** [facebook/litho#580]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
v0.26.0+

## Issues and Steps to Reproduce
Commit https://github.com/facebook/litho/commit/c88a6605d8e77378e0ac89b267dcb260daddc6f4 to "only enable incremental mount if parent incremental mount is enabled" is only applied to RecyclerBinder (and thus RecyclerCollectionComponentSpec). It would be good to apply the fix to VerticalScrollSpec too, as it also falls in the the category of a parent having children ComponentTrees. HorizontalScrollSpec hard-codes incremental mount to be disabled, thus its not affected.

## Expected Behavior
Extend the behavior of "only enable incremental mount if parent incremental mount is enabled" for VerticalScrollSpec.

## Link to Code
Commit https://github.com/facebook/litho/commit/c88a6605d8e77378e0ac89b267dcb260daddc6f4

**Comment by muraziz** [comment]
cc @astreet who has more context on that change

**Comment by astreet** [comment]
Hey, yes, I agree :) Btw, the implementation for this is changing soon (commit is landing now) -- it will now just check the incremental mount status on the parent componenttree directly.
