### ISSUE TITLE
Kotlin multi module support

### ISSUE THREAD

**Issue by steelahhh** [facebook/litho#584]
- [+] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.29.0

## Issues and Steps to Reproduce
When trying to add a component from a separate module, `Unresolved Reference: create` exception gets thrown. 
It works without any problem if component is written in Java.

Repro steps:
- Create LayoutSpec or MountSpec in a separate module
- Try adding it in the parent module

## Expected Behavior
Components created in a separate module are usable

## Link to Code
[Repository with a reproducible bug](https://github.com/steelahhh/LithoKotlinBug
)

**Comment by wooyukit** [comment]
I got the same issue. Finally, I use java for cross module components. Also, when I use Kotlin <List> for the component state, it doesn't work any more.

**Comment by colriot** [comment]
Hi @steelahhh. Thanks for reporting this! I think issue here comes from gradle. Will need to dig into it, but don't promise that it will be soon

**Comment by bangonkali** [comment]
I can reproduce this as well. Create components from a different module. Module with components builds successfully but can't be referenced from the main android application.

I did notice that only root components can't be referenced from main android application. So it seems you can have root components on the main android application module but the sub-components required by the root components can be in a separate module. This is what I'm doing, for now, to avoid being blocked.

See attached for a sample. 

[updating-ui.zip](https://github.com/facebook/litho/files/3865961/updating-ui.zip)

**Comment by colriot** [comment]
@steelahhh @bangonkali just to gather some more info in the meantime – do you have a different behavior in Java?

**Comment by steelahhh** [comment]
Seems like the issue is no longer present since the version 0.33.0. 
@bangonkali please confirm, if possible.

**Comment by bangonkali** [comment]
I will get back to this and report on status of fix.

**Comment by bangonkali** [comment]
The screenshot below is when using `litho_version = '0.26.1'`. It does not build.

![image](https://user-images.githubusercontent.com/539946/75345787-5fb37c80-58d8-11ea-8ce8-7185bbad745a.png)

After upgrading to `0.34.0`, it now builds and runs.

``` gradle
  // Litho
  implementation "com.facebook.litho:litho-core:0.34.0"
  implementation "com.facebook.litho:litho-widget:0.34.0"
```

![image](https://user-images.githubusercontent.com/539946/75346440-ac4b8780-58d9-11ea-9f1a-c37ca50aa836.png)

We do have a warning related to incremental builds.

I think we can close this now. I have attached the test project the same as above - only with the references updated to the latest versions I had of writing.

[updating-ui.zip](https://github.com/facebook/litho/files/4255766/updating-ui.zip)

**Comment by colriot** [comment]
I love self-closing issues! 
On the serious side, @bangonkali do you still have a question to be addressed? Incremental issue seems tied to Testing processor which should not be a big problem, I assume.

**Comment by bangonkali** [comment]
@colriot nothing else for now. 👍
