### ISSUE TITLE
RecyclerCollectionComponent items don't update when changed the states of it's SectionSpec

### ISSUE THREAD

**Issue by wooyukit** [facebook/litho#587]
I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.29

## Issues and Steps to Reproduce
Use event handler to update the state of SectionSpec. The list item won't update according to the state changes.

## Expected Behavior
The items of RecyclerCollectionComponent should be responded to the state change and update the layout.

**Comment by colriot** [comment]
Hi @wooyukit. This seems serious. Can you please provide a sample where we can validate this behaviour?

**Comment by wooyukit** [comment]
I just simply update section spec state of recyclercollectioncomponent for example @State fontSize in the android fragment. However, the cell items don't respond to the fontSize to update the text size. Do you want to have a sample project to reproduce this behaviour? I can create one for you

**Comment by colriot** [comment]
Taking in account current shortage of resources, it's better to have steps to reproduce, so any of my colleagues can jump in.
You can change `PlaygroundComponentSpec` in our `sample` project to have everything you need to reproduce this issue, and just post this spec's updated content here.

**Comment by wooyukit** [comment]
Noted. I will create a sample for you to reference

**Comment by colriot** [comment]
@wooyukit does everything work well now?

**Comment by ryanhoo** [comment]
@colriot I might have the same problem. I have a tab layout spec with a state(`selectedTab`) in order to change the tab item style(font size & color) when it's been selected. But it seems not working after I updated the state(`selectedTab`), onCreateLayout will be called as it should be, but onRender won't be called so the layout can't be updated.
```
@LayoutSpec
object TabLayoutComponentSpec {

    @PropDefault
    val defaultTab = 0

    @OnCreateInitialState
    fun onCreateInitialState(
        c: ComponentContext,
        @Prop(optional = true) defaultTab: Int,
        selectedTab: StateValue<Int>
    ) {
        selectedTab.set(defaultTab)
    }

    @OnCreateLayout
    fun onCreateLayout(
        c: ComponentContext,
        @State selectedTab: Int,
        @Prop tabs: List<Tab>,
        @Prop eventsController: RecyclerCollectionEventsController
    ): Component {
        val recyclerConfiguration =
            ListRecyclerConfiguration.create()
                .orientation(LinearLayoutManager.HORIZONTAL)
                .reverseLayout(false)
                .build()
        return RecyclerCollectionComponent.create(c)
            .recyclerConfiguration(recyclerConfiguration)
            .disablePTR(true)
            .section(
                DataDiffSection.create<Tab>(SectionContext(c))
                    .data(tabs)
                    .renderEventHandler(TabLayoutComponent.onRender(c, selectedTab))
                    .build()
            )
            .canMeasureRecycler(true)
            .eventsController(eventsController)
            .build()
    }

    @OnEvent(RenderEvent::class)
    fun onRender(
        c: ComponentContext,
        @Param currentSelectedTab: Int,
        @FromEvent model: Tab,
        @FromEvent index: Int
    ): RenderInfo {
        val isSelected = index == currentSelectedTab
        return ComponentRenderInfo.create()
            .component(
                Text.create(c)
                    .key("${model.id}_$isSelected")
                    .alignSelf(YogaAlign.CENTER)
                    .text(model.name)
                    .textSizeDip(if (isSelected) 18f else 16f)
                    .textColor(if (isSelected) Color.MAGENTA else Color.BLACK)
                    .paddingDip(YogaEdge.VERTICAL, 8f)
                    .paddingDip(YogaEdge.HORIZONTAL, 12f)
                    .clickHandler(TabLayoutComponent.onTabItemSelected(c, index))
                    .build()
            )
            .build()
    }

    @OnUpdateState
    fun changeTab(selectedTab: StateValue<Int>, @Param newTab: Int) {
        selectedTab.set(newTab)
    }

    @OnEvent(ClickEvent::class)
    fun onTabItemSelected(
        c: ComponentContext,
        @Param selectedIndex: Int,
        @Prop eventsController: RecyclerCollectionEventsController
    ) {
        eventsController.setSnapMode(SnapUtil.SNAP_TO_CENTER)
        eventsController.requestScrollToPositionWithSnap(selectedIndex, true)
        // update selected tab status
        TabLayoutComponent.changeTabSync(c, selectedIndex)
    }
}
```
Tab entity: `data class Tab(val id: Long, val name: String)`

**Comment by colriot** [comment]
@ryanhoo Hey! Yours is a different problems from the first glance. Thing is that `selectedTab` is part of the State only for `TabLayoutComponentSpec`, so that's why it's rerendered and its `onCreateLayout` is called. But its child `RecyclerCollectionComponent` and specifically its `DataDiffSection` don't know anything about `selectedTab`. Their input is only `tabs`, and they don't change. So, Spec being effectively a pure function thinks that if input didn't change, then the output won't change as well, and that's why `DataDiffSection` is not rerendered at all. This is a nice optimisation to not rerender specific children even if their parent has changed, but these changes don't affect specific children. 

So, my recommendation is to include selection flag in the Tab's data model

**Comment by ryanhoo** [comment]
@colriot Thanks for your reply. I managed to solve this issue by using `GroupSectionSpec` and recreate each tab in `onCreateChildren` with `SingleComponentSection`. The tab item selected respond properly and scroll position remain the same.

**Comment by colriot** [comment]
@ryanhoo this will mean that there will be no reuse, and tabs items will indeed be recreated on every collection update. But since we are talking about tabs, this should not hit hard on perf :)

**Comment by ryanhoo** [comment]
@colriot Yes indeed. But if I use DataDiffSection to create tabs, either the tabs won't show selected status properly or the scroll position gets reset to the beginning of the list.

**Comment by colriot** [comment]
@ryanhoo did you try three suggestion from the above? Does your data type has equals implemented? If you share the resulting code,I can look
