### ISSUE TITLE
Allow @Nullable on @Prop annotations.

### ISSUE THREAD

**Issue by jaceksur** [facebook/litho#597]
@Nullable is explicitly stripped from @Props in this commit:

https://github.com/facebook/litho/commit/b47a9f117dde8d039a741e64d45e783fa14c939a#diff-d9d52274880b4e0daff80cf43a53ae0e

But we'd like to be able to annotate arguments to prop setter methods in Builders to use static analysis tools effectively.

**Comment by colriot** [comment]
@jaceksur `@Nullable` is stripped only for primitive types, i.e. `int` resourceIds. And it's propagated for other types. So, you still can annotate them and use static analysis tools.

Closing this for now. But if I'm not getting the usecase, please, feel free to reopen the issue and add more examples.

**Comment by vinc3m1** [comment]
I don't think this is true of some List<BoxedPrimitive> types which are technically nullable, but are still generated with `parameterWithoutNullableAnnotation()`

https://github.com/facebook/litho/blob/7645bb73f7563b90776e6c4cb2db5ed9cb6043ee/litho-processor/src/main/java/com/facebook/litho/specmodels/generator/BuilderGenerator.java#L728-L731

**Comment by chggr** [comment]
I have put together https://github.com/facebook/litho/pull/744 to allow Nullable annotations for Lists.
Please have a look and let me know your thoughts.
