### ISSUE TITLE
Allow @Nullable on @Param arguments in event handler factories

### ISSUE THREAD

**Issue by jaceksur** [facebook/litho#598]
Annotating a @Param argument with @Nullable:

class MySpec {
  @OnEvent(TextChangedEvent.class)
  static void onTextChanged(
      ComponentContext c,
      @Param @Nullable CommandFuture onChange,
      @Param @Nullable CommandFuture onClear) {  
    // ...
  }
}

should result in a @Nullable argument in the generated event handler factory method.

This will allow the use static analysis tools effectively.

**Comment by colriot** [comment]
Fixed in dac6da0ff74f44a3d561f7d3e4f49fc7222d71f4
