### ISSUE TITLE
@PropDefault values don't have units, default text size is 13px

### ISSUE THREAD

**Issue by vinc3m1** [facebook/litho#599]
As discussed in person, TextSpec has a propdefault of 13, but this is interpreted as `px` instead of `sp`, so the default text side on hi dpi devices is very tiny.

https://github.com/facebook/litho/blob/edbcd2f12ff8ff2293844e31abf537bdbc1776ab/litho-widget/src/main/java/com/facebook/litho/widget/TextSpec.java#L191

`@PropDefault` annotation doesn't support specifying dimension units, which would be necessary to solve this problem.

**Comment by pavlospt** [comment]
@vinc3m1 `PropDefault` supports resource types, you can specify your own dimen with the proper size. https://github.com/facebook/litho/blob/master/litho-annotations/src/main/java/com/facebook/litho/annotations/PropDefault.java

**Comment by vinc3m1** [comment]
yes, technically I could make a new xml dimension that actually specified sp and point the @PropDefault at it, but that seems like a very awkward API requirement. Plus the fact that the core TextSpec is suffering from this bug is a sign that we should probably try to support it no?

**Comment by vinc3m1** [comment]
Also worth noting that even a dimension type @Prop generates builder methods for different units, not requiring xml. So it’s pretty awkward to not support that for @PropDefaults.

**Comment by astreet** [comment]
This was fixed specifically for TextSpec in https://github.com/facebook/litho/commit/a8b8014c820c2af6889b157a4142fb8404850be9 -- this is a pattern that should be applicable elsewhere as well :)
