### ISSUE TITLE
backgroundRes ContextCompat.getDrawable  ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Tobyyyyyyyyyy** [facebook/litho#600]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
`litho_version = '0.23.0'`

## Issues and Steps to Reproduce
[Logcat](https://gist.github.com/Tobyyyyyyyyyy/7c8711db35eb811e3957bf157ac8b470)

![image](https://user-images.githubusercontent.com/5964735/65762984-e6f79b00-e154-11e9-841f-021245af6ff6.png)

## Expected Behavior
No crash.
## Link to Code
![image](https://user-images.githubusercontent.com/5964735/65762561-e6aad000-e153-11e9-9ced-80b6b650af6d.png)
![image](https://user-images.githubusercontent.com/5964735/65762578-f1fdfb80-e153-11e9-8f1e-0d345706c34c.png)

**Comment by astreet** [comment]
Unfortunately it looks like the MIUI implementation of MiuiResources is not thread safe. A solution might be to synchronize when loading resources, but only for MIUI phones since this would not be necessary elsewhere afaik.
