### ISSUE TITLE
Fix lint warnings and reenable abortOnError

### ISSUE THREAD

**Issue by passy** [facebook/litho#62]
Lint doesn't have the highest opinion of us at the moment and we had to disable `abortOnError` as a consequence. Some of the issues are just noise, others are signal.

We should suppress those that we're okay with in code and fix the ones we're not.

This is a good task for new contributors.

**Comment by pavlospt** [comment]
@passy Is there a list of those, that you are ok with? 

I mean there are lint errors like: 
* `view.setForeground(null);`  that are safe-guarded with an API check before accessing them, although Lint does not understand it. One solution could be to reverse the API check and run that method only then, that would satisfy the Lint I suppose.

**Comment by passy** [comment]
@pavlospt That sounds pretty reasonable.

We don't have a list right now. I think it might be best to tackle these in a few individual PRs. There may be some that are a bit more invasive and require some thought but a bunch of them are probably just missing annotations or places where we could use `@SuppressLint` if it's clear that Lint is overly sensitive.

**Comment by pavlospt** [comment]
Ok I understand what you mean. Will try to create a PR covering most of them so that we can discuss what is acceptable and should be suppressed and what not :)

**Comment by passy** [comment]
@pavlospt Awesome!

![](https://media3.giphy.com/media/dudcZA9e14HIY/giphy.gif)

**Comment by pavlospt** [comment]
If this one is still relevant I think I can prepare the PR I said some time ago 😂

**Comment by passy** [comment]
Oh yeah, that would be awesome. Would love to get rid of some more lint warnings. :)

**Comment by pavlospt** [comment]
A nice alternative to this would be using a Lint baseline file and fix issues in parallel!

**Comment by colriot** [comment]
Hey @pavlospt ! Were there any progress about that? I think we may enable Lint baseline for this config and switch `abortOnError` on again
