### ISSUE TITLE
annotated @GroupSectionSpec ListSectionSpec not generating ListSection file

### ISSUE THREAD

**Issue by mntramos** [facebook/litho#637]
I'm still currently following the tutorial and I can't get past the ListSectionSpec.

@GroupSectionSpec
object ListSectionSpec {

    @OnCreateChildren
    fun onCreateChildren(c: SectionContext): Children {
        val builder: Children.Builder = Children.create()

        for (i in 1..32) {
            builder.child(
                SingleComponentSection.create(c)
                    .key(i.toString())
                    .component(ListItem.create(c).build())
            )
        }

        return builder.build()
    }
}

**Comment by colriot** [comment]
@mntramos can you state your problem? What exactly doesn't work?

**Comment by astreet** [comment]
If you are still having an issue here, make sure you have the lines

```
kapt project(':litho-processor')
kapt project(':litho-sections-processor')
```

in the `dependencies` of your build.gradle file. See [the sample-kotlin build.gradle](https://github.com/facebook/litho/blob/master/sample-kotlin/build.gradle) for an example.
