### ISSUE TITLE
No colorAccent method in TextInput

### ISSUE THREAD

**Issue by Startcev** [facebook/litho#639]
- I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.34.0

## Issues and Steps to Reproduce
There is no way to set colorAccent in TextInput parameters.

## Expected Behavior
There are three new methods for setting colorAccent:
accentRes, accentAttr, accentColor

**Comment by astreet** [comment]
We would accept a PR on this

**Comment by astreet** [comment]
A PR to fix this would add it as a prop and in @OnLoadStyle of TextInputSpec
