### ISSUE TITLE
[How to] make RecyclerCollectionComponent remember it's scroll-position

### ISSUE THREAD

**Issue by amoikevin** [facebook/litho#641]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.34.0

## Issues and Steps to Reproduce
Per-title, after resetting lithoview's component tree, a recyclerCollectionComponent scroll to zero point. 
Or, how can I set the initial scroll-position of the recyclerCollectionComponent ?

## Expected Behavior
A RecyclerCollectionComponent can scroll to previous position after resetting lithoview's componenttree.

**Comment by nicous** [comment]
Hey, have a look at this: https://fblitho.com/docs/communicating-with-the-ui#scrolling-requestfocus

**Comment by amoikevin** [comment]
I get it, thanks.
