### ISSUE TITLE
[How to] totally disable nested-scroll of recyclercollectioncomponent?

### ISSUE THREAD

**Issue by amoikevin** [facebook/litho#642]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.34.0

## Issues and Steps to Reproduce
user case:
I want to use lithoview in smartrefreshlayout (https://github.com/scwang90/SmartRefreshLayout) as the content view of it. 
But the scroll behavior does NOT work properly, because SRL can't detect the scroll-edge of LithoView (related methods of lithoview like 'canScrollVertically' returns wrong result ).

## Expected Behavior
lithoview can disable nested-scroll of recyclercollectioncomponent, or provide apis to detect the scroll-edge of it.

## Link to Code
view structure:

smartrefreshlayout{
    lithoview{
        recyclercollectioncomponent...
    }
}

**Comment by nicous** [comment]
Hey can you write a draft of how do you use this lib with a regular recycler view?

**Comment by amoikevin** [comment]
In code:
```
        SmartRefreshLayout srl = new SmartRefreshLayout(context);
        ...

        RecyclerView rv=new RecyclerView(context);
        ...
        srl.setRefreshContent(rv) or srl.addView(rv);

```
In xml:
```
<com.scwang.smartrefresh.layout.SmartRefreshLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent">
    <com.scwang.smartrefresh.layout.header.ClassicsHeader
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
    <RecylerView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        .../>
    <com.scwang.smartrefresh.layout.footer.ClassicsFooter
        android:layout_width="match_parent"
        android:layout_height="wrap_content"/>
</com.scwang.smartrefresh.layout.SmartRefreshLayout>
```
