### ISSUE TITLE
[How to] make every child item component to take whole space of RecycerCollectionComponent

### ISSUE THREAD

**Issue by amoikevin** [facebook/litho#644]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.34.0

## Issues and Steps to Reproduce
I have a horizontal RecycerCollectionComponent in the LithoView. 
There is no way to set width of ComponentRenderInfo's root component to take whole space of RecycerCollectionComponent.
By the way, the margin* methods doesn't work on ComponentRenderInfo's root component.

## Expected Behavior
I hope ComponentRenderInfo has methods (like marginPercent) to set it's width relative to the RecycerCollectionComponent.

**Comment by nileshkoo** [comment]
Have similar issue. How did you achieve it @amoikevin ?

**Comment by r-a-o** [comment]
+1 
@amoikevin
