### ISSUE TITLE
unable to find 0.34.1 snapshot

### ISSUE THREAD

**Issue by FunnyDevs** [facebook/litho#645]
Hi. When i set gradle with 0.34.1-SNAPSHOT i have this

ERROR: Failed to resolve: com.facebook.litho:litho-core:0.34.1-SNAPSHOT

**Comment by nicous** [comment]
Hey, the last version released is the 0.34.0.

**Comment by FunnyDevs** [comment]
Ok, but i would like to try the 0.34.1 snapshot (for kotlin DSL changes).
Here there is the 0.34.1-SNAPSHOT availability
https://fblitho.com/docs/getting-started

**Comment by nicous** [comment]
Oh! you are right! The CI is failing, once that is fixed the snapshot will be created.

**Comment by FunnyDevs** [comment]
ok, thank you!

**Comment by colriot** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/facebook/litho/litho-core/0.34.1-SNAPSHOT/
Fixed by #653
