### ISSUE TITLE
App Crash sometimes after upgraded to 0.33 and 0.34

### ISSUE THREAD

**Issue by wooyukit** [facebook/litho#649]
I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.33 and 0.34

## Issues and Steps to Reproduce
Sometimes crash when using the app

## Expected Behavior
Should not crash

<img width="1254" alt="Screenshot 2020-04-08 at 3 32 38 PM" src="https://user-images.githubusercontent.com/11748275/78757205-b53a7900-79ae-11ea-83ac-534971a09fbf.png">

**Comment by arpitratan** [comment]
@wooyukit Could you please share sample code on where this is happening and what is the repro steps? It would be great if you could also share the complete raw stack trace of the issue.

**Comment by wooyukit** [comment]
Actually, those crashes were from our production app and it is hard to repro. We have the crashlytics log only started from litho 0.33 version. I have no idea for the log message. Just wonder if there are some suggestions from the crash log.

**Comment by arpitratan** [comment]
@wooyukit  In that case could you please share the sample code of where its happening in case component is present in the stack trace? I can't say anything for sure until I have access to full stack trace, Could you please share the full stack trace ?

**Comment by colriot** [comment]
cc @adityasharat @mihaelao may it be due to Reconciliation or LayoutCalculation thread switch work?

**Comment by wooyukit** [comment]
I have the same guess. Therefore, I tried to disable that Reconciliation feature for the current app version but I got the crash report from crashlytics

**Comment by arpitratan** [comment]
@wooyukit Thanks you for confirming that it's not going away with reconciliation turned off. We have ruled out all the major recent changes which could have caused this. I'm afraid we will need a repro in order to proceed. Please get back to us with a repro by looking at the surface where this is happening.

**Comment by wooyukit** [comment]
@arpitratan Thanks for checking the issue. I am keep observing this issue in our app. After I disable the reconciliation, the number of crash seems dropped.

**Comment by wooyukit** [comment]
I have no idea about that. This crash has been occurred since upgraded to litho version 0.33. I have a plan to downgrade the litho version to test if the error is still existing but need to disable some new features of our app.
