### ISSUE TITLE
Where can i learn litho?i'm not able to find adequate resources any where

### ISSUE THREAD

**Issue by KishanAgarwal** [facebook/litho#650]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
***Add the version of the litho packages you use. You can paste the dependency
section of the gradle file if you have one.***

## Issues and Steps to Reproduce
***Replace this with steps to repro your issue.***

## Expected Behavior
***Describe what you expected would happen.***

## Link to Code
***Please show some code we can use to reproduce this issue. Consider using [PlaygroundComponentSpec](https://github.com/facebook/litho/blob/master/sample/src/main/java/com/facebook/samples/litho/playground/PlaygroundComponentSpec.java) to provide a small example of the issue***

**Comment by colriot** [comment]
Have you checked out our website with docs? https://fblitho.com
We also have codelabs (in code only state): https://github.com/facebook/litho/tree/master/codelabs
And two Sample apps in this repo.
What specific information you'd like to get?

**Comment by KishanAgarwal** [comment]
Its like I am having problem with configuring litho in my android studio.
Spec class is not showing the correct results. Maybe if a detailed video
demo or so was there,  that would be really helpfull.

**Comment by colriot** [comment]
Well I don't know what to add to [Getting Started](https://fblitho.com/docs/getting-started), it seems adequate :)
Also checkout this codelab demo: https://github.com/facebook/litho/tree/master/codelabs/hello-world

What exactly is happening?

**Comment by KishanAgarwal** [comment]
It's like when i am using section then i am not able to use the class
defined for it. Here attached are some screenshots of my project in android
studio. ListSection is the class defined for creating list and ListItem
for  item of the list but it is showing an error. The error is in
mainactivity.

And sir I am thankful to you that you cared about it.

**Comment by colriot** [comment]
@KishanAgarwal  nothing is attached. Can you post it via Github web interface? Did you define ListSectionSpec yourself?

**Comment by KishanAgarwal** [comment]
Yes sir why not. 
Yes sir i defined it myself but everything was same as that of in tutorials present.
Sir, PFA.

![LithoProblemMain](https://user-images.githubusercontent.com/58020942/80272424-c7265680-86e6-11ea-86b0-3446407f3359.PNG)

![ListItemSpecClass](https://user-images.githubusercontent.com/58020942/80272642-e8884200-86e8-11ea-9c36-25771fae4428.JPG)

![ListSectionSpecClass](https://user-images.githubusercontent.com/58020942/80272682-29805680-86e9-11ea-9fa9-430820944d81.JPG)

**Comment by KishanAgarwal** [comment]
Sir i,ve posted the screenshots in the github interface. Hole you've seen
it. If not please see it once.

**Comment by colriot** [comment]
@KishanAgarwal have you added both Annotation Processors to the `build.gradle`? Specifically the one for Sections: `annotationProcessor 'com.facebook.litho:litho-sections-processor:0.34.0'`

FYI: https://fblitho.com/docs/getting-started#adding-sections-to-your-project

**Comment by KishanAgarwal** [comment]
Yes sir i've checked it. All annotations are added.

**Comment by colriot** [comment]
It's not an annotation artifact, but an annotation processor. Please, show me your `build.gradle` file`

**Comment by KishanAgarwal** [comment]
![build gradle](https://user-images.githubusercontent.com/58020942/80462067-d65e0c00-8953-11ea-9652-da5764d97a5f.JPG)

Attached is the build.gradle file

**Comment by KishanAgarwal** [comment]
I've attached build.gradle file in guthub interface.

**Comment by colriot** [comment]
Seems ok...
If it still doesn't work, please share your sample project via Github or zip. I'll try to look at it

**Comment by colriot** [comment]
Closing this for now, as no recent interaction was done. Feel free to reopen if needed.
