### ISSUE TITLE
Component height runtime

### ISSUE THREAD

**Issue by FunnyDevs** [facebook/litho#651]
Hi! I'm using litho in conjuction with standard views. I need to know a component height at runtime to create ad animation together a standard view. Is there any API to obtain this information?

Thank you

**Comment by colriot** [comment]
Want kind of Components do you use? If it's a MountSpec you can use `@OnMeasure` and `@OnBoundsDefined` methods to determine and remember the size

**Comment by FunnyDevs** [comment]
The component draw a panel with @OnCreateLayout (let's call it "BottomComponent") and it is positioned at the bottom of the screen; then i should position a standard view on top of "BottomComponent", but without knowing BottomComponent height, i'm not able to do it

**Comment by colriot** [comment]
Why don't you create all of your UI with Litho? Mixing raw View with Litho might be not the best idea. If you want to add a custom View in your Litho hierarchy, try putting it in a MountSpec component, which can be positioned on top of the BottomComponent

**Comment by FunnyDevs** [comment]
I would like to do it, but I'm using a mapview and some operations (like setting padding on it) are executed on GoogleMap object, not the view.
So i would like to change the mappadding (from bottom of the screen) over the litho Component, but without knowing litho height, it is difficult.

**Comment by wooyukit** [comment]
you can use @OnCreateLayoutWithSizeSpec
https://fblitho.com/docs/custom-layout.html#sizespec-information-during-layout to get the component height at runtime

**Comment by FunnyDevs** [comment]
Thank you! I' ll give it a try

**Comment by colriot** [comment]
@wooyukit thanks for helping!
@FunnyDevs yep, you can indirectly try to propagate that info via callback or smth, but that's still a quite hacky way :(

**Comment by colriot** [comment]
I'll close this for now, with no new interactions currently. Feel free to reopen if needed
