### ISSUE TITLE
TextInput request focus

### ISSUE THREAD

**Issue by FunnyDevs** [facebook/litho#659]
- [✓] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.35.0

## Issues and Steps to Reproduce
use case:
i would like to requestfocus and clearFocus on TextInput programmatically

**Comment by colriot** [comment]
Hi @FunnyDevs!
Sorry for a late reply. You can trigger these events via specific Trigger-methods.
In particular:
```
TextInput.clearFocus(c, textInputHandle);
TextInput.requestFocus(c, textInputHandle);
``` 

You can check examples (how to setup Handle, etc) here:
https://fblitho.com/docs/trigger-events

**Comment by FunnyDevs** [comment]
Ok, thank you! And if i would decide to request focus or not on a TextInput at startup?

**Comment by colriot** [comment]
Good question. Seems that we don't have that ability. I can suggest a workaround:
1) Create VisibleEvent handler and set it to your TextInput.
2) In that EventHandler flip the flag (you only want to requestFocus on the first VisibleEvent) and call the method I mentioned above if VisibleEvent was sent the first time

**Comment by FunnyDevs** [comment]
Ok, it works. Thank you!
