### ISSUE TITLE
Add support for borderRadius

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#66]
We already have support for specifying border width and border color on a component. Now we would like to have an ability to specify the border radius which will draw curved edges on the component. The API might look like this:

```java
Row.create(c)
        .child(
            Row.create(c)
                ....)
        .child(
            Text.create(c)
                .text("Sample with border radius")
                .textSizeDip(14))
        .child(
            Row.create(c)
                ....)
        .borderColor(Color.BLUE)
        .borderWidthDip(YogaEdge.BOTTOM, 33)
        .borderRadiusDip(TOPLEFT, 2)
        .borderRadiusDip(TOPRIGHT, 2)
        .build();
```

Or you can specify one value for all edges something like:
```java
Row.create(c)
       .....
        .borderRadiusDip(ALL, 2)
        .build();
```

Besides specifying radius in Dip, you should be able to specify it in pixel value, resource attribute, dimension, similar to how borderWidth is defined.

Point of contact: @muraziz

**Comment by chakkrachak** [comment]
It would be so great !

**Comment by ooga** [comment]
I could help you if you have an idea of ​​the implementation

**Comment by passy** [comment]
Doesn't the new Border effects API provide this now?

**Comment by muraziz** [comment]
Yes, Border API supports not only border radius, but also other effects such as dotted, dash, multi-color borders.

**Comment by ooga** [comment]
If we set a background color, it overflow int the corner

**Comment by muraziz** [comment]
Hey @ooga, thanks for raising this. Could you create a new issue with some screenshot?

**Comment by ooga** [comment]
@muraziz The issue is created #235

**Comment by muraziz** [comment]
Rounded corner borders are already supported, now you can add border radius like this:
```
Row.create(c)
  .child(
    Text.create(c)
      .text("Hello Litho")
      .textSizeSp(16))
  .border(
    Border.create(c)
      .widthDip(YogaEdge.ALL, 5)
      .color(YogaEdge.ALL, 0xfff36b7f)
      // We set a corner radius of 10 here
      .cornerEffect(10f)
      .build())
  .build();
```
See https://fblitho.com/docs/borders
