### ISSUE TITLE
ListSectionSpec with dynamic list item

### ISSUE THREAD

**Issue by esperaking81** [facebook/litho#664]
Am trying to create a ListSectionSpec that takes a type paramter for building a list. I mean passing the model tto be shown in list as a type parameter so that my ListSectionSpec can display any kind of items withoud knowing in advance the object type.

Am using Kotlin Android.

**Comment by wooyukit** [comment]
What is your problem?
You can determine the model to create different kind of litho component in SectionSpec.
`@OnCreateChildren`
    `static Children onCreateChildren(SectionContext c, @Prop ItemViewModel model){`
`when(model){`
`is A -> ComponentA.create(c).build()`
`is B -> CompnoentB.create(c).build()`
`}}`

**Comment by esperaking81** [comment]
Thanks for you response.
When I say  ItemType, it's about the data type. I mean the data class representing the item that should be consumed. e.g. I display a listOf<Doctor> when I know the data type. But in case I don't know in advance what kind of data. It's a bit complicated as Litho don't support TypeVariable <T>

**Comment by colriot** [comment]
@esperaking81 Hi!
Have you tried to use generics for this case?

Like that:
```
@GroupSectionSpec
object ListSectionSpec<T> {
  
  @OnCreateChildren
  fun <T> onCreateChildren(
      c: SectionContext,
      @Prop data: List<T>): Children {
    return Children.create()
        .child(
            DataDiffSection.create<Any>(c)
                .data(data)
                .renderEventHandler(ListSection.onRender(c))
        )
        .build()
  }

  @OnEvent(RenderEvent::class)
  fun <T> onRender(
      c: SectionContext,
      @FromEvent index: Int,
      @FromEvent model: T): RenderInfo {
    return ComponentRenderInfo.create()
        .component(
            Text.create(c)
                .text(model.toString())
                .textSizeSp(20f))
        .build()
  }
}
```

And then in your parent component:
```
@OnCreateLayout
  fun onCreateLayout(c: ComponentContext): Component {
    val dataModels = listOf(Person("John"), Person("Mary"))
    return RecyclerCollectionComponent.create(c)
        .disablePTR(true)
        .section(
            ListSection.create(SectionContext(c))
                .data(dataModels)
                .build())
        .paddingDip(YogaEdge.TOP, 8f)
        .build()
  }
```

**Comment by esperaking81** [comment]
I can't do that.

First of all, thank you very much for looking down on my issue.

I've tried that but Litho is not able to generate class with this structure.
It says that the @Prop variable with TypeVariable is not a valid @Prop data type.

And I should tell you that I am creating a list from a service. The service call stuffs are managed directly inside the class.

Like this

`
@GroupSectionSpec
object ListSectionSpec {

    @OnCreateInitialState
    fun onCreateInitialState(
        c: SectionContext,
        items: StateValue<List<ResultObject>>,
        start: StateValue<Int>,
        count: StateValue<Int>,
        isFetching: StateValue<Boolean>,
        @Prop url: Url?
    ) {
        start.set(0)
        count.set(15)
        items.set(emptyList())
        isFetching.set(false)
    }

    @OnCreateChildren
    fun onCreateChildren(
        c: SectionContext,
        @State items: List<ResultObject>,
        @State isFetching: Boolean,
        @State start: Int,
        @State count: Int,
        @Prop listItem: BaseComponent
    ): Children? {
        val builder: Children.Builder = Children.create()
        writeToLog("ListItem by default is $listItem")

        items.map { it.items }.map { i ->
            var toRender = listItem.clone()
            toRender = setContent(toRender, i as Map<String, String>).clone()
            builder.child(
                SingleComponentSection
                    .create(c)
                    .key("_key${Random.nextInt(1000)}")
                    .component(
                        (toRender.transformToLitho(c) as Component)
                            .apply {
                                commonProps?.clickHandler(ListSection.onClick(c, i))
                            }
                    )
                    .build()
            )
        }

        // Display the loading component when list size if above or equal 10
        if (items.size >= 10) {
            builder.child(
                SingleComponentSection.create(c)
                    .component(ProgressLayout.create(c))
                    .build()
            )
        }

        return builder.build()
    }

    @OnCreateService
    fun onCreateService(
        c: SectionContext,
        @State items: List<ResultObject>,
        @State start: Int,
        @State count: Int,
        @Prop url: Url?
    ): BaseService {
        return BaseService(baseUrl = url)
    }

    @OnBindService
    fun onBindService(c: SectionContext, service: BaseService, @State items: List<ResultObject>) {
        service.registerLoadingEvent(ListSection.onDataLoaded(c))
        if (items.isEmpty()) service.fetch(0, 15)
    }

    @OnUnbindService
    fun onUnbindService(c: SectionContext, service: BaseService) {
        service.unregisterLoadingEvent()
    }

    @OnEvent(BaseEventModel::class)
    fun onDataLoaded(c: SectionContext, @FromEvent items: List<ResultObject>) {
        ListSection.updateData(c, items)
        ListSection.setFetching(c, false)
        SectionLifecycle.dispatchLoadingEvent(c, false, SUCCEEDED, null)
    }

    @OnUpdateState
    fun updateData(
        items: StateValue<List<ResultObject>>,
        start: StateValue<Int>,
        @Param newItems: List<ResultObject>
    ) {
        if (start.get() == 0) {
            items.set(newItems)
        } else {
            val docs = arrayListOf<ResultObject>()
            items.get()?.also {
                docs.addAll(it)
                docs.addAll(newItems)
            }
            items.set(docs)
        }
    }

    @OnRefresh
    fun onRefresh(
        c: SectionContext,
        service: BaseService,
        @State items: List<ResultObject>,
        @State start: Int,
        @State count: Int
    ) {
        ListSection.updateStartParam(
            c,
            0
        )
        service.fetch(0, 15)
    }

    @OnUpdateState
    fun setFetching(
        isFetching: StateValue<Boolean?>,
        @Param fetch: Boolean
    ) {
        isFetching.set(fetch)
    }

    @OnUpdateState
    fun updateStartParam(start: StateValue<Int>, @Param startParam: Int) {
        start.set(startParam)
    }

    @OnViewportChanged
    fun onViewportChanged(
        c: SectionContext,
        firstVisiblePosition: Int,
        lastVisiblePosition: Int,
        firstFullyVisibleIndex: Int,
        lastFullyVisibleIndex: Int,
        totalCount: Int,
        service: BaseService,
        @State items: List<ResultObject>,
        @State start: Int,
        @State count: Int,
        @State isFetching: Boolean,
        @Prop url: Url?
    ) {
        if (totalCount == items.size && !isFetching && totalCount >= 15) {
            ListSection.setFetching(c, true)
            ListSection.updateStartParam(c, items.size)
            service.fetch(items.size, count)
        }
    }

    @OnEvent(ClickEvent::class)
    fun onClick(
        c: SectionContext, @FromEvent view: View,
        @Param item: Map<Any, Any>,
        @Prop(optional = true) listener: OnListItemClick
    ) {
        listener.onClick(item)
    }

    interface OnListItemClick {
        fun onClick(item: Map<Any, Any>)
    }
}
`

**Comment by esperaking81** [comment]
Type Parameters are not allowed for objects.
Lint error...

**Comment by colriot** [comment]
@esperaking81 sorry, I check the code in Java and then just converted it to Kotlin. You can make your Spec class a `class` and add `@JvmStatic` to each method. This effectively will create the same `static` methods as you'd declare in Java Specs. I didn't dig into your code deeply. as it's quite long. But I have two comments:

1)
       (toRender.transformToLitho(c) as Component)
         .apply {
            commonProps?.clickHandler(ListSection.onClick(c, i))
         }

you don't need to access `commonProps`, `clickHandler` is available for every Component instance

2) If you call several UpdateState methods together, like in 
```
ListSection.setFetching(c, true)
ListSection.updateStartParam(c, items.size)
```
You should better create a method that does both things in one go. As, each OnUpdateState method call effectively rebuild the tree. I.e in this case you do it twice, which impacts perf and you don't want it :)

**Comment by esperaking81** [comment]
Thank you very much for your support.
I managed to work with Map<String, Any> to handle the case of an API fetch result. 
And about the UpdateState methods, you're right. I'll do as you said.
Thank you very much for everything.

I'll still try to create a ListSectionSpec with type variable using the class and JvmStatic annotation as you suggested.
Thanks again.

**Comment by colriot** [comment]
@esperaking81 you're welcome! I'll close this one then, feel free to reopen it or create another one if other questions arise
