### ISSUE TITLE
Migrate Website to Docusaurus 2 Alpha

### ISSUE THREAD

**Issue by Drewbi** [facebook/litho#669]
@yangshun mentioned Litho was interested in porting the documentation website over to Docusaurus V2. 

@teikjun and I are working on moving everything over currently and we will be making a PR soon. 

I anticipate some alterations to the deployment config will have to be made as I'm not too experienced in that field.

**Comment by yangshun** [comment]
Relevant issue - https://github.com/facebook/docusaurus/issues/1834

**Comment by colriot** [comment]
Finally all your work was deployed publicly and ready to be used with https://github.com/facebook/litho/commit/8934eefb6900487d6336b74009007476d5c11ab1!

Thanks again for helping us with that, @Drewbi @teikjun !

**Comment by Drewbi** [comment]
Ayy thanks for the merge, hope you like the new framework :)
