### ISSUE TITLE
Border width is not respected in leaf nodes

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#67]
When we set border color and border width on container components (such as Row/Column or any layout spec), it is drawn correctly respecting the boundaries of child items. However, when we set border on a leaf node (such as TextSpec or any mount spec) the border is overlapping with the actual content of that leaf node. Let's see these two cases:

Case 1: This works fine, i.e. the text content is not overlapped with border: 
```java
Column.create(c)
             .child(Text.create(c)
                        .text("Lorem ipsum")
                        .textSizeDip(18))
             .borderColor(Color.GREEN)
             .borderWidthDip(YogaEdge.LEFT, 6)
             .borderWidthDip(YogaEdge.TOP, 6)
```

Case 2: Here the border is overlapping with the content:
```java
Text.create(c)
             .text("Lorem ipsum")
             .textSizeDip(18)
             .withLayout()
             .borderColor(Color.GREEN)
             .borderWidthDip(YogaEdge.LEFT, 6)
             .borderWidthDip(YogaEdge.TOP, 6)
```

Possible solution could be to offset the `LayoutOutput`'s bounds when it's calculated (https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/LayoutState.java#L215) in the same way as we do with padding.

Point of contact: @muraziz

**Comment by colriot** [comment]
Already fixed
