### ISSUE TITLE
How to properly detach component builder from context (makeShallowCopy is leaking)

### ISSUE THREAD

**Issue by caiiiycuk** [facebook/litho#674]
Hi. I trying to create something like shared header component to have smooth transitions between activities. 
My code working like this:

`Activity A`, sets the header. I make it shallow copy and store it in global variable.
When transition is requested I do `startActivity` with `header` as shared component.
`Activity B`, uses stored version of component, and put it inside LithoView of `Activity B`.

```
// Activity A:
        GlobalContext.sharedHeader = component.makeShallowCopy();
        headerView.setComponent(component);

// startActivity with transition

// Activity B:
        headerView.setComponent(GlobalContext.sharedHeader);
```

Visually it looks perfect, header stay on it place without any artifacts. But this way produces memory leak, because
shallow copy have mBuilderContext, that pointing to `Activity A`

I can store just builder of component and recreate header when it's needed (I think it's more correct solution), but `Component.Builder` also stores context in field, and it can't be changed after builder is created. In other words I want to do something like this:

```
// Activity A
   Component.Builder<?> headerBuilder = Header.create(c).props(...);

   headerView.setComponent(headerBuilder.build());
   GlobalContext.sharedHeaderBuilder = headerBuilder.setCompnentContext(null);

// startActivity with transition

// Activity B
   headerView.setComponent(headerBuilder.setComponentContenxt(c).build());
```

## Version
0.36.0

**Comment by muraziz** [comment]
Given that this issue was opened a year ago, closing it now as it might not be relevant any more due to changes in Litho code since then. But if this is still relevant please create a new issue.
