### ISSUE TITLE
MountSpec in AppBarLayout have wrong behavior

### ISSUE THREAD

**Issue by Tobyyyyyyyyyy** [facebook/litho#675]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
`v0.36.0`

## Issues and Steps to Reproduce
1. Warp a VideoView in MountSpec
2. Use this spec in AppBarLayout
3. Infinite loop call `OnMount` and `OnUnmount`, VideoView can't play.

## Expected Behavior
VideoView play normally

## Link to Code
[Sample](https://github.com/facebook/litho/issues/new)
[My solution](https://github.com/Tobyyyyyyyyyy/LithoInAppBarSample/blob/master/app/src/main/java/com/example/wt/lithoinappbarsample/MyLithoView.kt#L38)

My solution cannot solve the fundamental problem, Hope to get the perfect solution.

**Comment by muraziz** [comment]
Given that this issue was opened a year ago, closing it now as it might not be relevant any more due to changes in Litho code since then. But if this is still relevant please create a new PR.
