### ISSUE TITLE
how to disable animation by key

### ISSUE THREAD

**Issue by Syne10** [facebook/litho#677]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

if you set the key to the list components, when the list is updated, the components will change with animation.
Is there a way to remove transition without deleting key???

**Comment by Katalune** [comment]
If you don't want animation because item hasn't changed, probably you don't want it updated at all. There're methods DataDiffSection#onCheckIsSame.. to control update behaviour.
https://fblitho.com/javadoc/com/facebook/litho/sections/common/DataDiffSection

**Comment by Syne10** [comment]
I need to update the list, but without animation.
At the moment, helped litho_view.release() before updating.
But I thought there is a better way to solve this problem..

**Comment by colriot** [comment]
@Syne10 you can set ItemAnimator for RecyclerCollection to `null` and no animation will happen

**Comment by Syne10** [comment]
@colriot this is what I need. Thanks
