### ISSUE TITLE
Add ability to send imperative commands with new Trigger API

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#68]
The Event api gives us the ability for child components to give callback to their parents. However in some cases we have the need for components to trigger actions on their children. The typical example is to issue a `scrollToTop` command on a `Recycler` component.

Let's call this Triggers, i.e. the ability perform imperative commands on mounted views/drawables in a type-safe way. This API would look very similar to the Event API but act in the inverse direction.

Point of contact: @muraziz

**Comment by colriot** [comment]
Already landed
