### ISSUE TITLE
Docs for @OnBind and @OnUnbind are not accurate

### ISSUE THREAD

**Issue by amrro** [facebook/litho#702]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
`0.37.1`

## Link to Code
https://github.com/facebook/litho/blob/bad7023f2668882a9d01525676d8ef868ce06f09/litho-annotations/src/main/java/com/facebook/litho/annotations/OnUnbind.java#L25-L27

Mentioned in the comments of `OnBind` annotation that it takes Android's `Context` as the first parameter. But when applied,  it throws this error: 

> error: Parameter in position 0 of a method annotated with interface com.facebook.litho.annotations.OnBind should be of type com.facebook.litho.ComponentContext.

And it works with `ComponentContext`. Same goes with `@OnUnbind` annotation. Should the comments be updated or is there something I am missing?

**Comment by colriot** [comment]
Hi @amrro! Yep, this should be fixed – good catch! Do you want to send a PR?

**Comment by amrro** [comment]
Sure.

**Comment by amrro** [comment]
Hey @colriot, I linked the tutorials and added comments for `OnMeasure` annotation too.

**Comment by colriot** [comment]
@amrro thank you!
