### ISSUE TITLE
Nested Component ignores the new Prop.

### ISSUE THREAD

**Issue by amrro** [facebook/litho#706]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

Maybe related issues: 
#587 #664 #636

## Version
`0.37.1`

## Issues and Steps to Reproduce
```
o RecyclerCollectionComponent
|
+--o GroupSectionSpec
   |    a state changing here based on user inputs that is passed as a prop for the next component. 
   |
   +--o ImagePickerSpec
      | This component is not affected by changing its prop which is affected the state of the parent Component.
      |
      +--o ...
```
## Expected Behavior
Changing prop suposedly will guide the framework to renewer new component since the props are immutable. 

### Fragment's onCreateView()
```kotlin
        val component: Component = RecyclerCollectionComponent.create(c)
            .disablePTR(true)
            .section(
                FormViewRootComponent.create(SectionContext(c))
                    .loader(this.serviceLoader)
                    .activity(requireActivity())
                    .build()
            )
            .build()

        return LithoView.create(c, component)
```

### FormViewRootComponentSpec's @OnCreateChildren
State here is updated. and passed as a `prop` to a child of this Group Section. 
```kotlin
    @OnCreateChildren
    internal fun onCreateLayout(
        c: SectionContext,
        @State slug: String,
        @State images: ArrayList<String>?,
        ...
    ): Children {

        builder.child(
            SingleComponentSection.create(c)
                .isFullSpan(true)
                .key("image-picker-component")
                .component(
                    Column.create(c)
                        .child(
                            ImagesPicker.create(c)
                                .title("Pick Images")
                                .key(images?.size.toString())
                                .images(images)
                                .max(5)
                                .min(2)
                                .clickEventHandler(FormViewRootComponent.onClick(c, "date"))
                                // .alignSelf(YogaAlign.CENTER)
                                .marginRes(YogaEdge.BOTTOM, R.dimen.dimen_16dp)
                                .marginRes(YogaEdge.TOP, R.dimen.dimen_16dp)
                                .marginRes(YogaEdge.START, R.dimen.dimen_16dp)
                                .marginRes(YogaEdge.END, R.dimen.dimen_16dp)
                        )
                )
        )

```

### ImagePickerSpec has collections that should display the list of selected images.
** The new updated list of images should be delivered here. But it's not.**
```kotlin
        return Column.create(c)
            .child(
                Row.create(c)
                    .child(
                        ...
                    )
                    .child(
                        ...
                    )
            )
            .child(
                RecyclerCollectionComponent.create(c)
                    .key("list-of-selected-images")
                    .recyclerConfiguration(
                        ListRecyclerConfiguration.create()
                            .orientation(OrientationHelper.HORIZONTAL)
                            .snapMode(LinearSmoothScroller.SNAP_TO_START)
                            .build()
                    )
                    .section(
                        DataDiffSection.create<String>(SectionContext(c))
                            .key(images.size.toString())
                            .data(images)
                            .renderEventHandler(ImagesPicker.onRenderImage(c))
                    )
                    // .section(
                    //     SelectedImages.create(SectionContext(c))
                    //         .images(images ?: setOf())
                    //         .max(6)
                    // )
                    .heightDip(128f)
            )
            .child(
                AddImageItem.create(c)
                    .clickHandler(ImagesPicker.onAddImageClicked(c))
            )
            .build()
```

When updated the prop form the parent Group section, it's not affected.

**Comment by pasqualeanatriello** [comment]
The problem is that DataDiffSection will only re-render items for which the corresponding element in the data list has changed.
In your case I assume that nothing is changing in data. Re-rendering based on props not in the data list is unfortunately not supported so I would recommend you just add whicheve information you are trying to use for rendering in your list of models.
The other suspicious thing I see here is that you are giving the size of your list as a key to the DataDiffSection. That's really inefficient as any time the number of elements change you are forcing all items to be re-rendered again. 
This video explains a bit more how you should be doing diffing in Sections: https://www.youtube.com/watch?v=-Ahskig2Lw0

**Comment by amrro** [comment]
Hey @pasqualeanatriello,

> Re-rendering based on props not in the data list is unfortunately not supported so I would recommend you just add whicheve information you are trying to use for rendering in your list of models.

The data represents inputs selected by user, user can add/remove from/to it. The list itself gets updated. 


>The other suspicious thing I see here is that you are giving the size of your list as a key to the DataDiffSection. That's really inefficient as any time the number of elements change you are forcing all items to be re-rendered again.

This was another try to force component rendering, but it didn't work either.

**Comment by amrro** [comment]
I don't think it's with the the `DataDiffSection`
Here is the chain again. 
```
ImagesPicker
Column
RecyclerCollectionComponent
```
the updated prop, or the updated list, doesn't reach the `ImagePicker`. 

I've replaced the `ImagePicker` with `RecyclerCollectionComponent` with render and is same item events and it's the same behavior.

Am I doing something wrong?

**Comment by amrro** [comment]
@pasqualeanatriello , @colriot 

Would you help me please?
