### ISSUE TITLE
0.38.0 is unavailable on Jcenter

### ISSUE THREAD

**Issue by tpucci** [facebook/litho#707]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.37.0

## Issues and Steps to Reproduce

In the docs and in Github, it is written that the version 0.38.0 is released.
However, the release does not exist in Jcenter repo.

## Expected Behavior

Jcenter repo contains the 0.38.0 version.

## Link to Code

/

**Comment by pakoito** [comment]
I'm experimenting with Github Actions and it has failed a couple of times, which has delayed the release: https://github.com/facebook/litho/actions/runs/255928746

I will make sure this is landed today, even if it's still manually for now.

**Comment by pakoito** [comment]
New failure because we haven't registered a new package 😬 Retrying in a few minutes.

**Comment by colriot** [comment]
@tpucci all good now. Shiny `v0.38.0` is synced with Bintray!

**Comment by tpucci** [comment]
Thank you very much 😁😁😁
