### ISSUE TITLE
Create api to acquire Views for measuring

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#71]
We need an API for acquiring Views for measuring. This api would allow us to do things like:
```java
@OnMeasure
protected static void onMeasure(
        ComponentContext c, 
        ComponentLayout layout, 
        int widthSpec, 
        int heightSpec, 
        Size size) {
    View toMeasure = c.acquireMeasurableView();
    toMeasure.measure(...)
    ...
    c.releaseMeasurableView(toMeasure);
}
```

This way we might cache the views by context and thread and make this thread safe and consistent with theming. The acquire being a Component level api could simply call `ComponentLifecycle.createMountContent` under the hood (and create appropriate `LayoutParams`).

Point of contact: @IanChilds

**Comment by newfivefour** [comment]
I've come across this problem too.

I want to use Android EditText. (It has properties that litho's doesn't).

I want to measure the height of the EditText like this: https://stackoverflow.com/questions/24359538/how-to-find-the-text-areaheight-width-of-textview-programmatically-in-android/24359594#24359594

```
textView.setText("bla");
textView.measure(0, 0);
textView.getMeasuredWidth();
textView.getMeasuredHeight();
```

But currently there is no way to access the Android EditText in the `onMeasure` function.

@IanChilds @emilsjolander Does this touch on the same issue in this ticket or shall I make a new one? This one hasn't been touched for 20 days.

**Comment by IanChilds** [comment]
Not sure what you mean here: 

> But currently there is no way to access the Android EditText in the onMeasure function.

If you look at https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/EditTextSpec.java#L229 you see that it _does_ actually access the Android EditText in the `onMeasure` method.

**Comment by ar-g** [comment]
@IanChilds API for measuring custom views such as EditText is unclear. Moreover, in EditText example to measure EditTextSpec we create a new instance of EditText each time. Is this a common approach to implement onMeasure for any view capable to resize itself dynamically?
