### ISSUE TITLE
Navigation between components

### ISSUE THREAD

**Issue by KirillSaltykov** [facebook/litho#712]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
Latest

## Comment
Hello. How can I manage navigation between components? I'm a newbie in Android development and coming from SwiftUI/React Native. In RN, there is react-navigation that manages nav flow in the app; SUI has NavigationLink; what I should use when developing with Litho?

**Comment by adityasharat** [comment]
Litho currently does not support native Android navigations. So I suppose you will have to implement navigation natively outside of Litho.
