### ISSUE TITLE
How to get view inside component spec for Snackbar

### ISSUE THREAD

**Issue by amrro** [facebook/litho#718]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Expected Behavior
I want to get the view inside an event in order to display a `Snackbar` message. Is there a method or a way to do so other than the `ClickEvent`'s , like to trigger it under certain conditions or so.

**Comment by andrewpmsmith** [comment]
Could you provide a bit more detail about what you're trying to do?

One option for retrieving a View would be to specify the view tag when creating the component (`.viewTag(VIEW_TAG)`) then retrieve it in the event with `activity.getWindow().getDecorView().findViewWithTag(VIEW_TAG)`

**Comment by amrro** [comment]
Hello @andrewpmsmith, 

What I am trying to do is to display a `Snackbar` message in case of some uploading some data finished. `Snackbar` requires view or anchor view to be displayed. 

Event starts in `@OnEvent` method, and and in some callback I want to display the `Snackbar`. So the question is how to get the view or the root view of the component in order to display it? 

Thanks for you tip, But the logic happens in side the component.

**Comment by andrewpmsmith** [comment]
So you could do this inside the component...


```
// In @OnCreate
return Column.create(c)
  .viewTag("root_tag")
  ...

// Inside event
View root = ((Activity) c.getAndroidContext()).getWindow().getDecorView().findViewWithTag("root_tag");
```

**Comment by amrro** [comment]
This great! Thanks.
