### ISSUE TITLE
Create TextSpec API for highlighting text with longclick like in Android EditText

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#72]
Create a new API in TextSpec to give callback about the text that's highlighted and change highlight text background. This should be similar to how Android EditText handles text selection.

To achieve that first we need to get (x, y) coordinates of a touch event, and then get the start, end offset of the text that's under (x,y). 
For the first part we can do something similar as in `TextView`'s `getOffsetForPosition()` API (https://developer.android.com/reference/android/widget/TextView.html#getOffsetForPosition(float, float)). When we have start, end offset of the text, it shouldn't be hard to highlight corresponding portion of the text.

For the API side we might create a new event, something like `TextHighlightEvent` and provide corresponding prop to `TextSpec`.

Point of contact: @muraziz

**Comment by muraziz** [comment]
This is very old issue, it may or may not be relevant now, closing it for now. If needed, new issue can be created reflecting current state of Litho APIs.
