### ISSUE TITLE
Support setting themable styles on Components

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#73]
Right now we only apply styles if the user explicitly sets one in the component's create() method. However, we want to be able to set this in the Component itself so that you can make components automatically gather styles from the theme.

The work here is to automatically get the theme off the context and set the appropriate props on mount items (`Text`, etc) if they are not otherwise overridden.

Point of contact @emilsjolander

**Comment by sheshank-2903** [comment]
@emilsjolander hello, I am new to open source contribution, I want to start my contribution with this task can you help me out with details and tips?
thanks and regards
