### ISSUE TITLE
Post sync state updates instead of immediately starting

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#74]
Sync state updates should be posted on the main thread instead of executed immediately. 
If a sync state update is triggered while we're executing a layout calculation, then the state update would trigger another layout calculation. We should instead post any sync state updates on the main thread and wait for the current layout calculation to be finished before starting a new one.

### Code pointer
https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/ComponentTree.java#L677

Point of contact: @mihaelao

**Comment by colriot** [comment]
Closed as fixed
