### ISSUE TITLE
don't do anything If a state is "updated", but it hasn't actually changed

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#75]
Don't trigger state updates if the old value and new value of the state is the same.

Two ideas for this:
1. When we have all the `stateUpdates` on the `ComponentTree`, we could call shouldUpdate on each Component and if it is false for all of them, then we should return without calculating a new layout.
2. When we update the value for the state, we could compare it to the old one and if it is the same, then don't do anything (seems simpler, not sure if there are issues here).

We could have a `StateContainer` comparison and don't enqueue incoming `StateUpdates` if the state value doesn't change. 

### Code pointer
https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/ComponentTree.java#L697

Point of contact: @mihaelao

**Comment by appleguy** [comment]
@mihaelao is this behavior now implemented by default? Alternatively, is there a specific API that a client needs to use in order to ensure that equivalent states don't trigger an update? cc @vinc3m1

**Comment by vinc3m1** [comment]
Is this an upcoming fix? or permanently backlogged now?

**Comment by mihaelao** [comment]
Sorry for the delay, I missed this! We didn't invest time in this because it's not a common problem, you can avoid this situation by checking the state value before triggering an update. Are you facing an issue with this?

**Comment by mihaelao** [comment]
Closing this as we've decided not to invest time in this; comparing two state objects transparently on the framework is not trivial, as we could be dealing with complex objects, and asking the developer to implement a comparison method when using state API is unnecessary overhead. This can already be handled with the current API by conditionally triggering state updates.
