### ISSUE TITLE
Recycle StateUpdate objects

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#77]
We should have a pool of `StateUpdate` objects instead of allocating a new one for each state update creation. The state update objects don't live past a layout calculation, so we can recycle them then. Each generated lifecycle would need a pool instance types to their specific `StateUpdate` subclass and instead of calling `new StateUpdate()` we would need to acquire / release these objects from / to the pool. This is very similar to how we currently generate pools for the specific builder objects. 

### Code pointers
https://github.com/facebook/litho/blob/master/litho-processor/src/main/java/com/facebook/litho/specmodels/generator/ComponentImplGenerator.java#L320

https://github.com/facebook/litho/blob/master/litho-processor/src/main/java/com/facebook/litho/specmodels/generator/BuilderGenerator.java#L93

Point of contact: @mihaelao

**Comment by appleguy** [comment]
@mihaelao @passy @pasqualeanatriello more broadly on object pooling, is there any analysis in the last year of the most common sources of new allocations to rank the value of new pools? Is StateUpdate near the top of the list for types that have not already been pooled?

**Comment by colriot** [comment]
We ran an experiment and pooling happened to not be very efficient at all, especially with the new GC. So, pooling was already removed. Also, some changes to the StateUpdates codegen are coming soon.

Closing this
