### ISSUE TITLE
Expose RecyclerView in RecyclerBinder.

### ISSUE THREAD

**Issue by RamiMohammedSeid** [facebook/litho#771]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
implementation 'com.facebook.litho:litho-core:0.39.0'
implementation 'com.facebook.litho:litho-widget:0.39.0'
kapt 'com.facebook.litho:litho-processor:0.39.0'
implementation 'com.facebook.litho:litho-fresco:0.39.0'
implementation 'com.facebook.fresco:fresco:1.13.0'

## Issues and Steps to Reproduce
***Expose RecyclerView in RecyclerBinder, I specifically had this irritating problem in-which I wanted to scroll into a specific location providing float as scrollY, I've done some research and found out that RecyclerView is not exposed, but there's a private field (Image attached bellow).***

## Expected Behavior
***I expected it to have a scroller or RecyclerView exposed so I can do the scrolling myself. since Litho by default uses the native RecyclerView, I don't see any reason for not exposing it directly from RecyclerBinder.***

## Link to Code
![Screen Shot 2021-02-18 at 5 21 46 AM](https://user-images.githubusercontent.com/48802163/108295701-35259800-71a9-11eb-8f28-5e13cf2e5abb.png)

**Comment by muraziz** [comment]
Hi @RamiMohammedSeid , 

We already have API for scrolling, check out https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/RecyclerEventsController.java#L91

You can add it as prop to RecyclerCollectionComponent: https://github.com/facebook/litho/blob/master/litho-sections-widget/src/main/java/com/facebook/litho/sections/widget/RecyclerCollectionComponentSpec.java#L281

You can also call `scrollToPosition` from RecyclerBinder: https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/RecyclerBinder.java#L3043

**Comment by RamiMohammedSeid** [comment]
scrollToPosition is not working properly, most-likely cuz I am using nested-scrolling.

**Comment by RamiMohammedSeid** [comment]
> Hi @RamiMohammedSeid ,
> 
> We already have API for scrolling, check out https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/RecyclerEventsController.java#L91
> 
> You can add it as prop to RecyclerCollectionComponent: https://github.com/facebook/litho/blob/master/litho-sections-widget/src/main/java/com/facebook/litho/sections/widget/RecyclerCollectionComponentSpec.java#L281
> 
> You can also call `scrollToPosition` from RecyclerBinder: https://github.com/facebook/litho/blob/master/litho-widget/src/main/java/com/facebook/litho/widget/RecyclerBinder.java#L3043

Sorry, didn't mention ⬆️
