### ISSUE TITLE
Litho didn't work with Viewpager2

### ISSUE THREAD

**Issue by jingweihu** [facebook/litho#773]
- [ ] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
litho_version = 0.39.0
***Add the version of the litho packages you use. You can paste the dependency
    implementation "com.facebook.litho:litho-fresco:${rootProject.ext.litho_version}"
    implementation "com.facebook.litho:litho-core:${rootProject.ext.litho_version}"
    implementation "com.facebook.litho:litho-widget:${rootProject.ext.litho_version}"
    implementation "com.facebook.litho:litho-sections-core:${rootProject.ext.litho_version}"
    implementation "com.facebook.litho:litho-sections-widget:${rootProject.ext.litho_version}"
    compileOnly "com.facebook.litho:litho-sections-annotations:${rootProject.ext.litho_version}"

## Issues and Steps to Reproduce
All the component will be empty if I create them in fragments that are embedded in ViewPager2

## Expected Behavior
Component should be shown

**Comment by SonicCodes** [comment]
LithoView can't be rendered inside another ScrollView (aka RecyclerView), That's what I learned from a long trial and error session.
