### ISSUE TITLE
Use a ComponentContext pool for scoping

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#78]
Each `Component` is scoped to a `ComponentContext`. This helps us identify, given a `ComponentContext`, which component we are trying to apply a state update to. 
Every time a component gets scoped to a component context, a new component context instance is created and associated with that component.
We should use a `ComponentContext` pool instead of allocating a new `ComponentContext` each time we want to have a `ComponentContext` -> `Component` association

### Code pointers
https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/Component.java#L303

Point of contact: @mihaelao

**Comment by pavlospt** [comment]
Not sure if relevant since it seems to.clone from super instead of creating new Component. But I might definitely be missing something!

**Comment by colriot** [comment]
Pooling was already removed from the codebase as being not very efficient.
Closing as stale
