### ISSUE TITLE
OnCreateMountContentPool not support kotlin 

### ISSUE THREAD

**Issue by liufsd** [facebook/litho#785]
OnCreateMountContentPool not support kotlin ???

`: error: A method annotated with @OnCreateMountContentPool needs to return com.facebook.litho.MountContentPool. Note that even if your return value is a subclass of com.facebook.litho.MountContentPool, you should still use com.facebook.litho.MountContentPool as the return type.
    public final com.facebook.litho.MountContentPool<?> onCreateMountContentPool() `

**Comment by adityasharat** [comment]
Can you please share a patch that reproduces the error?

**Comment by adityasharat** [comment]
This should now work correctly

```
{
  @JvmStatic
  @OnCreateMountContentPool
  fun onCreateMountContentPool(): MountContentPool = DefaultMountContentPool("MyComponent", 3, true)
}
```
