### ISSUE TITLE
How can I help with Doc localization?

### ISSUE THREAD

**Issue by LinXueyuanStdio** [facebook/litho#795]
- [X] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

I'd like to translate the doc to another language, such as Chinese, French, etc.
But I have no idea to post my translated docs and merge to main branch.

Since the official docs only provide English version, it may have a gap between litho and its users.
By the way, there are many pages that have empty content.
It's time to fix the docs!

**Comment by colriot** [comment]
Hi @LinXueyuanStdio ! Thank you for your interest, we are planning bigger documentation workstream for the coming months, it's indeed time to fix the docs! In terms of translation, I don't think we will invest into that before the main docs would be nice. At the same time Docusaurus, which we base our docs on now, has such ability and you can check it out to play and understand the effort: https://docusaurus.io/docs/i18n/introduction
