### ISSUE TITLE
FrescoImage can't support ScaleType well

### ISSUE THREAD

**Issue by philadelphia** [facebook/litho#808]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce

***now i try to use frescoImage to load a remote resouce , and I set blurRadius to this view and scaletype as CenterInside. I don't get an Exception but the image looks wrong. and how to solve it?***

**Comment by philadelphia** [comment]
sorry for my english and hope u can understand

**Comment by colriot** [comment]
Hi @philadelphia ! Can you please share a code that uses FrescoImage and screenshots of the wrong UI with images?

**Comment by philadelphia** [comment]
<img width="376" alt="截屏2021-07-20 下午7 53 19" src="https://user-images.githubusercontent.com/1246126/126319517-b5f0d32c-56a5-4298-bc34-b0764a6c66f8.png">
<img width="369" alt="截屏2021-07-20 下午7 53 52" src="https://user-images.githubusercontent.com/1246126/126319534-6c9d8e5d-b169-45ff-bd5d-e7010bc3c090.png">

![ic_tomcat](https://user-images.githubusercontent.com/1246126/126319601-49827328-f072-41b5-b010-43a79af6adbc.png)

        
       package com.example.lithodemo.ui;
        
        import android.content.Context;
        import android.net.Uri;
        import android.os.Bundle;
        
        import androidx.annotation.Nullable;
        import androidx.appcompat.app.AppCompatActivity;
        
        import com.example.lithodemo.databinding.ActivityMainBinding;
        import com.facebook.drawee.backends.pipeline.DraweeConfig;
        import com.facebook.drawee.backends.pipeline.Fresco;
        import com.facebook.drawee.drawable.ScalingUtils;
        import com.facebook.drawee.generic.RoundingParams;
        import com.facebook.imagepipeline.core.ImagePipelineConfig;
        import com.facebook.litho.ComponentContext;
        import com.facebook.litho.LithoView;
        import com.facebook.litho.fresco.FrescoImage;
        
        public class MainActivity extends AppCompatActivity {
            private static final String RESOURCE_PATH_DRAWABLE = "drawable";
            private static final String RESOURCE_PATH_MIPMAP = "mipmap";
            private static final String RESOURCE_PATH_RAW = "raw";
        
            @Override
            public void onCreate(@Nullable Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                ActivityMainBinding binding = ActivityMainBinding.inflate(getLayoutInflater());
                setContentView(binding.getRoot());
                ComponentContext componentContext = new ComponentContext(this);
                ImagePipelineConfig imagePipelineConfig = ImagePipelineConfig.newBuilder(this).build();
                DraweeConfig draweeConfig = DraweeConfig.newBuilder()
                        .build();
                Fresco.initialize(this, imagePipelineConfig, draweeConfig);
        
                int resId = getResourceId(componentContext.getAndroidContext(), "ic_tomcat");
                String uri = Uri.parse("res://" + componentContext.getAndroidContext().getPackageName() + "/" + resId).toString();
                FrescoImage.Builder builder = FrescoImage.create(componentContext)
                        .widthDip(100)
                        .heightDip(100)
                        .controller(Fresco.newDraweeControllerBuilder().setUri(uri).build());
                builder.actualImageScaleType(ScalingUtils.ScaleType.CENTER_INSIDE);
        
                RoundingParams roundingParams = new RoundingParams();
                roundingParams.setCornersRadius(40);
                builder.roundingParams(roundingParams);
        
                LithoView lithoView = LithoView.create(componentContext, builder.build());
                binding.llViewGroup1.addView(lithoView);
        
                FrescoImage.Builder builder2 = FrescoImage.create(componentContext)
                        .widthDip(100)
                        .heightDip(100)
                        .controller(Fresco.newDraweeControllerBuilder().setUri(uri).build());
                builder2.actualImageScaleType(ScalingUtils.ScaleType.CENTER_INSIDE);
                RoundingParams roundingParams2 = new RoundingParams();
                builder2.roundingParams(roundingParams2);
                LithoView lithoView2 = LithoView.create(componentContext, builder2.build());
                binding.llViewGroup2.addView(lithoView2);
        
            }
        
            /**
             * get resource id by resource name
             *
             * @param context
             * @param resName
             * @return resId
             */
            public int getResourceId(Context context, String resName) {
                int resId = context.getResources().getIdentifier(resName, RESOURCE_PATH_DRAWABLE, context.getPackageName());
                if (resId == 0) {
                    resId = context.getResources().getIdentifier(resName, RESOURCE_PATH_MIPMAP, context.getPackageName());
                }
                if (resId == 0) {
                    resId = context.getResources().getIdentifier(resName, RESOURCE_PATH_RAW, context.getPackageName());
                }
                return resId;
            }
        
        }
