### ISSUE TITLE
Adding layout attributes to an already measured component doesn't work

### ISSUE THREAD

**Issue by emilsjolander** [facebook/litho#83]
When calling `Layout.create(c, component)` after the component has been measured, it causes the subsequent attribute (including the click handler) to be lost.

What happens is that we end up with two internal nodes for the same components and it doesn't work out well. The problem relates to returning early when we call `LayoutState.collectResults()` and `InternalNode.isNestedTreeHolder()` returns true, which is the case when we already have a cached layout for the component associated with the node.

### Code pointers
https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/LayoutState.java#L447

https://github.com/facebook/litho/blob/master/litho-core/src/main/java/com/facebook/litho/InternalNode.java#L369

Point of contact: @marco-cova

**Comment by colriot** [comment]
We have `Wrapper` class for that. 
Closing
