### ISSUE TITLE
Move ComponentInfo to litho-widgets

### ISSUE THREAD

**Issue by lucasr** [facebook/litho#88]
It's an RecyclerBinder API so it should be under litho-widget in the `org.facebook.litho.widget` java package.

Point of contact: @pasqualeanatriello

**Comment by pavlospt** [comment]
Also, this issue seems irrelevant now, in favor of `ComponentRenderInfo`, which lives in `litho-widget`!

**Comment by muraziz** [comment]
@pavlospt indeed! Thanks for pointing out!
