### ISSUE TITLE
"Getting Started" link in README returns 404

### ISSUE THREAD

**Issue by aaronhe42** [facebook/litho#94]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Issues and Steps to Reproduce
At [Installation](https://github.com/facebook/litho#installation) section of the README, the getting started link points to `http://fblitho.com/getting-started` which isn't available. Maybe it should be this page: `http://fblitho.com/docs/getting-started`?

## Expected Behavior
 Should be landed on getting started page.

## Link to Code
[README.md line 19](https://github.com/facebook/litho/blame/master/README.md#L19).

**Comment by IanChilds** [comment]
Thanks for the report. This is fixed by https://github.com/facebook/litho/pull/93

**Comment by aaronhe42** [comment]
lol, race condition..
