### ISSUE TITLE
Unable to import Litho KComponent, ComponentScope and other Litho classes

### ISSUE THREAD

**Issue by connorutting** [facebook/litho#978]
- [x] I have searched [existing issues](https://github.com/facebook/litho/issues) and this is not a duplicate

## Version
0.49.0

## Issues and Steps to Reproduce

1. Create a new project in android studio
<img width="400" alt="Screenshot 2024-03-12 at 2 15 46 PM" src="https://github.com/facebook/litho/assets/163178088/3725bfe9-710f-4046-9a52-475d2a7b1048">

2. Select these settings
<img width="500" alt="Screenshot 2024-03-12 at 2 16 16 PM" src="https://github.com/facebook/litho/assets/163178088/a43e08af-b175-4349-b2d6-9287389fae7a">

3. Update your dependencies in the gradle file
```
dependencies {
    implementation("androidx.core:core-ktx:1.9.0")
    implementation("androidx.appcompat:appcompat:1.6.1")
    implementation("com.google.android.material:material:1.11.0")
    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
    testImplementation("junit:junit:4.13.2")
    androidTestImplementation("androidx.test.ext:junit:1.1.5")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.5.1")

    // Litho
    implementation ("com.facebook.litho:litho-core:0.49.0")
    implementation ("com.facebook.litho:litho-widget:0.49.0")

    // SoLoader
    implementation ("com.facebook.soloader:soloader:0.10.5")

    // For integration with Fresco
    implementation ("com.facebook.litho:litho-fresco:0.49.0")

    // For testing
    testImplementation ("com.facebook.litho:litho-testing:0.49.0")
}
```
4. Run gradle sync

5. Modify your `MainActivity.kt` file like so
```kt
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import com.facebook.litho.Component
import com.facebook.litho.ComponentScope
import com.facebook.litho.KComponent
import com.facebook.litho.LithoView
import com.facebook.litho.kotlin.widget.Text
import com.facebook.rendercore.dp

class MyActivity : AppCompatActivity() {

  override fun onCreate(savedInstanceState: Bundle?) {
    super.onCreate(savedInstanceState)

    val lithoView = LithoView.create(this /* context */, MyComponent())
    setContentView(lithoView)
  }
}

class MyComponent() : KComponent() {
  override fun ComponentScope.render(): Component {
    return Text(text = "Hello, World!", textSize = 50.dp)
  }
}
```

After doing this, I received errors saying "Unresolved reference" for these imports
```kt
import com.facebook.litho.ComponentScope
import com.facebook.litho.KComponent
import com.facebook.litho.kotlin.widget.Text
```

I also couldn't find the classes/imports with "Unresolved reference" in this folder or definition for them
<img width="438" alt="Screenshot 2024-03-12 at 2 35 41 PM" src="https://github.com/facebook/litho/assets/163178088/66fa7a6b-734a-43a2-af5a-feceb0999289">
<img width="500" alt="Screenshot 2024-03-12 at 2 41 07 PM" src="https://github.com/facebook/litho/assets/163178088/ce453d7c-db6d-4494-b374-cf8537272bb4">

## Expected Behavior

I would say the expected behavior is just to import the classes for the tutorial

**Comment by pengj** [comment]
Thanks for reporting the issue. There is a bug in the maven publish plugin and we just revoked back.  Could you please check v0.49.1 if it works for you?

**Comment by connorutting** [comment]
@pengj Hey thanks for getting this resolved it is working, you can close this issue!
